# Enrichment analysis

In [1]:

import GSEA_suit as gsea
import pandas as pd
import numpy as np
import os
import getting_threshold_genes as gtg

In [2]:
def get_selected_genes(csv_file):
    rank_genes = gtg.get_gene_rank(csv_file)
    alpha = gtg.get_inflexion_point_from_gene_rank(rank_genes)
    alpha = 0
    print(alpha)
    gene_rank_df = rank_genes[rank_genes["abs_coef"]>alpha]
    return gene_rank_df

In [12]:
def get_gene_rank_format_cat_temporal(csv_file):
    rank_genes = gtg.get_gene_rank_format_cat_temporal(csv_file)
    gene_rank_df = rank_genes[rank_genes["abs_coef"]>0]
    return gene_rank_df

In [4]:

def get_selected_genes_format_RF(csv_file):
    rank_genes = gtg.get_gene_rank_format_RF(csv_file)
    alpha = gtg.get_inflexion_point_from_gene_rank(rank_genes)
    gene_rank_df = rank_genes[rank_genes["abs_coef"]>alpha]
    return gene_rank_df

In [64]:
algorithm = "smote_catBoost"
database = "Tabula_Sapiens"
database = "KEGG_2021_Human"
database = "SysMyo_Muscle_Gene_Sets"
database = "WikiPathway_2023_Human"
database = "GO_Molecular_Function_2023"

In [65]:
csv_path = f"Results/feature_selection/RNAseq/{algorithm}/"
file_list = os.listdir(csv_path)
file_list = [f for f in file_list if f.endswith('_Symbols.csv')]
file_list

['Status_untrained_feature_selection_Symbols.csv',
 'Experiment_GSE129643_feature_selection_Symbols.csv',
 'Experiment_GSE167186_feature_selection_Symbols.csv',
 'Experiment_GSE152558_feature_selection_Symbols.csv',
 'Sex_male_feature_selection_Symbols.csv',
 'Status_Sarcopenia_feature_selection_Symbols.csv',
 'Status_Healthy_feature_selection_Symbols.csv',
 'feature_importance_Symbols.csv',
 'Experiment_GSE60590_feature_selection_Symbols.csv',
 'Experiment_GSE157585_feature_selection_Symbols.csv',
 'Experiment_GSE164471_feature_selection_Symbols.csv',
 'Sex_female_feature_selection_Symbols.csv',
 'Status_trained_feature_selection_Symbols.csv']

In [66]:
csv_file = 'RNAseq_All_abundances_adjusted_feature_selection_Symbols.csv'
csv_file

'RNAseq_All_abundances_adjusted_feature_selection_Symbols.csv'

In [67]:
sections = []
tms_sections=[]
for csv_file in file_list:#[csv_file]:
    try:
        if "random_forest" in algorithm:
            rank_list = get_selected_genes_format_RF(csv_path + csv_file)
        elif "catBoost" in algorithm:
            rank_list = get_gene_rank_format_cat_temporal(csv_path + csv_file)
        else:
            rank_list = get_selected_genes(csv_path + csv_file)
        symbols = rank_list["Symbol"].tolist()
        #symbols = rank_list["symbol"].tolist()
        symbols = list(set(symbols))
        symbols=symbols[1:]
        coef = rank_list["coef"].tolist()
        #coef = rank_list["V1"].tolist()
        coef = list(set(coef))
        coef=coef[1:]
        dict_list = {"name": csv_file, "symbols": symbols, "coef": coef, "description": "RNAseq Ridge L2 0.1"}
        tms_sections.append(dict_list)
        sets_ranks = {}
        for gene, coef in zip(rank_list["Symbol"], rank_list["abs_coef"]):
            if gene in sets_ranks:
                sets_ranks[gene] += coef
            else:
                sets_ranks[gene] = coef
        sets_ranks = {k: v for k, v in sorted(sets_ranks.items(), key=lambda item: item[1], reverse=True)}
        # asing the value to the dictionary on the position they have
        for i, gene in enumerate(sets_ranks):
            sets_ranks[gene] = i+1
        folder_save = f"Results/feature_selection/RNAseq/{algorithm}/csv_file/"
        results = gsea.get_GSEA(rank_dict=sets_ranks, database= database, min_size=5, outdir=folder_save)
        enrichment = results.res2d
        h_enrichment = enrichment[enrichment['FDR q-val']<0.2]
        dict_list[database] = enrichment
        sections.append(dict_list)

    except Exception as e:
        print("Error with file: ", csv_file, "error ", e)
        #break

# save sections
sections_df = pd.DataFrame(sections)
sections_df.to_csv(f"Results/feature_selection/RNAseq/{algorithm}/enriched/{database}_selected_genes_all.csv", index=False)

/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "Ensembl":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "Ensembl":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "Ensembl":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "Ensembl":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "Ensembl":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "Ensembl":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "Ensembl":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "Ensembl":

Error with file:  feature_importance_Symbols.csv error  Length mismatch: Expected axis has 4 elements, new values have 3 elements

/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "Ensembl":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "Ensembl":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "Ensembl":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:45: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "Ensembl":

In [54]:
sections_df

,name,symbols,coef,description,SysMyo_Muscle_Gene_Sets
0,Status_untrained_feature_selection_Symbols.csv,"[IRX4, AIPL1, C17orf49, ARL8B, IZUMO2, GRWD1, ...","[1.970115291452536, 2.9042267150826917, 3.9094...",RNAseq Ridge L2 0.1,Name ...
1,Experiment_GSE129643_feature_selection_Symbols...,"[ACTR3P2, CAPN1, ELP4, ZNF121, MYH7B, LRPPRC, ...","[1.7582425318889152, 2.166507251782825, 2.6640...",RNAseq Ridge L2 0.1,Name ...
2,Experiment_GSE167186_feature_selection_Symbols...,"[PRRG1, AP2S1, RPS20P28, ACTR3P2, PTCHD1, TP53...","[0.5458501099658291, 2.057193005249359, 0.0739...",RNAseq Ridge L2 0.1,Name ...
3,Experiment_GSE152558_feature_selection_Symbols...,"[ATG9B, UBE2Q2, IQCH, LOC100418961, GNAZ, LOC1...","[1.9901279220570791, 2.8079211032501594, 3.758...",RNAseq Ridge L2 0.1,Name ...
4,Sex_male_feature_selection_Symbols.csv,"[GAL3ST3, ACTR3P2, MYBPH, ESR1, SFXN4, NLN, CF...","[1.9736713356246511, 2.762512760098545, 3.4881...",RNAseq Ridge L2 0.1,Name ...
5,Status_Sarcopenia_feature_selection_Symbols.csv,"[UBE2Q2, CTRL, TRAPPC12, HPS4, NTM, LHFPL2, CA...","[1.3091729359696629, 2.6890252686844542, 2.096...",RNAseq Ridge L2 0.1,Name ...
6,Status_Healthy_feature_selection_Symbols.csv,"[ND5, H2BC4, MDM2, ASZ1, PPP1CC, DNAH10, RPL13...","[1.7266723137657811, 2.764313822893312, 2.5539...",RNAseq Ridge L2 0.1,Name ...
7,Experiment_GSE60590_feature_selection_Symbols.csv,"[MYO1H, DNM1L, PA2G4, HPCAL4, TP53BP2, ICE2, D...","[0.1732370681046982, 2.4617436827937995, 3.220...",RNAseq Ridge L2 0.1,Name ...
8,Experiment_GSE157585_feature_selection_Symbols...,"[ACTR3P2, STAT5A, ZNF121, LRPPRC, PGAP4, CSNK1...","[1.875225423016472, 2.8811194546381182, 2.6983...",RNAseq Ridge L2 0.1,Name ...
9,Experiment_GSE164471_feature_selection_Symbols...,"[RNA5SP35, HMGN3, ABCB4, ARHGAP11B, GPD2, DAAM...","[0.5298044214412352, 2.374448191875903, 2.7162...",RNAseq Ridge L2 0.1,Name ...
10,Sex_female_feature_selection_Symbols.csv,"[ACTR3P2, UPF3B, RNA5SP182, PLAC9P1, LIMA1, ST...","[0.1822991161527705, 2.61535549725249, 2.86243...",RNAseq Ridge L2 0.1,Name ...
11,Status_trained_feature_selection_Symbols.csv,"[CLK3, SLC6A19, PGM3, GPD2, TRDJ2, FSD1, CD19,...","[1.9421899927484096, 2.981429925526937, 3.3694...",RNAseq Ridge L2 0.1,Name ...

In [43]:
tms_sections

[{'name': 'Status_untrained_feature_selection_Symbols.csv',
  'symbols': ['IRX4',
   'AIPL1',
   'C17orf49',
   'ARL8B',
   'IZUMO2',
   'GRWD1',
   'HPCAL4',
   'CCL18',
   'LOC100287355',
   'ECI1',
   'LOC100128865',
   'ZNF580',
   'EFEMP2',
   'THOC3',
   'TMEM232',
   'SLC35A4',
   'TOMM22',
   'ATP6V1A',
   'BCAM',
   'CCDC34',
   'TTTY14',
   'SMAP1',
   'GOLGA6L6',
   'RWDD4',
   'CFLAR',
   'KLHL22',
   'STIP1',
   'ST6GALNAC2',
   'PHBP4',
   'ZNF234',
   'PRPS1L1',
   'DNM1',
   'RPL7P44',
   'RTKN',
   'SMCO1',
   'SORBS1',
   'TACSTD2',
   'AP2A2',
   'VAPA',
   'SETD6',
   'CTTNBP2',
   'APBB2',
   'TRABD',
   'RASGRP1',
   'C7orf25',
   'ELP6',
   'TRPV2',
   'MTND2P9',
   'DNM3',
   'CTCF',
   'ELMO2',
   'PI4KA',
   'SPCS1',
   'ARHGAP1',
   'SMTNL2',
   'CLK1',
   'MYO1A',
   'RPL12P26',
   'UPK3BL2',
   'ZNF219',
   'TPRG1',
   'HIP1R',
   'DSN1',
   'C5orf38',
   'SLC5A6',
   'HSP90AB1',
   'TMEM164',
   'GGA3',
   'PPM1AP1',
   'NBN',
   'CPM',
   'EYA3',
   'TXLNGY',
   'LMTK2',
   'GNS',
   'MAP2K6',
   'NPY6R',
   'C8orf86',
   'PTPRR',
   'NSD1',
   'HMGB1P7',
   'SMARCC2',
   'H4P1',
   'MSN',
   'FUZ',
   'CDIN1',
   'ATXN2',
   'CLK2',
   'ZNF724',
   'MTND3P25',
   'SULT6B1',
   'PHTF1',
   'RPS12P12',
   'AFF1',
   'NPBWR2',
   'AP3S2',
   'ARMC8P1',
   'MAP3K12',
   'FGFR3',
   'HSPE1P19',
   'LMOD2',
   'SUPT20HL1',
   'DPH3',
   'TMEM44',
   'DHRS7C',
   'PLXNA1',
   'MTHFD2',
   'LOC100419786',
   'SRP68P1',
   'RMC1',
   'KDM5D',
   'PCDHGA11',
   'SLC35G6',
   'BNIP3P35',
   'LAGE3',
   'HNRNPA3P3',
   'POT1',
   'ECHDC1',
   'TNNC1',
   'CD163L1',
   'OR7E21P',
   'RPL21P84',
   'C9orf64',
   'CEP170',
   'SPTLC3',
   'FAM181A',
   'FUOM',
   'TAOK2',
   'RNA5SP508',
   'RPL7P3',
   'NBPF1',
   'LRRC34P2',
   'KCNJ11',
   'PCSK2',
   'SLC6A14P3',
   'SWI5',
   'ZNF584',
   'HLA-B',
   'RABGGTB',
   'RPS26P9',
   'CD300LF',
   'TAF11L2',
   'FBXW5',
   'SLC25A30',
   'RPS5P4',
   'FGGY',
   'IRS1',
   'DHX32',
   'WIPF3',
   'COL27A1',
   'HMGN1P13',
   'RPS2P5',
   'UTY',
   'TNNT2',
   'CNTFR',
   'DNAJB1',
   'ACSM5',
   'ERVMER34-1',
   'SELENOF',
   'C1QTNF3',
   'ATG5',
   'PITPNB',
   'FNDC5',
   'OTUD5',
   'CCS',
   'RHOH',
   'DHX9',
   'KIF19',
   'ARMCX1',
   'RNF19A',
   'PRKD1',
   'TMPRSS3',
   'SPIB',
   'FLRT1',
   'ZNF358',
   'GTF2IRD2B',
   'RABGGTA',
   'SLC2A13P1',
   'CFL1P1',
   'UBE2G2',
   'CCDC141',
   'SIDT2',
   'PVRIG',
   'RPS4Y1',
   'TANC1',
   'PRR36',
   'RPS23P2',
   'LIN7B',
   'FLRT2',
   'DNAJC15',
   'CD9',
   'NAA10',
   'RCL1',
   'BLMH',
   'RPL35AP',
   'TLE4',
   'UPK3A',
   'TMEM35A',
   'CCND3',
   'RNA5SP441',
   'NENF',
   'ARHGEF40',
   'STX18',
   'MTX1P1',
   'MAOA',
   'GRB10',
   'RNA5SP418',
   'LRRC34',
   'ZNF273',
   'ENOPH1',
   'USP9Y',
   'CLIP3',
   'IMMP1L',
   'RPL5P20',
   'LCE1E',
   'TBKBP1',
   'CAPNS1',
   'FILIP1',
   'WASF1P1',
   'COMMD4',
   'PACS2',
   'NKAIN1',
   'MASP1',
   'TBL1XR1',
   'ORC3',
   'PAQR4',
   'MNAT1',
   'WASH7P',
   'CYP2A7',
   'TSPAN4',
   'SNPH',
   'NCALD',
   'EXOG',
   'TBPL1',
   'FYTTD1',
   'TEX13D',
   'POLI',
   'USP17L19',
   'RPL14P1',
   'STT3A',
   'IGLVI-42',
   'CLDND2',
   'OXER1',
   'EEF1B2P3',
   'RALB',
   'RTKN2',
   'TTC38',
   'SLC39A7',
   'ZNF688',
   'KCTD20',
   'TIMM10',
   'FAM83E',
   'ASB15',
   'TMA7',
   'NAPA',
   'VMP1'],
  'coef': [1.970115291452536,
   2.9042267150826917,
   3.9094224442852967,
   4.42423482007696,
   4.931030612087022,
   4.827337571227913,
   6.8776120430139445,
   6.0916301348865804,
   3.754575540632816,
   2.8366503790510937,
   2.651721703122422,
   2.113714697221411,
   1.8954070220345187,
   0.0041020450651228,
   5.664223166057833e-05,
   0.009254971775021,
   0.0061139200718019,
   1.1408591962325338e-06,
   0.011482315844916,
   1.5663652829313437,
   1.4284440764578223,
   0.0274382246542071,
   3.465798610957792e-05,
   0.0074091915324226,
   9.178435350111332e-05,
   7.597465824251052e-06,
   0.0001245025036163,
   0.9283546781585632,
   0.8946928694689906,
   0.0002378844980932,
   5.816986907728701e-06,
   1.3932263315408453,
   1.370067535200619,
   0.0002847208993977,
   0.0092039838610898,
   0.0040689354415371,
   5.7384180539154086e-05,
   0.4776542483279591,
   0.0009254603713156,
   0.0002808971466848,
   5.1186898771392536e-05,
   0.0013603244272139,
   0.0152365991343433,
   0.0035610817173404,
   0.0015814302953743,
   5.384552143119738e-05,
   0.0154495694472401,
   0.0063161954363167,
   0.0006997123078121,
   0.1928832963119618,
   0.1830232930878624,
   0.0700163917514707,
   0.0002040281613325,
   1.7384436538406272,
   0.0034973789848867,
   7.075850217858088e-05,
   0.0065549757477679,
   0.0012366857333879,
   0.0138318695164679,
   0.4119394651687085,
   0.0001059140284159,
   1.6833107720680769,
   1.12103831619642,
   0.0045383769710368,
   0.00195248018136,
   0.0004722923803893,
   0.0003900487078126,
   8.843843769572639e-06,
   8.407178977029097e-06,
   7.296157502593951e-05,
   0.046566123899404,
   0.5403382070868346,
   0.0384063475013217,
   0.017137891810781,
   0.0153769024713553,
   0.0127070769868725,
   0.0091018267701473,
   0.0006009053348766,
   0.000459135456006,
   8.612747753127285e-05,
   0.0074943486860533,
   2.2092698988209505,
   0.003239066039801,
   1.2050313235302608e-05,
   0.0026640347903129,
   0.7700938069644978,
   1.164831329893184,
   0.0022698560760373,
   0.0042013723537882,
   0.000967191258817,
   0.1326377710800562,
   0.3260346620173991,
   0.3152462749321388,
   0.3228402457001152,
   0.2909057079331184,
   0.0448183964297631,
   1.5585117569158715,
   0.0003086545625835,
   0.0175759375284717,
   0.014799787096969,
   2.5340591913629087,
   0.0617365731848017,
   0.0002335877588951,
   0.0072649961024523,
   0.0002544225165338,
   0.0029152313612107,
   0.0001416879307768,
   0.0006401075650871,
   0.0036140166105781,
   0.0007927080300328,
   4.418379916453493e-06,
   0.0002356002064899,
   3.777584644811285e-05,
   0.0205218309609206,
   0.0111112227445281,
   6.8657378543188855e-06,
   0.0012173995914991,
   0.0326124418949841,
   1.106975287979952,
   0.0060664882098885,
   0.0048933786666184,
   0.0004484264561416,
   0.0032874129440191,
   0.0010947008624734,
   7.992074508935425e-06,
   6.1191183823020015e-06,
   0.0019479795432987,
   0.1373995107693061,
   0.6141811701844189,
   0.3465299246160809,
   0.2082269361646499,
   0.1249667304667493,
   0.0821399339924751,
   0.0782609123298513,
   0.0020978333238407,
   0.0221423361373104,
   0.001302816924556,
   0.0011790501896721,
   0.0008624943435219,
   0.0009904769242429,
   0.0003675964668842,
   0.0002714847775632,
   3.973790556419796e-05,
   0.0609419509069725,
   0.1955606003661956,
   1.6185628397777052,
   0.1117384057226659,
   4.816724809106379e-06,
   1.2226174084128116e-05,
   0.0003725380488394,
   4.8659545607389485e-05,
   0.0140251368315124,
   0.0071814340471018,
   0.0014685502035413,
   0.0002000878528624,
   0.0008576359025364,
   4.087646864213916e-06,
   0.2935420858133516,
   0.9558685197009126,
   0.5849183601731788,
   0.4702763088256915,
   0.2576259595506204,
   0.1871750900442165,
   1.7450619043868905,
   0.6421372024765685,
   0.5062188703959688,
   0.0270444301324887,
   0.0192824066522358,
   0.0023565137198468,
   0.0010819655935187,
   8.090997287236102e-05,
   4.397304206150253e-05,
   1.3850787455929489e-06,
   4.180187307779361e-05,
   0.0012526120686266,
   0.0030561540289732,
   1.1912865461548971e-05,
   0.0180191546403491,
   0.0001827616494411,
   0.0659654379703979,
   0.000460351086517,
   0.0053559221675933,
   9.135280052032292e-05,
   0.0032685439010899,
   0.0005377262258023,
   0.0004059018782653,
   0.9181960402588956,
   0.000138166913935,
   0.0024645462345251,
   0.0145330377331653,
   0.0022238966291114,
   1.3051220668106656e-05,
   0.1107035637162567,
   0.1960988403295835,
   0.1913410982451639,
   0.0025080305683384,
   0.0005779714044373,
   9.991713650117706e-05,
   8.513150149461264e-05,
   7.222340943666015e-06,
   0.0018126495462342,
   0.0024626402007614,
   0.0141392491404985,
   0.0040409158270999,
   0.0024249318420834,
   0.0013394752820736,
   0.0465701655971326,
   8.467315518526855e-05,
   0.0001414206026528,
   1.6398518788354155e-05,
   0.0132215859423536,
   1.1622506729849004e-05,
   1.0700528015563766,
   1.337204122202015e-05,
   4.570724413105769e-06,
   0.0674922291968613,
   0.0468986881591366,
   4.625698050768416e-05,
   1.0524890619266123,
   0.0001149205505943,
   0.0004205313794327,
   0.0074077333521571,
   0.0022634975843751,
   0.0003094325909691,
   6.935909720600842e-05,
   0.000220075590666,
   0.000109536384786,
   0.015126648806079,
   0.0099178609119121,
   0.2994667622721134,
   0.456335966451685,
   0.3818216254457622,
   0.3498583027032333,
   0.4234579252455854,
   0.8935102004561326,
   1.8738713590467864,
   0.3814420471817019,
   0.0019034583779331,
   0.0006390897469854,
   0.000375339843186,
   9.303188719338427e-06,
   0.0004981946399571,
   0.000607510619905,
   0.0051121705625305,
   0.0001156029359008,
   2.3302423651512348e-05,
   6.526742042775648e-06,
   0.000725047159793,
   0.0011510447002387,
   0.0005456130761456,
   0.0074348800269179,
   0.0039504880093983,
   0.0009931727404346,
   0.0001160756598086,
   0.0008847205602331,
   0.0977381075871366,
   0.2898375316940318,
   0.0022760239215502,
   0.0020134106308944,
   0.0015061990435485,
   1.4934349761697718,
   0.0016850059680877,
   0.0004742494341405,
   1.189877242033665e-06,
   0.041067167374041,
   0.0032967708452862,
   5.066903156126684e-06,
   1.814621948966997e-05,
   0.0035738131304934,
   0.2206485298581695,
   0.1339511356481877,
   0.0514815526573775,
   0.0026389959595092,
   0.0005497148467781,
   0.0002365587309274,
   1.676772706803873,
   0.0010754374509063,
   7.691504290301303e-05,
   0.0016149699398311,
   0.0100321580157132,
   0.0007405890396883,
   0.0375122309937632,
   0.0073772836311665,
   0.0070261719165192,
   0.0750000685619807,
   0.0335774155314492,
   0.0003652019027902,
   0.0002187645087781,
   1.3166904815220077e-06,
   2.663834996984257e-05,
   0.0027906333216554,
   6.267897615396301e-05,
   0.0214702583166284,
   0.0138496811718125,
   0.0008040382584149,
   0.0011973579839386,
   0.008684557755394,
   0.863094943977117,
   0.0001694502796925,
   1.1155444776261303,
   5.958420166085322e-05,
   0.0021649075777721,
   0.0003798407044997,
   0.0034182979499493],
  'description': 'RNAseq Ridge L2 0.1',
  'GO_Molecular_Function_2023':        Name                                               Term        ES  \
  0   prerank  Sequence-Specific Double-Stranded DNA Binding ...  0.738616
  1   prerank                     Metal Ion Binding (GO:0046872)  0.703875
  2   prerank                   Calcium Ion Binding (GO:0005509)  0.743437
  3   prerank  RNA Polymerase II Transcription Regulatory Reg...  0.578058
  4   prerank     Protein Homodimerization Activity (GO:0042803) -0.483871
  5   prerank  RNA Polymerase II Cis-Regulatory Region Sequen...  0.532759
  6   prerank  Cis-Regulatory Region Sequence-Specific DNA Bi...  0.532759
  7   prerank                         Actin Binding (GO:0003779)  0.648116
  8   prerank                           DNA Binding (GO:0003677)  0.650876
  9   prerank                           RNA Binding (GO:0003723)  0.461431
  10  prerank                       GTPase Activity (GO:0003924)  0.544704
  11  prerank  Protein Serine/Threonine Kinase Activity (GO:0...  0.471013
  12  prerank  Ribonucleoside Triphosphate Phosphatase Activi...  0.483846
  13  prerank                Protein Kinase Binding (GO:0019901)  0.372962
  14  prerank  Purine Ribonucleoside Triphosphate Binding (GO...  0.399477
  15  prerank                       Tubulin Binding (GO:0015631)  0.370072
  16  prerank                        Kinase Binding (GO:0019900)  0.340834
  17  prerank                           ATP Binding (GO:0005524)  0.404108
  18  prerank         Adenyl Ribonucleotide Binding (GO:0032559)  0.404108
  19  prerank                      Cadherin Binding (GO:0045296)  0.343731
  20  prerank                   Microtubule Binding (GO:0008017)  0.358566
  21  prerank             GTPase Regulator Activity (GO:0030695)  0.318491
  22  prerank                        GTPase Binding (GO:0051020)  0.261044
  23  prerank                  Small GTPase Binding (GO:0031267)  0.261044
  24  prerank          Transition Metal Ion Binding (GO:0046914)  0.260719
  25  prerank                      Zinc Ion Binding (GO:0008270)  0.258643

           NES NOM p-val FDR q-val FWER p-val Tag %  Gene %  \
  0   1.746536  0.005701  0.092336      0.064   4/7  22.66%
  1   1.590697  0.017483  0.218749      0.249   2/6   7.42%
  2   1.588061    0.0157  0.149497      0.256   2/5   7.42%
  3   1.561936   0.01357  0.140428      0.299  5/13  22.66%
  4  -1.506905  0.058252   0.04237   0.115471   8/8  53.52%
  5   1.421868  0.049318   0.25997      0.611  4/12  22.66%
  6   1.421868  0.049318   0.25997      0.611  4/12  22.66%
  7   1.390147  0.070743  0.273397      0.682   3/5  24.61%
  8   1.389904  0.090909  0.239772      0.683   3/5  22.66%
  9   1.220605  0.193376  0.552673      0.951  8/11  47.27%
  10   1.15429  0.267726  0.668118      0.979   2/5   6.25%
  11  1.106874  0.322323   0.73739      0.987   5/7  50.00%
  12  1.083301  0.345927  0.738322      0.992   3/6  20.31%
  13  1.001586  0.478261  0.898501      0.999  7/12  50.00%
  14   0.98366  0.486517  0.884809        1.0   6/8  48.44%
  15  0.903764  0.601087       1.0        1.0   3/8  19.14%
  16  0.899619   0.62043  0.970834        1.0  6/11  50.00%
  17  0.873899  0.656663  0.914384        1.0   4/5  48.44%
  18  0.873899  0.656663  0.914384        1.0   4/5  48.44%
  19  0.770872  0.794872       1.0        1.0   5/6  57.03%
  20  0.761821  0.811976       1.0        1.0   5/5  64.84%
  21  0.683849  0.908313       1.0        1.0   3/5  44.92%
  22  0.620235  0.953757       1.0        1.0   7/7  74.61%
  23  0.620235  0.953757       1.0        1.0   7/7  74.61%
  24  0.610431   0.94049  0.993163        1.0   6/7  73.83%
  25  0.584516  0.966427  0.967419        1.0   5/6  73.83%

                                             Lead_genes
  0                               ZNF580;SPIB;DHX9;CTCF
  1                                        HPCAL4;NCALD
  2                                        HPCAL4;NCALD
  3                         ZNF580;TBPL1;SPIB;DHX9;CTCF
  4   MASP1;TNNC1;HIP1R;TIMM10;PRPS1L1;EFEMP2;MAP3K1...
  5                               ZNF580;SPIB;DHX9;CTCF
  6                               ZNF580;SPIB;DHX9;CTCF
  7                                    SORBS1;NCALD;MSN
  8                                       DHX9;NBN;CTCF
  9    DHX32;TEX13D;ATXN2;DHX9;MSN;DNM1;FYTTD1;HSP90AB1
  10                                         ARL8B;RHOH
  11                     TAOK2;PRKD1;CLK2;LMTK2;MAP3K12
  12                                    ARL8B;RHOH;DHX9
  13           TAOK2;FAM83E;MSN;IRS1;DNM1;CCND3;MAP3K12
  14              ARL8B;RHOH;DHX9;KCNJ11;HSP90AB1;LMTK2
  15                                  ARL8B;NCALD;CLIP3
  16             FAM83E;MSN;DNM1;CCND3;HSP90AB1;MAP3K12
  17                         DHX9;KCNJ11;HSP90AB1;LMTK2
  18                         DHX9;KCNJ11;HSP90AB1;LMTK2
  19                     DNAJB1;PI4KA;HSP90AB1;CCS;VAPA
  20                         CLIP3;DNM1;VAPA;KIF19;DNM3
  21                                 RHOH;RTKN;ARHGEF40
  22       RHOH;RTKN;GGA3;RABGGTB;ASB15;ARHGAP1;RABGGTA
  23       RHOH;RTKN;GGA3;RABGGTB;ASB15;ARHGAP1;RABGGTA
  24               CTCF;CCS;RABGGTB;RASGRP1;NSD1;TIMM10
  25                   CTCF;RABGGTB;RASGRP1;NSD1;TIMM10  },
 {'name': 'Experiment_GSE129643_feature_selection_Symbols.csv',
  'symbols': ['ACTR3P2',
   'CAPN1',
   'ELP4',
   'ZNF121',
   'MYH7B',
   'LRPPRC',
   'C1GALT1',
   'FZD1',
   'TPTEP1',
   'WDR7',
   'POU2F1',
   'RO60',
   'FAM197Y5',
   'ACSF3',
   'CLYBL',
   'OR1C1',
   'FMNL2',
   'ZPBP2',
   'ARID4B',
   'C5orf38',
   'COX6B1',
   'ZNF772',
   'CTSC',
   'PSMC3',
   'LYNX1-SLURP2',
   'BORCS8-MEF2B',
   'LRP11',
   'NGLY1',
   'SDR42E1',
   'ZNF606',
   'PPM1K',
   'PON2',
   'KRT18P68',
   'ABHD18',
   'PPME1',
   'NDUFV2',
   'SETD5',
   'BMPER',
   'RNA5SP379',
   'ZC3H6',
   'ATP5ME',
   'RNA5SP246',
   'KDM5C',
   'GOLGA8B',
   'HACD1',
   'IQCM',
   'ZSWIM8',
   'FNBP4',
   'GNPDA2',
   'TFE3',
   'P3R3URF',
   'ZNF433',
   'TRAV25',
   'DDX19B',
   'DNAJC19',
   'OR52J2P',
   'OXCT1',
   'MIER1',
   'TPM2',
   'NGRN',
   'MYCBP2',
   'LOC100420008',
   'RPL39P28',
   'PDZD8',
   'ANKRD36',
   'IPO13',
   'AQP7',
   'RNA5SP345',
   'RBM14-RBM4',
   'CLEC16A',
   'HSD17B11',
   'SLC9A6',
   'NPM1P25',
   'CHPT1',
   'MYSM1',
   'PDE4D',
   'TBP',
   'FUT8',
   'SUGP2',
   'MTARC1',
   'RPL7',
   'SLC7A6',
   'LECT2',
   'ZSWIM4',
   'COPS5',
   'MRPL1',
   'USP32P1',
   'RNF7',
   'MDH2',
   'TNFRSF18',
   'NPIPA8',
   'NPIPB11',
   'USP9YP15',
   'DCAF13',
   'RNA5SP241',
   'RNA5SP68',
   'LILRB2',
   'FHL3',
   'LPIN2',
   'SERAC1',
   'UNC80',
   'RNA5SP33',
   'UBASH3A',
   'RBM12B',
   'BNIP3P33',
   'ZDHHC17',
   'BACE1',
   'PDPK1',
   'PDC',
   'XKR8',
   'VWA7',
   'EGR3',
   'LRRC37A5P',
   'DNAJC25-GNG10',
   'TRDV1',
   'ROCK1P1',
   'VN1R80P',
   'OMG',
   'RNA5SP483',
   'TJP3',
   'RNA5SP363',
   'MBTD1',
   'PSME4',
   'PEX11B',
   'FCF1',
   'ERICH2',
   'SDHAP4',
   'MRPL52',
   'ATRX',
   'MTHFD2P7',
   'CLEC3B',
   'SPATA31A3',
   'CDKL1',
   'CPD',
   'PTP4A3',
   'GULP1',
   'DDHD2',
   'TTYH3',
   'SLC38A6',
   'HDGFL2',
   'BICC1',
   'PAN2',
   'CAPN3',
   'HNRNPA1P33',
   'ERFL',
   'BCKDHB',
   'MTHFS',
   'ASCL4',
   'RIMS3',
   'VPS54',
   'FASTKD1',
   'LOC100419562',
   'BBS2',
   'TUBA8',
   'GRM5',
   'ZNF574',
   'UBE2L6',
   'SLC36A3',
   'PRKAG1',
   'PKDCC',
   'UIMC1',
   'BAIAP2',
   'HNF1A',
   'PIK3IP1',
   'TSC22D1',
   'ARHGAP6',
   'KRBOX1',
   'ZSWIM7',
   'CEP57',
   'CFAP61',
   'VGF',
   'TNS2',
   'EHBP1',
   'ZNF681',
   'ARL8B',
   'ZSCAN4',
   'TAOK1',
   'RNA5SP213',
   'RPS13P2',
   'CAPN10',
   'IL17D',
   'ERP29',
   'PLEKHH2',
   'ITPRID2',
   'SLC35E3',
   'WEE2',
   'RNY4P13',
   'SMPX',
   'RNA5SP460',
   'SSR2',
   'CD24',
   'LOC402192',
   'AHSA1',
   'MTND4P24',
   'ZNF770',
   'OR7E47P',
   'FXR2',
   'LOC100129554',
   'SH3BP2',
   'BUD31',
   'KCTD18',
   'PIGN',
   'ZNF875',
   'TLX1',
   'NIPAL2',
   'DCTPP1',
   'FMC1',
   'RIOX2',
   'FERMT2',
   'SPAG9',
   'TMEM237',
   'THNSL2',
   'C6orf118',
   'DDX18',
   'TMEM106C',
   'NANOGNBP2',
   'CTXN3',
   'POLE2',
   'TMEM70',
   'CD163L1',
   'PHF14',
   'PPFIBP2',
   'ST3GAL3',
   'PLPP1',
   'SPATA7',
   'EOLA2',
   'IL1RAP',
   'TRAV9-2',
   'PTGER3',
   'RASEF',
   'RNA5SP105',
   'PHKA1',
   'DOCK7',
   'NADSYN1',
   'PRSS45P',
   'CGN',
   'RPS27AP12',
   'ECSIT',
   'DDX1',
   'NOS2P3',
   'EPM2AIP1',
   'RNA5SP471',
   'SAFB2',
   'SLC2A13P1',
   'NPIPB5',
   'SLC25A27',
   'KRBA2',
   'USP9YP34',
   'ZC3H12A',
   'OR10Q2P',
   'EIF5B',
   'MRPS31',
   'EPS15',
   'PIAS2',
   'ATXN7',
   'RNA5SP217',
   'HDX',
   'BLM',
   'CDK12',
   'RNA5SP159',
   'EHBP1L1',
   'TPM4',
   'CLPTM1LP1',
   'CD34',
   'RNA5SP450',
   'RPL23AP34',
   'SELENOM',
   'FMR1',
   'MFAP5',
   'GSAP',
   'SLC2A7',
   'CCDC39',
   'GCSH',
   'ZNF395',
   'MRPL42',
   'SMAD7',
   'CFH',
   'EBNA1BP2',
   'GCM2',
   'ECI2',
   'RNA5SP402',
   'ABHD12B',
   'ATP6V1G1P4',
   'KRT18P25',
   'STIM2',
   'MORC3',
   'CFTR',
   'METAP1',
   'RBMX2',
   'TEX9',
   'ERV3-1',
   'NOP16',
   'CTAGE10P',
   'MFSD1',
   'ALLC',
   'RPL5P34',
   'EBF3',
   'DYNC1LI2',
   'TUFM',
   'GAR1',
   'KRTCAP3',
   'LGR5',
   'RAI14',
   'USF1',
   'TEX10',
   'DDAH1',
   'RPL36AP20',
   'EXOSC9',
   'SP3',
   'MAGI2',
   'SELENOF',
   'LGR4',
   'TMEM258',
   'AHI1',
   'CNOT4',
   'TRAJ11',
   'TBCK',
   'PGM2L1',
   'NFE2L3',
   'ATP2A2',
   'H2BC9',
   'SNRPD1',
   'RNA5SP374',
   'MAIP1',

In [49]:
h_enrichment#["Term"]

Empty DataFrame
Columns: [Name, Term, ES, NES, NOM p-val, FDR q-val, FWER p-val, Tag %, Gene %, Lead_genes]
Index: []

In [68]:
terms=[]
for enrichment in sections_df[database]:
    terms.append(set(enrichment["Term"].tolist()))
terms

[{'ATP Binding (GO:0005524)',
  'Actin Binding (GO:0003779)',
  'Adenyl Ribonucleotide Binding (GO:0032559)',
  'Cadherin Binding (GO:0045296)',
  'Calcium Ion Binding (GO:0005509)',
  'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
  'DNA Binding (GO:0003677)',
  'GTPase Activity (GO:0003924)',
  'GTPase Binding (GO:0051020)',
  'GTPase Regulator Activity (GO:0030695)',
  'Kinase Binding (GO:0019900)',
  'Metal Ion Binding (GO:0046872)',
  'Microtubule Binding (GO:0008017)',
  'Protein Homodimerization Activity (GO:0042803)',
  'Protein Kinase Binding (GO:0019901)',
  'Protein Serine/Threonine Kinase Activity (GO:0004674)',
  'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
  'RNA Binding (GO:0003723)',
  'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
  'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
  'Ribonucleoside Triphosphate Phosphatase Activity (GO:0017111)',
  'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)',
  'Small GTPase Binding (GO:0031267)',
  'Transition Metal Ion Binding (GO:0046914)',
  'Tubulin Binding (GO:0015631)',
  'Zinc Ion Binding (GO:0008270)'},
 {'ATP Binding (GO:0005524)',
  'Actin Binding (GO:0003779)',
  'Adenyl Ribonucleotide Binding (GO:0032559)',
  'Cadherin Binding (GO:0045296)',
  'Calcium Ion Binding (GO:0005509)',
  'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
  'DNA Binding (GO:0003677)',
  'DNA-binding Transcription Activator Activity, RNA Polymerase II-specific (GO:0001228)',
  'DNA-binding Transcription Factor Binding (GO:0140297)',
  'Double-Stranded DNA Binding (GO:0003690)',
  'GTPase Regulator Activity (GO:0030695)',
  'Kinase Binding (GO:0019900)',
  'Metal Ion Binding (GO:0046872)',
  'Microtubule Binding (GO:0008017)',
  'Protein Heterodimerization Activity (GO:0046982)',
  'Protein Homodimerization Activity (GO:0042803)',
  'Protein Kinase Binding (GO:0019901)',
  'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
  'RNA Binding (GO:0003723)',
  'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
  'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
  'RNA Polymerase II-specific DNA-binding Transcription Factor Binding (GO:0061629)',
  'Sequence-Specific DNA Binding (GO:0043565)',
  'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)',
  'Transcription Cis-Regulatory Region Binding (GO:0000976)',
  'Transition Metal Ion Binding (GO:0046914)',
  'Tubulin Binding (GO:0015631)',
  "mRNA 3'-UTR Binding (GO:0003730)",
  'mRNA Binding (GO:0003729)'},
 {'ATP Binding (GO:0005524)',
  'Adenyl Ribonucleotide Binding (GO:0032559)',
  'Cadherin Binding (GO:0045296)',
  'Calcium Ion Binding (GO:0005509)',
  'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
  'DNA Binding (GO:0003677)',
  'DNA-binding Transcription Activator Activity, RNA Polymerase II-specific (GO:0001228)',
  'DNA-binding Transcription Factor Binding (GO:0140297)',
  'DNA-binding Transcription Repressor Activity, RNA Polymerase II-specific (GO:0001227)',
  'Double-Stranded DNA Binding (GO:0003690)',
  'GTPase Activator Activity (GO:0005096)',
  'GTPase Binding (GO:0051020)',
  'GTPase Regulator Activity (GO:0030695)',
  'Guanyl-Nucleotide Exchange Factor Activity (GO:0005085)',
  'Histone Deacetylase Binding (GO:0042826)',
  'Kinase Binding (GO:0019900)',
  'Metal Ion Binding (GO:0046872)',
  'Phosphatidylinositol Phosphate Binding (GO:1901981)',
  'Protein Heterodimerization Activity (GO:0046982)',
  'Protein Homodimerization Activity (GO:0042803)',
  'Protein Kinase Binding (GO:0019901)',
  'Protein Serine/Threonine Kinase Activity (GO:0004674)',
  'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
  'RNA Binding (GO:0003723)',
  'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
  'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
  'RNA Polymerase II-specific DNA-binding Transcription Factor Binding (GO:0061629)',
  'Sequence-Specific DNA Binding (GO:0043565)',
  'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)',
  'Small GTPase Binding (GO:0031267)',
  'Transcription Cis-Regulatory Region Binding (GO:0000976)',
  'Transcription Regulatory Region Nucleic Acid Binding (GO:0001067)',
  'Transition Metal Ion Binding (GO:0046914)',
  'Ubiquitin-Like Protein Ligase Activity (GO:0061659)',
  'mRNA Binding (GO:0003729)'},
 {'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
  'DNA Binding (GO:0003677)',
  'Double-Stranded DNA Binding (GO:0003690)',
  'GTPase Regulator Activity (GO:0030695)',
  'Protein Homodimerization Activity (GO:0042803)',
  'Protein Serine/Threonine Kinase Activity (GO:0004674)',
  'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
  'RNA Binding (GO:0003723)',
  'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
  'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
  'Sequence-Specific DNA Binding (GO:0043565)',
  'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)'},
 {'ATP Binding (GO:0005524)',
  'Adenyl Ribonucleotide Binding (GO:0032559)',
  'Cadherin Binding (GO:0045296)',
  'Calcium Ion Binding (GO:0005509)',
  'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
  'Cysteine-Type Peptidase Activity (GO:0008234)',
  'DNA Binding (GO:0003677)',
  'DNA-binding Transcription Factor Binding (GO:0140297)',
  'Deubiquitinase Activity (GO:0101005)',
  'Double-Stranded DNA Binding (GO:0003690)',
  'Endopeptidase Activity (GO:0004175)',
  'GTPase Activator Activity (GO:0005096)',
  'GTPase Regulator Activity (GO:0030695)',
  'Guanyl-Nucleotide Exchange Factor Activity (GO:0005085)',
  'Kinase Binding (GO:0019900)',
  'Metal Ion Binding (GO:0046872)',
  'Nuclear Receptor Binding (GO:0016922)',
  'Oxidoreduction-Driven Active Transmembrane Transporter Activity (GO:0015453)',
  'Protein Homodimerization Activity (GO:0042803)',
  'Protein Kinase Binding (GO:0019901)',
  'Protein Phosphatase Binding (GO:0019903)',
  'Protein Serine/Threonine Kinase Activity (GO:0004674)',
  'Protein-Lysine N-methyltransferase Activity (GO:0016279)',
  'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
  'RNA Binding (GO:0003723)',
  'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
  'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
  'Sequence-Specific DNA Binding (GO:0043565)',
  'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)',
  'Transcription Cis-Regulatory Region Binding (GO:0000976)',
  'Transcription Regulatory Region Nucleic Acid Binding (GO:0001067)',
  'Transition Metal Ion Binding (GO:0046914)',
  'Ubiquitin Protein Ligase Binding (GO:0031625)',
  'Ubiquitin-Like Protein Ligase Binding (GO:0044389)',
  'Ubiquitin-Protein Transferase Activity (GO:0004842)',
  'Zinc Ion Binding (GO:0008270)',
  'mRNA Binding (GO:0003729)'},
 {'ATP Binding (GO:0005524)',
  'Adenyl Ribonucleotide Binding (GO:0032559)',
  'Cadherin Binding (GO:0045296)',
  'Cell-Cell Adhesion Mediator Activity (GO:0098632)',
  'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
  'DNA Binding (GO:0003677)',
  'DNA-binding Transcription Activator Activity, RNA Polymerase II-specific (GO:0001228)',
  'DNA-binding Transcription Factor Binding (GO:0140297)',
  'Double-Stranded DNA Binding (GO:0003690)',
  'GTPase Binding (GO:0051020)',
  'GTPase Regulator Activity (GO:0030695)',
  'Guanyl-Nucleotide Exchange Factor Activity (GO:0005085)',
  'Kinase Binding (GO:0019900)',
  'Metal Ion Binding (GO:0046872)',
  'Protein Homodimerization Activity (GO:0042803)',
  'Protein Kinase Activator Activity (GO:0030295)',
  'Protein Kinase Binding (GO:0019901)',
  'Protein Serine/Threonine Kinase Activity (GO:0004674)',
  'Protein Tyrosine Kinase Activity (GO:0004713)',
  'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
  'RNA Binding (GO:0003723)',
  'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
  'RNA Polymerase II Complex Binding (GO:0000993)',
  'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
  'RNA Polymerase II-specific DNA-binding Transcription Factor Binding (GO:0061629)',
  'Sequence-Specific DNA Binding (GO:0043565)',
  'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)',
  'Single-Stranded DNA Binding (GO:0003697)',
  'Transition Metal Ion Binding (GO:0046914)',
  'Ubiquitin-Like Protein Ligase Binding (GO:0044389)',
  'Ubiquitin-Protein Transferase Activity (GO:0004842)',
  'Zinc Ion Binding (GO:0008270)',
  'mRNA Binding (GO:0003729)'},
 {'ATP Binding (GO:0005524)',
  'Adenyl Ribonucleotide Binding (GO:0032559)',
  'Cadherin Binding (GO:0045296)',
  'Calcium Ion Binding (GO:0005509)',
  'Carboxylic Ester Hydrolase Activity (GO:0052689)',
  'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
  'DNA Binding (GO:0003677)',
  'DNA-binding Transcription Activator Activity, RNA Polymerase II-specific (GO:0001228)',
  'DNA-binding Transcription Factor Binding (GO:0140297)',
  'Double-Stranded DNA Binding (GO:0003690)',
  'GTPase Regulator Activity (GO:0030695)',
  'Guanyl Ribonucleotide Binding (GO:0032561)',
  'Histone Deacetylase Binding (GO:0042826)',
  'Kinase Binding (GO:0019900)',
  'Metal Ion Binding (GO:0046872)',
  'Microtubule Binding (GO:0008017)',
  'Monoatomic Cation Channel Activity (GO:0005261)',
  'Oxidoreduction-Driven Active Transmembrane Transporter Activity (GO:0015453)',
  'Phosphatase Binding (GO:0019902)',
  'Protein Heterodimerization Activity (GO:0046982)',
  'Protein Homodimerization Activity (GO:0042803)',
  'Protein Kinase Binding (GO:0019901)',
  'Protein Phosphatase Binding (GO:0019903)',
  'Protein Serine/Threonine Kinase Activity (GO:0004674)',
  'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
  'RNA Binding (GO:0003723)',
  'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
  'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
  'Sequence-Specific DNA Binding (GO:0043565)',
  'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)',
  'Transcription Cis-Regulatory Region Binding (GO:0000976)',
  'Transition Metal Ion Binding (GO:0046914)',
  'Translation Initiation Factor Activity (GO:0003743)',
  'Tubulin Binding (GO:0015631)',
  'Ubiquitin Protein Ligase Activity (GO:0061630)',
  'Ubiquitin Protein Ligase Binding (GO:0031625)',
  'Ubiquitin-Like Protein Ligase Activity (GO:0061659)',
  'Ubiquitin-Like Protein Ligase Binding (GO:0044389)',
  'Ubiquitin-Like Protein Transferase Activity (GO:0019787)',
  'Ubiquitin-Protein Transferase Activity (GO:0004842)',
  'Zinc Ion Binding (GO:0008270)',
  'mRNA Binding (GO:0003729)'},
 {'Adenyl Ribonucleotide Binding (GO:0032559)',
  'Cadherin Binding (GO:0045296)',
  'Calcium Ion Binding (GO:0005509)',
  'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
  'DNA Binding (GO:0003677)',
  'Double-Stranded DNA Binding (GO:0003690)',
  'Endopeptidase Activity (GO:0004175)',
  'Flavin Adenine Dinucleotide Binding (GO:0050660)',
  'GTP Binding (GO:0005525)',
  'GTPase Activator Activity (GO:0005096)',
  'GTPase Activity (GO:0003924)',
  'GTPase Binding (GO:0051020)',
  'GTPase Regulator Activity (GO:0030695)',
  'Guanyl Ribonucleotide Binding (GO:0032561)',
  'Metal Ion Binding (GO:0046872)',
  'Microtubule Binding (GO:0008017)',
  'Protein Homodimerization Activity (GO:0042803)',
  'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
  'RNA Binding (GO:0003723)',
  'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
  'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
  'RNA Polymerase II-specific DNA-binding Transcription Factor Binding (GO:0061629)',
  'Ribonucleoside Triphosphate Phosphatase Activity (GO:0017111)',
  'Sequence-Specific DNA Binding (GO:0043565)',
  'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)',
  'Small GTPase Binding (GO:0031267)',
  'Transcription Cis-Regulatory Region Binding (GO:0000976)',
  'Transition Metal Ion Binding (GO:0046914)',
  'Tubulin Binding (GO:0015631)',
  'Ubiquitin Protein Ligase Binding (GO:0031625)',
  'Ubiquitin-Like Protein Ligase Binding (GO:0044389)',
  'Zinc Ion Binding (GO:0008270)',
  'mRNA Binding (GO:0003729)'},
 {'ATP Binding (GO:0005524)',
  'Adenyl Ribonucleotide Binding (GO:0032559)',
  'Cadherin Binding (GO:0045296)',
  'Calcium Ion Binding (GO:0005509)',
  'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
  'DNA Binding (GO:0003677)',
  'DNA-binding Transcription Activator Activity, RNA Polymerase II-specific (GO:0001228)',
  'DNA-binding Transcription Factor Binding (GO:0140297)',
  'Double-Stranded DNA Binding (GO:0003690)',
  'GTPase Activity (GO:0003924)',
  'GTPase Binding (GO:0051020)',
  'GTPase Regulator Activity (GO:0030695)',
  'Kinase Binding (GO:0019900)',
  'Magnesium Ion Binding (GO:0000287)',
  'Metal Ion Binding (GO:0046872)',
  'Microtubule Binding (GO:0008017)',
  'Protein Homodimerization Activity (GO:0042803)',
  'Protein Kinase Binding (GO:0019901)',
  'Protein Serine/Threonine Kinase Activity (GO:0004674)',
  'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
  'RNA Binding (GO:0003723)',
  'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
  'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
  'RNA Polymerase II-specific DNA-binding Transcription Factor Binding (GO:0061629)',
  'Ribonucleoside Triphosphate Phosphatase Activity (GO:0017111)',
  'Ribosome Binding (GO:0043022)',
  'Sequence-Specific DNA Binding (GO:0043565)',
  'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)',
  'Small GTPase Binding (GO:0031267)',
  'Transcription Cis-Regulatory Region Binding (GO:0000976)',
  'Transcription Regulatory Region Nucleic Acid Binding (GO:0001067)',
  'Transition Metal Ion Binding (GO:0046914)',
  'Tubulin Binding (GO:0015631)',
  'Ubiquitin Protein Ligase Activity (GO:0061630)',
  'Ubiquitin Protein Ligase Binding (GO:0031625)',
  'Ubiquitin-Like Protein Ligase Activity (GO:0061659)',
  'Ubiquitin-Like Protein Ligase Binding (GO:0044389)',
  'Ubiquitin-Like Protein Transferase Activity (GO:0019787)',
  'Ubiquitin-Protein Transferase Activity (GO:0004842)',
  'Zinc Ion Binding (GO:0008270)',
  "mRNA 3'-UTR Binding (GO:0003730)",
  'mRNA Binding (GO:0003729)'},
 {'ATP Binding (GO:0005524)',
  'Acyltransferase Activity, Transferring Groups Other Than Amino-Acyl Groups (GO:0016747)',
  'Adenyl Ribonucleotide Binding (GO:0032559)',
  'Cadherin Binding (GO:0045296)',
  'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
  'DNA Binding (GO:0003677)',
  'DNA-binding Transcription Activator Activity, RNA Polymerase II-specific (GO:0001228)',
  'DNA-binding Transcription Factor Binding (GO:0140297)',
  'Double-Stranded DNA Binding (GO:0003690)',
  'GTPase Regulator Activity (GO:0030695)',
  'Kinase Binding (GO:0019900)',
  'Protein Homodimerization Activity (GO:0042803)',
  'Protein Kinase Binding (GO:0019901)',
  'Protein Serine/Threonine Kinase Activity (GO:0004674)',
  'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
  'RNA Binding (GO:0003723)',
  'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
  'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
  'Sequence-Specific DNA Binding (GO:0043565)',
  'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)',
  'Transcription Cis-Regulatory Region Binding (GO:0000976)',
  'Transition Metal Ion Binding (GO:0046914)',
  'Tubulin Binding (GO:0015631)',
  'Zinc Ion Binding (GO:0008270)',
  'mRNA Binding (GO:0003729)'},
 {'ATP Binding (GO:0005524)',
  'Adenyl Ribonucleotide Binding (GO:0032559)',
  'Cadherin Binding (GO:0045296)',
  'Calcium Ion Binding (GO:0005509)',
  'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
  'DNA Binding (GO:0003677)',
  'DNA-binding Transcription Factor Binding (GO:0140297)',
  'Double-Stranded DNA Binding (GO:0003690)',
  'GTPase Activity (GO:0003924)',
  'GTPase Regulator Activity (GO:0030695)',
  'Kinase Activity (GO:0016301)',
  'Kinase Binding (GO:0019900)',
  'Metal Ion Binding (GO:0046872)',
  'Methylated Histone Binding (GO:0035064)',
  'Methylation-Dependent Protein Binding (GO:0140034)',
  'Microtubule Binding (GO:0008017)',
  'Oxidoreduction-Driven Active Transmembrane Transporter Activity (GO:0015453)',
  'Protease Binding (GO:0002020)',
  'Protein Heterodimerization Activity (GO:0046982)',
  'Protein Homodimerization Activity (GO:0042803)',
  'Protein Kinase Binding (GO:0019901)',
  'Protein Serine/Threonine Kinase Activity (GO:0004674)',
  'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
  'RNA Binding (GO:0003723)',
  'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
  'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
  'RNA Polymerase II-specific DNA-binding Transcription Factor Binding (GO:0061629)',
  'Ribonucleoside Triphosphate Phosphatase Activity (GO:0017111)',
  'Ribosome Binding (GO:0043022)',
  'Sequence-Specific DNA Binding (GO:0043565)',
  'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)',
  'Transcription Cis-Regulatory Region Binding (GO:0000976)',
  'Transcription Regulatory Region Nucleic Acid Binding (GO:0001067)',
  'Tubulin Binding (GO:0015631)',
  'Ubiquitin Protein Ligase Activity (GO:0061630)',
  'Ubiquitin Protein Ligase Binding (GO:0031625)',
  'Ubiquitin-Like Protein Ligase Activity (GO:0061659)',
  'Ubiquitin-Like Protein Ligase Binding (GO:0044389)',
  'Ubiquitin-Protein Transferase Activity (GO:0004842)',
  'mRNA Binding (GO:0003729)'},
 {'ATP Binding (GO:0005524)',
  'Adenyl Ribonucleotide Binding (GO:0032559)',
  'Cadherin Binding (GO:0045296)',
  'Calcium Ion Binding (GO:0005509)',
  'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
  'DNA Binding (GO:0003677)',
  'DNA-binding Transcription Factor Binding (GO:0140297)',
  'Endopeptidase Activity (GO:0004175)',
  'GTPase Activator Activity (GO:0005096)',
  'GTPase Binding (GO:0051020)',
  'GTPase Regulator Activity (GO:0030695)',
  'Guanyl Ribonucleotide Binding (GO:0032561)',
  'Guanyl-Nucleotide Exchange Factor Activity (GO:0005085)',
  'Kinase Binding (GO:0019900)',
  'Metal Ion Binding (GO:0046872)',
  'Microtubule Binding (GO:0008017)',
  'Phosphatidylinositol Binding (GO:0035091)',
  'Protein Homodimerization Activity (GO:0042803)',
  'Protein Kinase Binding (GO:0019901)',
  'Protein Serine/Threonine Kinase Activity (GO:0004674)',
  'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
  'RNA Binding (GO:0003723)',
  'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
  'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
  'Sequence-Specific DNA Binding (GO:0043565)',
  'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)',
  'Small GTPase Binding (GO:0031267)',
  'Transition Metal Ion Binding (GO:0046914)',
  'Tubulin Binding (GO:0015631)',
  'Ubiquitin-Protein Transferase Activity (GO:0004842)',
  'Zinc Ion Binding (GO:0008270)',
  'mRNA Binding (GO:0003729)'}]

In [69]:
intersection = set.intersection(*terms)
intersection

{'Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000987)',
 'DNA Binding (GO:0003677)',
 'GTPase Regulator Activity (GO:0030695)',
 'Protein Homodimerization Activity (GO:0042803)',
 'Purine Ribonucleoside Triphosphate Binding (GO:0035639)',
 'RNA Binding (GO:0003723)',
 'RNA Polymerase II Cis-Regulatory Region Sequence-Specific DNA Binding (GO:0000978)',
 'RNA Polymerase II Transcription Regulatory Region Sequence-Specific DNA Binding (GO:0000977)',
 'Sequence-Specific Double-Stranded DNA Binding (GO:1990837)'}

In [24]:
# name and terms
names = sections_df["name"].tolist()
name_terms = zip(names, terms)
name_terms_df = pd.DataFrame(name_terms, columns=["name", "terms"])

In [36]:
muscles = []
for row in name_terms_df.iterrows():
    term = row[1]["terms"]
    m = False
    for t in term:
        if "muscle" in t.lower() or "myo" in t.lower() or "sarcomere" in t.lower() or \
        "actin" in t.lower() or "myosin" in t.lower() or "fibroblast" in t.lower():
            m = True
            break

    muscles.append(m)
        
name_terms_df["muscle"] = muscles

In [37]:
name_terms_df

,name,terms,muscle,fibroblast
0,Experiment_GSE167186_feature_selection_Symbols...,"{Bone Marrow-erythrocyte, Eye-erythroid Lineag...",False,False
1,Sex_male_feature_selection_Symbols.csv,"{Salivary Gland-monocyte, Vasculature-smooth M...",True,False
2,Status_Sarcopenia_feature_selection_Symbols.csv,{Thymus-erythrocyte},False,False
3,Status_Healthy_feature_selection_Symbols.csv,"{Heart-cardiac Muscle Cell, Prostate-basal Cel...",True,False
4,Experiment_GSE60590_feature_selection_Symbols.csv,"{Bone Marrow-erythrocyte, Thymus-erythrocyte, ...",True,False
5,Experiment_GSE164471_feature_selection_Symbols...,"{Vasculature-pericyte Cell, Vasculature-smooth...",True,False
6,Sex_female_feature_selection_Symbols.csv,"{Muscle-fast Muscle Cell, Thymus-fast Muscle C...",True,False

In [ ]:
list(enrichment['Term'])

In [ ]:
sets_ranks

{'ATP1B4': 1,
 'HMGB2': 2,
 0: 3,
 'FEZ2': 4,
 'CSDE1': 5,
 'RNA5SP123': 6,
 'MTCO1P12': 7,
 'C12orf75': 8,
 'RNA5SP66': 9,
 'LOC440311': 10,
 'NDUFB4': 11,
 'NPY6R': 12,
 'TARS1': 13,
 'IRX3': 14,
 'MYLK4': 15,
 'CFAP61': 16,
 'ACHE': 17,
 'EPC1': 18,
 'RNF10': 19,
 'DUSP3': 20,
 'ANKRD12': 21,
 'MTRNR2L10': 22,
 'XPO5': 23,
 'ERCC1': 24,
 'TLN1': 25,
 'SLC37A4': 26,
 'RNA5SP191': 27,
 'ECH1': 28,
 'BCLAF3': 29,
 'WDR74': 30,
 'AQP1': 31,
 'TRAJ27': 32,
 'PSME4': 33,
 'ACTB': 34,
 'ARHGEF6': 35,
 'KIF2A': 36,
 'RNA5SP237': 37,
 'HK2': 38,
 'PCID2': 39,
 'CDIN1': 40,
 'S100PBP': 41,
 'FUCA2': 42,
 'ERCC5': 43,
 'SNURF': 44,
 'NUDCD3': 45,
 'MTRR': 46,
 'COPZ2': 47,
 'TFDP2': 48,
 'RNA5SP75': 49,
 'RFTN1': 50,
 'RRAS2': 51,
 'PDGFRB': 52,
 'RPS25': 53,
 'NUDT19': 54,
 'ZNF232': 55,
 'TRMT13': 56,
 'MLF1': 57,
 'IGFN1': 58,
 'HCN1': 59,
 'EIF2S1': 60,
 'MAB21L3': 61,
 'MCCC1': 62,
 'TLE1': 63,
 'MTRNR2L2': 64,
 'KIAA1143': 65,
 'POLR3D': 66,
 'CHRNB1': 67,
 'METTL25': 68,
 'MROH7': 69,
 'STRAP': 70,
 'PPP1R1C': 71,
 'CCT5': 72,
 'HSPA4': 73,
 'MTIF2': 74,
 'CELF2': 75,
 'IWS1': 76,
 'RNA5SP402': 77,
 'FGL2': 78,
 'COX7C': 79,
 'ERBB3': 80,
 'RPL5': 81,
 'COL3A1': 82,
 'RRAGB': 83,
 'PITHD1': 84,
 'HACD1': 85,
 'NUB1': 86,
 'CNBD2': 87,
 'ND1': 88,
 'CADM1': 89,
 'NUCKS1': 90,
 'DNAJA2': 91,
 'RNA5SP320': 92,
 'CCDC91': 93,
 'TXLNGY': 94,
 'TASOR2': 95,
 'CDK2AP1': 96,
 'RPL18A': 97,
 'MICAL2': 98,
 'NSMAF': 99,
 'MTSS1': 100,
 'LRP1B': 101,
 'UCP2': 102,
 'PPIL2': 103,
 'NR4A1': 104,
 'MT1X': 105,
 'SAMD4A': 106,
 'CCDC69': 107,
 'THOC1': 108,
 'RNA5SP282': 109,
 'RNA5SP133': 110,
 'STOM': 111,
 'METTL15': 112,
 'MTX2': 113,
 'METAP1': 114,
 'DNAJB6': 115,
 'EPB41L3': 116,
 'EXOC3': 117,
 'GPALPP1': 118,
 'MLEC': 119,
 'NCK1': 120,
 'RBSN': 121,
 'ETS2': 122,
 'BZW1': 123,
 'TSSC4': 124,
 'ACTA2': 125,
 'SLF2': 126,
 'SRP14P4': 127,
 'CAPN10': 128,
 'RNA5SP363': 129,
 'MCEE': 130,
 'CHPT1': 131,
 'CREB1': 132,
 'IFITM1': 133,
 'LGI4': 134,
 'TMLHE': 135,
 'SRFBP1': 136,
 'HMGN5': 137,
 'MYLIP': 138,
 'RNA5SP445': 139,
 'RNA5SP408': 140,
 'SLIRP': 141,
 'WARS1': 142,
 'CREBRF': 143,
 'FBXO4': 144,
 'RPS6KA6': 145,
 'HARS2': 146,
 'ZNF532': 147,
 'SPRTN': 148,
 'C1D': 149,
 'NFYB': 150,
 'XPA': 151,
 'TBX15': 152,
 'SMCO1': 153,
 'MTND4P24': 154,
 'XIRP1': 155,
 'HOMER3': 156,
 'TDG': 157,
 'RNA5SP312': 158,
 'PLPBP': 159,
 'GGPS1': 160,
 'ROCK1': 161,
 'LZIC': 162,
 'NUCB1': 163,
 'CETN2': 164,
 'MTDH': 165,
 'RNA5SP305': 166,
 'TEX2': 167,
 'PPP1R7': 168,
 'UBE3D': 169,
 'EIF3J': 170,
 'FAM83A': 171,
 'TLK1': 172,
 'PFDN5': 173,
 'DCUN1D1': 174,
 'TMEM87A': 175,
 'HBA1': 176,
 'IGHV1-24': 177,
 'TSPAN6': 178,
 'COG3': 179,
 'ADK': 180,
 'DYNC1I2': 181,
 'CPNE3': 182,
 'RFK': 183,
 'KAT14': 184,
 'ANGPTL2': 185,
 'PRKAG1': 186,
 'UBE2V2': 187,
 'TRIM37': 188,
 'SECISBP2': 189,
 'MBTD1': 190,
 'RASSF3': 191,
 'NFKBIA': 192,
 'SGF29': 193,
 'MIER1': 194,
 'PIK3R1': 195,
 'RPLP1': 196,
 'PPP1R1A': 197,
 'QKI': 198,
 'C11orf1': 199,
 'MSL3': 200,
 'FKBP5': 201,
 'BACE1': 202,
 'ITFG2': 203,
 'GPN3': 204,
 'MTRNR2L3': 205,
 'RPRD1B': 206,
 'RNA5SP180': 207,
 'FAM98B': 208,
 'MN1': 209,
 'CCDC66': 210,
 'DDX10': 211,
 'PLCB1': 212,
 'RNA5SP245': 213,
 'NAV1': 214,
 'RASSF8': 215,
 'CUEDC1': 216,
 'RNA5SP258': 217,
 'MYL6B': 218,
 'CCDC186': 219,
 'MIER3': 220,
 'SIMC1': 221,
 'POLK': 222,
 'MTRNR2L11': 223,
 'BCAP31P2': 224,
 'MEIS2': 225,
 'FBXW11': 226,
 'RNA5SP395': 227,
 'CKB': 228,
 'SLC38A1': 229,
 'IMPA2': 230,
 'KIAA0895L': 231,
 'SMIM11': 232,
 'APOD': 233,
 'VMO1': 234,
 'TM9SF2': 235,
 'USP36': 236,
 'C1QTNF6': 237,
 'RNA5SP64': 238,
 'HBB': 239,
 'NAA15': 240,
 'FAU': 241,
 'RNA5SP79': 242,
 'MAP4K5': 243,
 'LAS1L': 244,
 'MYH11': 245,
 'DENR': 246,
 'HECTD2': 247,
 'PPP2R1B': 248,
 'CCDC25': 249,
 'FAM13A': 250,
 'NAMPT': 251,
 'COL1A2': 252,
 'TPRN': 253,
 'TRAJ21': 254,
 'FTSJ1': 255,
 'ARFGEF1': 256,
 'SNRNP27': 257,
 'BAZ2A': 258,
 'RNA5SP512': 259}

In [ ]:
lab_mirna_targets= ["gap43",
"acvr2a",
"hdac9",
"grp78",
"atf6",
"pgc1-a",
"acvr1b",
"NCAM",
"Hmbox1",
"p2ry6",
"camk2a",
"cadps",
"lch1",
"Il1rapl1",
"Carf",
"Aak1",
"P2ry1",
"Yy1",
"Psme3",
"Bach2",
"Smurf2",
"Atp6v1g1",
"Kcnk10",
"Gpx4",
"Psmg4",
"bach2",
"pten",
"p62",
"Prdx6"]
# upper case
lab_mirna_targets = [x.upper() for x in lab_mirna_targets]

In [ ]:
lab_mirna_targets

['GAP43',
 'ACVR2A',
 'HDAC9',
 'GRP78',
 'ATF6',
 'PGC1-A',
 'ACVR1B',
 'NCAM',
 'HMBOX1',
 'P2RY6',
 'CAMK2A',
 'CADPS',
 'LCH1',
 'IL1RAPL1',
 'CARF',
 'AAK1',
 'P2RY1',
 'YY1',
 'PSME3',
 'BACH2',
 'SMURF2',
 'ATP6V1G1',
 'KCNK10',
 'GPX4',
 'PSMG4',
 'BACH2',
 'PTEN',
 'P62',
 'PRDX6']

In [ ]:
sections_df

,name,symbols,coef,description,Tabula_Sapiens
0,feature_importance_Symbols.csv,"[USP36, RFK, CDK2AP1, CETN2, MICAL2, CHRNB1, T...","[0.9576554952824688, 0.4387035937214147, 0.040...",RNAseq Ridge L2 0.1,"Series([], Name: Term, dtype: object)"

In [ ]:
for row in sections_df.iterrows():
    symbols = row[1]["symbols"]
    known_genes = [gene for gene in symbols if gene in lab_mirna_targets]
    print (row[1]["name"], len(known_genes))

feature_importance_Symbols.csv 0

In [ ]:
symbols

['USP36',
 'RFK',
 'CDK2AP1',
 'CETN2',
 'MICAL2',
 'CHRNB1',
 'TASOR2',
 'RNA5SP258',
 'PPP2R1B',
 'LZIC',
 'PRKAG1',
 'TDG',
 'RBSN',
 'XIRP1',
 'MT1X',
 'COL1A2',
 'PITHD1',
 'MTRNR2L3',
 'MYLIP',
 'WDR74',
 'S100PBP',
 'MTRNR2L11',
 'QKI',
 'ND1',
 'IGHV1-24',
 'DUSP3',
 'EPC1',
 'RFTN1',
 'PCID2',
 'MTND4P24',
 'MCCC1',
 'RNA5SP75',
 'RPL5',
 'HACD1',
 'PPP1R1A',
 'TRMT13',
 'POLK',
 'PDGFRB',
 'IFITM1',
 'SNRNP27',
 'TMEM87A',
 'SAMD4A',
 'ROCK1',
 'MYLK4',
 'RNA5SP123',
 'ITFG2',
 'DDX10',
 'IMPA2',
 'SRP14P4',
 'RPL18A',
 'FTSJ1',
 'MTRR',
 'RRAS2',
 'NUCKS1',
 'CNBD2',
 'SLC37A4',
 'EPB41L3',
 'TRAJ21',
 'MBTD1',
 'TBX15',
 'MTRNR2L10',
 'HMGB2',
 'ACHE',
 'FAM98B',
 'PIK3R1',
 'MYH11',
 'MIER3',
 'C1QTNF6',
 'RNA5SP408',
 'NFKBIA',
 'FUCA2',
 'ERBB3',
 'FEZ2',
 'GPN3',
 'SLF2',
 'ARHGEF6',
 'CREB1',
 'MN1',
 'FBXO4',
 'TARS1',
 'RPRD1B',
 'FAM83A',
 'CFAP61',
 'RNA5SP445',
 'METTL25',
 'RNA5SP191',
 'ERCC5',
 'RPS25',
 'MTSS1',
 'HECTD2',
 'MTCO1P12',
 'DYNC1I2',
 'TLN1',
 'HBB',
 'TEX2',
 'RNA5SP395',
 'PPIL2',
 'SMCO1',
 'RNA5SP512',
 'MAB21L3',
 'RNA5SP64',
 'POLR3D',
 'HOMER3',
 'HARS2',
 'TXLNGY',
 'CADM1',
 'MTDH',
 'RNA5SP282',
 'XPA',
 'WARS1',
 'HMGN5',
 'CCDC66',
 'HK2',
 'LAS1L',
 'XPO5',
 'NUCB1',
 'COL3A1',
 'FGL2',
 'KIF2A',
 'STRAP',
 'EIF2S1',
 'MSL3',
 'SMIM11',
 'RNA5SP305',
 'DENR',
 'SLIRP',
 'VMO1',
 'HBA1',
 'RNA5SP402',
 'DNAJA2',
 'SLC38A1',
 'BACE1',
 'AQP1',
 'RNA5SP180',
 'RNA5SP245',
 'C11orf1',
 'IRX3',
 'SPRTN',
 'FAU',
 'APOD',
 'UCP2',
 'FBXW11',
 'NR4A1',
 'HCN1',
 'METTL15',
 'NAMPT',
 'TFDP2',
 'CCT5',
 'IWS1',
 'ERCC1',
 'RASSF3',
 'GPALPP1',
 'MEIS2',
 'SIMC1',
 'CDIN1',
 'UBE2V2',
 'KIAA1143',
 'MTIF2',
 'SRFBP1',
 'PFDN5',
 'BCLAF3',
 'PLPBP',
 'ECH1',
 'MTRNR2L2',
 'CCDC91',
 'NUDCD3',
 'EXOC3',
 'PPP1R1C',
 'NCK1',
 'ETS2',
 'ADK',
 'CCDC186',
 'RPLP1',
 'NAA15',
 'PLCB1',
 'RNA5SP66',
 'ZNF532',
 'KIAA0895L',
 'BAZ2A',
 'NUDT19',
 'PSME4',
 'ACTB',
 'RNA5SP133',
 'CSDE1',
 'RNF10',
 'ARFGEF1',
 'NUB1',
 'COX7C',
 'COG3',
 'NFYB',
 'GGPS1',
 'FAM13A',
 'RASSF8',
 'CREBRF',
 'MCEE',
 'TRIM37',
 'RRAGB',
 'MLEC',
 'FKBP5',
 'CUEDC1',
 'SECISBP2',
 'LRP1B',
 'IGFN1',
 'MTX2',
 'KAT14',
 'MROH7',
 'TPRN',
 'ANKRD12',
 'C1D',
 'NDUFB4',
 'ZNF232',
 'PPP1R7',
 'RNA5SP79',
 'ANGPTL2',
 'CCDC25',
 'ACTA2',
 'RNA5SP312',
 'THOC1',
 'TLE1',
 'CHPT1',
 'SNURF',
 'MIER1',
 'RNA5SP363',
 'TSPAN6',
 'LOC440311',
 'NAV1',
 'C12orf75',
 'LGI4',
 'MYL6B',
 'CELF2',
 'NPY6R',
 'COPZ2',
 'STOM',
 'METAP1',
 'RPS6KA6',
 'DNAJB6',
 'BCAP31P2',
 'CCDC69',
 'MLF1',
 'SGF29',
 'UBE3D',
 'HSPA4',
 'RNA5SP320',
 'BZW1',
 'CAPN10',
 'TMLHE',
 'TLK1',
 'MAP4K5',
 'DCUN1D1',
 'TSSC4',
 'NSMAF',
 'TRAJ27',
 'CKB',
 'ATP1B4',
 'TM9SF2',
 'EIF3J',
 'RNA5SP237',
 'CPNE3']