# Enrichment analysis

In [35]:

import GSEA_suit as gsea
import pandas as pd
import numpy as np
import os
import getting_threshold_genes as gtg

In [36]:
def get_selected_genes(csv_file):
    rank_genes = gtg.get_gene_rank(csv_file)
    alpha = gtg.get_inflexion_point_from_gene_rank(rank_genes)
    gene_rank_df = rank_genes[rank_genes["abs_coef"]>alpha]
    return gene_rank_df

In [37]:

def get_selected_genes_format_RF(csv_file):
    rank_genes = gtg.get_gene_rank_format_RF(csv_file)
    alpha = gtg.get_inflexion_point_from_gene_rank(rank_genes)
    gene_rank_df = rank_genes[rank_genes["abs_coef"]>alpha]
    return gene_rank_df

In [48]:
def get_selected_genes_format_catBoost(csv_file):
    rank_genes = gtg.get_gene_rank_format_cat_temporal(csv_file)
    alpha = 0
    gene_rank_df = rank_genes[rank_genes["abs_coef"]>alpha]
    return gene_rank_df

In [81]:
algorithm = "ridge_L2_0"
#algorithm = "smote_catBoost"
gmt_database = "/home/karen/Documents/phd/Resources/Enrichment_dbs/HALLMARK_MYOGENESIS.v2023.2.Hs.gmt"

database = "Tabula_Sapiens"
database = gmt_database
#database = "KEGG_2021_Human"
#database = "SysMyo_Muscle_Gene_Sets"
#database = "WikiPathway_2023_Human"
#database = "GO_Molecular_Function_2023"

In [73]:
csv_path = f"Results/feature_selection/RNAseq/{algorithm}/"
file_list = os.listdir(csv_path)
file_list = [f for f in file_list if f.endswith('_Symbols.csv')]
file_list

['Experiment_GSE129643_feature_selection_Symbols.csv',
 'Experiment_GSE167186_feature_selection_Symbols.csv',
 'Experiment_GSE152558_feature_selection_Symbols.csv',
 'RNAseq_All_abundances_adjusted_feature_selection_Symbols.csv',
 'Sex_male_feature_selection_Symbols.csv',
 'Status_Sarcopenia_feature_selection_Symbols.csv',
 'Status_Healthy_feature_selection_Symbols.csv',
 'Experiment_GSE60590_feature_selection_Symbols.csv',
 'Experiment_GSE157585_feature_selection_Symbols.csv',
 'Experiment_GSE164471_feature_selection_Symbols.csv',
 'Sex_female_feature_selection_Symbols.csv',
 'Status_trained_feature_selection_Symbols.csv']

In [40]:
csv_file = 'RNAseq_All_abundances_adjusted_feature_selection_Symbols.csv'
csv_file

'RNAseq_All_abundances_adjusted_feature_selection_Symbols.csv'

In [88]:
sections = []

for csv_file in file_list:#[csv_file]:
    try:
        if "random_forest" in algorithm :
            rank_list = get_selected_genes_format_RF(csv_path + csv_file)
        elif "smote_c" in algorithm:
            rank_list = get_selected_genes_format_catBoost(csv_path + csv_file)
        else:
            rank_list = get_selected_genes(csv_path + csv_file)
        symbols = rank_list["Symbol"].tolist()
        #symbols = rank_list["symbol"].tolist()
        symbols = list(set(symbols))
        symbols=symbols[1:]
        coef = rank_list["coef"].tolist()
        #coef = rank_list["V1"].tolist()
        coef = list(set(coef))
        coef=coef[1:]
        dict_list = {"name": csv_file, "symbols": symbols, "coef": coef, "description": f"RNAseq {algorithm}"}
        
        sets_ranks = {}
        for gene, coef in zip(rank_list["Symbol"], rank_list["abs_coef"]):
            if gene in sets_ranks:
                sets_ranks[gene] += coef
            else:
                sets_ranks[gene] = coef
        sets_ranks = {k: v for k, v in sorted(sets_ranks.items(), key=lambda item: item[1], reverse=True)}
        # asing the value to the dictionary on the position they have
        for i, gene in enumerate(sets_ranks):
            sets_ranks[gene] = i+1
        folder_save = f"Results/feature_selection/RNAseq/{algorithm}/csv_file/"
        results = gsea.get_GSEA(rank_dict=sets_ranks, database= database, min_size=1, outdir=folder_save)
        enrichment = results.res2d
        h_enrichment = enrichment[enrichment['FDR q-val']<0.2]
        dict_list[database] = enrichment["Term"]
        sections.append(dict_list)

    except Exception as e:
        print("Error with file: ", csv_file, "error ", e)

# save sections
sections_df = pd.DataFrame(sections)
#sections_df.to_csv(f"Results/feature_selection/RNAseq/{algorithm}/{database}_selected_genes_all.csv", index=False)
sections_df

/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py:945: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*new_inputs, **kwargs)
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/.venv/lib/python3.10/site-packages/numpy/lib/polynomial.py:668: RuntimeWarning: invalid value encountered in divide
  lhs /= scale
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py:945: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*new_inputs, **kwargs)
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/.venv/lib/python3.10/site-packages/numpy/lib/polynomial.py:668: RuntimeWarning: invalid value encountered in divide
  lhs /= scale

Error with file:  ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  5 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 Status_Healthy_feature_selection_Symbols.csv error  SVD did not converge in Linear Least Squares
Error with file:  Experiment_GSE60590_feature_selection_Symbols.csv error  SVD did not converge in Linear Least Squares
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  5 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value

/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":

,name,symbols,coef,description,/home/karen/Documents/phd/Resources/Enrichment_dbs/HALLMARK_MYOGENESIS.v2023.2.Hs.gmt
0,Experiment_GSE129643_feature_selection_Symbols...,"[MTERF3, TRAJ39, ABCE1, YWHAH, STYX, ACSL1, DN...","[0.06874883466850641, -0.04945602400059417, 0....",RNAseq ridge_L2_0,0 HALLMARK_INFLAMMATORY_RESPONSE 1 ...
1,Experiment_GSE167186_feature_selection_Symbols...,"[MTERF3, ALG9, BTBD3, DNAJC2, ABCE1, TAB2, CAM...","[-0.05401227064808972, 0.04958098566201505, 0....",RNAseq ridge_L2_0,0 HALLMARK_INFLAMMATORY_RESPONSE 1 ...
2,Experiment_GSE152558_feature_selection_Symbols...,"[ZNF418, CAPNS1, MYH3, EIF3EP3, RANBP9, TRBV26...","[-0.006172467081098095, 0.01105299609572099, 0...",RNAseq ridge_L2_0,0 HALLMARK_DNA_REPAIR 1 ...
3,RNAseq_All_abundances_adjusted_feature_selecti...,"[MTERF3, SATL1, PATJ, PTMS, CAPZA2, HLA-B, IKB...","[0.1882640921440763, -0.18212858894399941, -1....",RNAseq ridge_L2_0,0 HALLMARK_INFLAMMATORY_RESPONSE 1 ...
4,Sex_male_feature_selection_Symbols.csv,"[SATL1, RNA5SP513, RNA5SP509, RNA5SP48, RNA5SP...","[-0.08499529972192735, 0.14201529597074714, 0....",RNAseq ridge_L2_0,0 HALLMARK_MYOGENESIS 1 ...
5,Status_Sarcopenia_feature_selection_Symbols.csv,"[TCERG1, ABHD1, SATL1, HSPB11, DNAJC2, TAB2, M...","[0.006759327195045021, 0.014183280598438692, 0...",RNAseq ridge_L2_0,0 HALLMARK_DNA_REPAIR 1 ...
6,Experiment_GSE157585_feature_selection_Symbols...,"[EGFL7, TXLNGY, HIGD1A, CCR10, RABEP2, PRRG1, ...","[-0.06730714876104968, 0.05630011864377938, 0....",RNAseq ridge_L2_0,0 HALLMARK_APOPTOSIS 1 HALLM...
7,Experiment_GSE164471_feature_selection_Symbols...,"[SATL1, MYH3, ANKRD23, ABCE1, MAST4, RNA5SP20,...","[0.24704592192589134, 0.1649144498630691, 0.10...",RNAseq ridge_L2_0,0 HALLMARK_DNA_REPAIR 1 ...
8,Sex_female_feature_selection_Symbols.csv,"[EIF3EP3, RNA5SP509, ABCE1, TBCE, TRAJ39, YWHA...","[-0.15791264946863784, 0.12392276183217599, 0....",RNAseq ridge_L2_0,0 HALLMARK_INFLAMMATORY_RESPONSE 1 ...
9,Status_trained_feature_selection_Symbols.csv,"[WNT11, NSL1, TTC23, COLQ, MTERF3, HSPB11, AKR...","[0.00045621832607647907, -0.000460894897275739...",RNAseq ridge_L2_0,0 HALLMARK_DNA_REPAIR 1 HALLM...

In [74]:
algorithm
rank_list
csv_path
csv_file = "RNAseq_All_abundances_adjusted_feature_selection_Symbols.csv"
rank_list = get_selected_genes(csv_path + csv_file)

/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":

In [76]:

sets_ranks = {}
for gene, coef in zip(rank_list["Symbol"], rank_list["coef"]):
    if gene in sets_ranks:
        sets_ranks[gene] += coef
    else:
        sets_ranks[gene] = coef
sets_ranks = {k: v for k, v in sorted(sets_ranks.items(), key=lambda item: item[1], reverse=True)}
sets_ranks

{'APOD': '0.6267889319434388',
 'METTL25': '0.6183406478418709',
 'RNA5SP482': '0.5964238444266273',
 'IFITM1': '0.5915365362312107',
 'HCN1': '0.5618525227180531',
 'MAB21L3': '0.5168269324181688',
 'MTRNR2L8': '0.4577738694115041',
 'TRAJ21': '0.43970394873164187',
 'ST7': '0.43310391117567526',
 'PIK3R1': '0.41494000710154033',
 'UQCRH': '0.40416755105427715',
 'PPDPF': '0.39705713298830414',
 'NCOA2': '0.3900218681656765',
 'ABLIM2': '0.38260048553828063',
 'C3': '0.3747153462732006',
 'KCNMA1': '0.37088737652489245',
 'PKD1P4': '0.35789409501255254',
 'PSMG4': '0.3536770588806263',
 'RNA5SP497': '0.3515611232530883',
 'RERE': '0.33709801293935987',
 'SMBD1P': '0.337058088001567',
 'RNA5SP249': '0.33318264878959736',
 'RNA5SP287': '0.3320683194874301',
 'TSPAN7': '0.33199499256260195',
 'UCP2': '0.32076750668830745',
 'BACE1': '0.3207045120317765',
 'CYP2C9': '0.31840065013926466',
 'EIF5A': '0.3173591520518855',
 'DCUN1D1': '0.3173002182850625',
 'TRAJ9': '0.3172419878643793',
 'GTF2IRD2': '0.31710651983119265',
 'COX14': '0.3164507685762379',
 'MTSS1': '0.31203707265872277',
 'NFKBIA': '0.3099180284342287',
 'MCCC1': '0.30518137569218784',
 'RNA5SP451': '0.3039595505664415',
 'SNW1': '0.30328291551427183',
 'GCC2': '0.29828366607991164',
 'PARM1': '0.2979619156244253',
 'NOLC1': '0.2966369566712703',
 'FEZ2': '0.2963190343013101',
 'UBQLN2': '0.2953390749534136',
 'RNA5SP84': '0.29261496665947373',
 'CFAP61': '0.28919106709051035',
 'KIAA0232': '0.28728617331551387',
 'CITED2': '0.2866596282170677',
 'SERPING1': '0.28658370648525',
 'YAP1': '0.2833514470100027',
 'ARID4B': '0.2822584885016597',
 'KLF13': '0.2810353092067794',
 'PHLDB2': '0.2805119583035043',
 'S100A13': '0.2796016377873377',
 'TRAJ48': '0.2788840020999642',
 'CXXC5': '0.2782640976522748',
 'ANKRD11': '0.2782394637875234',
 'MCEE': '0.27822292654650954',
 'SLC35B1': '0.27789771838112665',
 'HSPB6': '0.27686747617630936',
 'SPIRE1': '0.2765519074213969',
 'LRP1B': '0.27630451627783187',
 'CTBP2': '0.2732949868132549',
 'CDK5RAP1': '0.27159604199090914',
 'TGFBR2': '0.269830295208537',
 'MYOM2': '0.26936013572083795',
 'RNA5SP307': '0.2687957231990292',
 'C12orf75': '0.2671658620993554',
 'ACADSB': '0.26513865425077604',
 'CAMTA2': '0.2648710685779192',
 'PFKFB3': '0.2635105479028766',
 'RNA5SP212': '0.2608423464310369',
 'NUDT19': '0.25802828148897106',
 'LAMB2': '0.25801226262721644',
 'ANKRD12': '0.25760889868653447',
 'RNA5SP365': '0.2565500277189736',
 'CKB': '0.2543620831980631',
 'TMEM140': '0.2537993518979546',
 'KAT2B': '0.253444961146326',
 'RPRD2': '0.25342221806131154',
 'ADK': '0.2519821834177184',
 'PFKFB2': '0.25196854785660805',
 'RPL27': '0.25150293179721844',
 'MTLN': '0.2514517377437282',
 'CASC3': '0.2512537042518285',
 'SGCA': '0.25098549935687525',
 'RNA5SP418': '0.25054532426488196',
 'MAIP1': '0.25031498079056663',
 'CAMK2B': '0.2502913801781589',
 'COX6B1': '0.2499519834982578',
 'SAFB2': '0.24984728123787459',
 'COPB2': '0.2498253489377953',
 'FKBP9': '0.2495091204256139',
 'M6PR': '0.248659805866574',
 'IKBKB': '0.24861576431752969',
 'CD74': '0.24860467080405016',
 'DCTN4': '0.24840539841491294',
 'SEMA6D': '0.24704216513400656',
 'KIAA1143': '0.24698465007725104',
 'KCNQ5': '0.24664788885306776',
 'NCK2': '0.24662670585553226',
 'RNA5SP359': '0.24654278872474988',
 'SLC4A1AP': '0.24543019965495516',
 'FCGR2A': '0.24318801826935593',
 'GLG1': '0.2427814889264121',
 'SLC41A1': '0.24076194154862557',
 'RNA5SP257': '0.2401166892963258',
 'GGA2': '0.2390444707603694',
 'ACSM5': '0.23863408927946383',
 'DDX46': '0.23827758916712222',
 'KIAA0319L': '0.23827441557304846',
 'ZNF844': '0.23715465057268292',
 'MYH8': '0.23662029472429685',
 'CCZ1B': '0.23659117267015844',
 'TRIO': '0.2362933555687701',
 'GPATCH4': '0.2360873198861571',
 'PRNP': '0.23467294107360803',
 'IGKJ2': '0.23462314378933946',
 'HSDL2': '0.23237650595535958',
 'ZNF75A': '0.2323677899484416',
 'SH3RF2': '0.23193995610331725',
 'SPOP': '0.23192972911444576',
 'MN1': '0.22995665255904785',
 'WDR74': '0.22974575298076205',
 'COQ7': '0.22937787493612238',
 'SLC25A23': '0.22935813796145144',
 'SIRT5': '0.2292816845842734',
 'FBXL20': '0.22827829995581017',
 'RNA5SP469': '0.22775230136595875',
 'MTRNR2L3': '0.22757562446165547',
 'USP16': '0.22751341552212745',
 'MEF2D': '0.2265786469286888',
 'RNA5SP120': '0.22634969688636186',
 'SEC63': '0.22624891334006297',
 'SMC3': '0.2228169122929296',
 'PELP1': '0.22257096814772548',
 'ADAMTSL4': '0.2222768325125073',
 'EPB41L3': '0.22121986196570398',
 'PLA2G12A': '0.21988501914794106',
 'MTMR3': '0.21972157679339555',
 'DCXR': '0.21859030140068064',
 'TRAJ6': '0.21843301691756223',
 'RHOB': '0.2183104326263639',
 'RNF181': '0.21827547082057938',
 'MRPL52': '0.21799854171142644',
 'HEXB': '0.21789975823064162',
 'RPS15': '0.21736832833913802',
 'B2M': '0.21715687310146736',
 'HTATSF1': '0.21694883275260812',
 'PFDN5': '0.21693054862349398',
 'TLN2': '0.21608472985648325',
 'CADM1': '0.21565810081492726',
 'H2BC4': '0.21523003232717086',
 'TIMM17B': '0.2151466240533112',
 'PER3': '0.21464209752704197',
 'MYO1C': '0.2141307168306017',
 'HECTD2': '0.21410696877590427',
 'SATL1': '0.21374010716039765',
 'FCRL5': '0.21371319675566536',
 'DUSP10': '0.21222682186260022',
 'BRD8': '0.21210362275029276',
 'RTF1': '0.21174832281569322',
 'PITHD1': '0.21156654046432458',
 'DOK5': '0.2112614094046268',
 'KRR1': '0.21080418360887965',
 'RNF114': '0.21073230640085971',
 'ILRUN': '0.21066803472135776',
 'RAB10': '0.2103779208191135',
 'CREBRF': '0.21027047946994148',
 'TMEM131L': '0.21017623471808267',
 'AGBL1': '0.2098463439891258',
 'ZBTB38': '0.2098025340320272',
 'PITX2': '0.20964568534231953',
 'MAPK3': '0.2093583979942182',
 'DCUN1D2': '0.2089768002278027',
 'PCCB': '0.20842732369919525',
 'PPP1R12A': '0.20839457361349978',
 'PPFIBP2': '0.20836399132162872',
 'MATR3': '0.2081116267911725',
 'MSI2': '0.2080292462431126',
 'CTXN3': '0.2066659821602927',
 'GSTM1': '0.2062074735972304',
 'PCNT': '0.20608354474809132',
 'ZNF462': '0.20599461536281094',
 'ASB8': '0.2055730611724731',
 'H2AC6': '0.20547173637214067',
 'TLE1': '0.20418197826023898',
 'RPRD1B': '0.20414700214135734',
 'LINC00339': '0.20397431312193626',
 'TFPI': '0.2038556425373924',
 'TBC1D14': '0.20371573917657432',
 'LSM4': '0.20357993928555773',
 'TTC1': '0.20344339239113063',
 'FILIP1': '0.20310154302182376',
 'RPL26': '0.2030076556673457',
 'CREB5': '0.20292196240260302',
 'WBP11': '0.20275709271950726',
 'CCDC174': '0.20275396757082143',
 'AZI2': '0.20230606436308682',
 'COG5': '0.20203627022093112',
 'PCF11': '0.20156065438827558',
 'SMAD2': '0.20112100018542814',
 'PIGQ': '0.20098144532735207',
 'KMT2D': '0.20050626129620885',
 'BLOC1S1': '0.19918515358257566',
 'NUCB1': '0.19885028328549964',
 'DPM3': '0.19859990421757945',
 'MRPS31': '0.19858558209272684',
 'MT1X': '0.19777073156947744',
 'NRIP1': '0.19730887592285823',
 'LSM14A': '0.19678494002842684',
 'CKLF': '0.1965502846953746',
 'KDM5D': '0.19638741844196658',
 'ZNF710': '0.19569113549410277',
 'R3HDM2': '0.19490865256614945',
 'PDGFC': '0.19453132275234575',
 'GUK1': '0.19431435438909966',
 'KCTD12': '0.19420721431538068',
 'OR5AS1': '0.19382575330485446',
 'CUL1': '0.19356407791221292',
 'TRAJ60': '0.1934750620447585',
 'BRD2': '0.1933395015556873',
 'SLC44A2': '0.19326795813731568',
 'PDGFA': '0.19292918640129575',
 'BRI3': '0.19224219318348112',
 'ANK1': '0.1917358008733417',
 'HMGB2': '0.19155009208507856',
 'GDAP1': '0.19145480831992895',
 'MPV17': '0.1909900267318775',
 'HMGB1P5': '0.19088980033648',
 'RPL31': '0.19066395378420053',
 'RNA5SP271': '0.19042983508409395',
 'MAP3K7CL': '0.19010314530347702',
 'CACNA1S': '0.19007280861428055',
 'FASTKD1': '0.18985628248627728',
 'RBPJ': '0.18984074412477597',
 'DDT': '0.1895129177641089',
 'PPP1R1C': '0.18945250249178497',
 'TMLHE': '0.18877870161313115',
 'TP63': '0.1882640921440763',
 'KLHL24': '0.18801897303809983',
 'IFTAP': '0.18796551269700484',
 'RNA5SP91': '0.18766939605651675',
 'RNA5SP142': '0.18764537478262283',
 'LGALSL': '0.18740949333155268',
 'NMTRQ-TTG12-1': '0.18725866028162338',
 'CCDC192': '0.18718333147618543',
 'SPPL2A': '0.18691030308329773',
 'RERGL': '0.18688246581283313',
 'KIAA1191': '0.18687272586203207',
 'BEST3': '0.1863575956062889',
 'DERL1': '0.18605849825018483',
 'SCAPER': '0.18600858826346517',
 'ARHGAP10': '0.18599768437364034',
 'MTERF3': '0.18577523708289748',
 'IQCF3': '0.18548994728798024',
 'LAP3': '0.18547107063138762',
 'CXCL14': '0.1853650975025608',
 'NIBAN1': '0.1851801941403971',
 'FKBP15': '0.1850840184773802',
 'ACAD8': '0.18461119836812628',
 'RNA5SP106': '0.18454834573363657',
 'SIVA1': '0.18452840733104342',
 'DEPTOR': '0.18440851056091034',
 'PPHLN1': '0.18405683247887097',
 'WFDC11': '0.18379174305407123',
 'PATJ': '0.18378194545493265',
 'RNA5SP40': '0.18376793573727668',
 'CIR1': '0.18354567809813666',
 'ADAM32': '0.1833196085764095',
 'TSC22D1': '0.18296565245535648',
 'ZSCAN31': '0.18282776843022758',
 'NOSIP': '0.18264066336272133',
 'YWHAB': '0.18243377212719802',
 'ANAPC11': '0.18240108595556534',
 'AP1B1P2': '0.1820905521252698',
 'PDCD6': '0.18206624765909857',
 'RNA5SP373': '0.18190910876161104',
 'CHMP2A': '0.1818447156570646',
 'SP3': '0.18156489658405953',
 'RPL26L1': '0.18137198281873035',
 'ZNF595': '0.18067136800362482',
 'MYLK3': '0.18064795723920818',
 'H1-0': '0.1805863274440745',
 'PPIA': '0.1804408335010223',
 'RNA5SP45': '0.18027717267490506',
 'FAM149B1': '0.1802188453454157',
 'CCDC169': '0.18012897285878196',
 'LOC100419755': '0.17977235175352557',
 'GGT7': '0.17973057361500921',
 'CHPT1': '0.1796297214835883',
 'EIF4ENIF1': '0.179475736194859',
 'FAM13C': '0.1794206290543472',
 'MED30': '0.17939796753519976',
 'MAP1B': '0.17917907022084933',
 'EIF1AY': '0.17882182071509617',
 'TMEM127': '0.1787782790391247',
 'KLHL18': '0.17877328945275756',
 'RPP30': '0.17872501983556405',
 'PUM1': '0.17809358675270492',
 'CDC16': '0.17799340498294666',
 'MVD': '0.17765863311104035',
 'USP6': '0.17741844275433583',
 'COG3': '0.17711651240117754',
 'TOX4': '0.17694539812673948',
 0: '-2.1308006525951155-1.4273564819430242-1.0240295640681656-0.6728335493960275-0.592825866011345-0.5657464652802362-0.56479956667582630.48485358214781943-0.344818851748119050.3372082403560686-0.33339655719603540.33321955752385190.33280534810888784-0.32550459394700526-0.311536689472585-0.30156399591159890.29858594496789215-0.29456082676451395-0.288684344256146750.28590340490371813-0.2742948031353234-0.27176123375305490.2679185025267232-0.26713442143148040.25487831754336230.242272784491693340.240074927746991130.2371595420799183-0.232214945569873960.231326580881961450.23066484486306083-0.22733784343258990.226747815232250350.226672361278403-0.2100198032470884-0.20836357650792453-0.206680950487897860.2022573954465755-0.19988145604964447-0.197044196277522370.19650390863443940.195714376101871920.19475694570767554-0.19064551278358957-0.188476941359710380.180875393746399720.17961837383148550.17829588147387920.17791802994898953',
 'NDUFB4': '-1.844772000690206',
 'RPSA': '-1.3896280537194985',
 'NDUFA4': '-1.332166680598341',
 'NDUFB10': '-1.3241087487403715',
 'MTND4P12': '-1.2853246898468245',
 'SPARC': '-1.243649422231727',
 'PTMS': '-1.1794047835609194',
 'SMTNL2': '-1.07795294072852',
 'COX7B': '-1.0022829293074333',
 'MTCO2P22': '-0.9803486204080862',
 'HDGF': '-0.9580309011261323',
 'EEF1A2': '-0.9381110818064909',
 'MTND6P4': '-0.9313020948979488',
 'RPLP1': '-0.9258505011507181',
 'MACROD1': '-0.8903262884941271',
 'UQCR11': '-0.8725694326146817',
 'POLR2J3': '-0.8319772389619451',
 'COPS6': '-0.8176519785697512',
 'ARIH1': '-0.8168803147980876',
 'USF2': '-0.7963451932628741',
 'MTND4P24': '-0.7928518515027685',
 'MAF1': '-0.6895251129533299',
 'PRDX6': '-0.6857230211648058',
 'XIRP1': '-0.678805371376711',
 'RNA5SP331': '-0.652399814153302',
 'MTRNR2L6': '-0.6446722339503468',
 'CMYA5': '-0.6439264020550738',
 'TUBA4A': '-0.6337699683383539',
 'SNURF': '-0.612891640415128',
 'APEH': '-0.6083072259610688',
 'COL3A1': '-0.5993505094752356',
 'RNA5SP202': '-0.5698132220877571',
 'ATP5F1E': '-0.5674296978239842',
 'NDUFB6': '-0.5595977902645513',
 'MTCO1P40': '-0.5581047370177552',
 'VCP': '-0.5561568896192828',
 'FKBP5': '-0.5541895741547875',
 'RHEB': '-0.5522475659364638',
 'ANXA6': '-0.54193211920905',
 'GPD1': '-0.5356271384225981',
 'MTRNR2L1': '-0.5305856573354281',
 'NMRK2': '-0.5280724474053581',
 'STOM': '-0.5234309078795876',
 'RNA5-8SP6': '-0.5098335123066733',
 'ACTA2': '-0.5054320326819104',
 'TRIM28': '-0.5050543510300576',
 'MTRNR2L11': '-0.5035690212625558',
 'MTRNR2L7': '-0.49920445225818133',
 'AHSA1': '-0.49530736602046554',
 'TMBIM6': '-0.48942927643823403',
 'SCHIP1': '-0.47697780513303223',
 'RNA5SP283': '-0.47281749069854506',
 'TCAP': '-0.4628252559003492',
 'FNDC5': '-0.4538174931538382',
 'RNA5SP408': '-0.4530920358023719',
 'MTCO3P22': '-0.45296533817686546',
 'EPHX1': '-0.45166780605185064',
 'RNA5SP434': '-0.45028035368349245',
 'RNA5SP191': '-0.4484902069353627',
 'IMPA2': '-0.44763992189107865',
 'SPCS2': '-0.44540688263456524',
 'SNX3': '-0.4449281380113238',
 'RNA5SP75': '-0.4369953076927461',
 'SLC25A11': '-0.4367276434554771',
 'COX7A1': '-0.435916998275958',
 'ND1': '-0.4343335761739143',
 'PTP4A1': '-0.4283539875194753',
 'MTRNR2L2': '-0.42801213020334206',
 'TCP1': '-0.4254242345213758',
 'TUFM': '-0.42321342629835246',
 'SEM1': '-0.4211011011038225',
 'ABLIM3': '-0.41805306286101596',
 'ATP6': '-0.4170424536543281',
 'ALDOA': '-0.4129762315095693',
 'ALAS1': '-0.4116830797827842',
 'DQX1': '-0.4107802988345759',
 'DLAT': '-0.409354092272902',
 'FAM162A': '-0.4089823614080629',
 'MTND1P23': '-0.40448366814004255',
 'EP300': '-0.40403720701810747',
 'COX2': '-0.40156638664803035',
 'SDHC': '-0.4015252728655364',
 'RNA5SP392': '-0.3949944630935287',
 'FAF1': '-0.3946783963544317',
 'FABP4': '-0.39112901357813135',
 'RPL21P16': '-0.39106300037577185',
 'NQO2': '-0.384034824793879',
 'FABP3': '-0.38374017569624785',
 'TIMP3': '-0.38130412416731074',
 'ND5': '-0.3795121675825963',
 'RNA5SP72': '-0.37512698775035347',
 'TRAJ49': '-0.37192371259787205',
 'EMC10': '-0.3709319514718494',
 'UQCRC1': '-0.37064061707606594',
 'ND6': '-0.37027644058308584',
 'RNF10': '-0.37009088018085967',
 'RNA5SP24': '-0.3693169744496359',
 'NTPCR': '-0.36777804570938444',
 'NNT': '-0.3663862143909537',
 'TRAJ45': '-0.3634467113882409',
 'NUDCD3': '-0.36169145075467557',
 'USP2': '-0.36122273007321504',
 'RPL13A': '-0.36100757540842837',
 'VWF': '-0.35974689393678727',
 'ZNRF1': '-0.3544885225663481',
 'MYL9': '-0.3538499436902405',
 'TIMM21': '-0.35380062009740504',
 'SAP18': '-0.3524814173943744',
 'ORC6': '-0.34769315555027286',
 'UBA2': '-0.3467693681810078',
 'DOCK10': '-0.34324625750151844',
 'RNA5SP425': '-0.34213459366619575',
 'VGLL2': '-0.3412811806672',
 'CYCS': '-0.34114613640486396',
 'MTCO1P12': '-0.3401690319733655',
 'FBXO3': '-0.3396353585631621',
 'COMMD6': '-0.3380748929126396',
 'RNA5SP450': '-0.3354330778370872',
 'RNA5SP133': '-0.33518000670900927',
 'TMEM120A': '-0.3315986484999376',
 'NPM1': '-0.3295618538154155',
 'ATXN10': '-0.32829750173610317',
 'ASB11': '-0.3276824255875017',
 'PSMD11': '-0.3272349059470755',
 'MAOA': '-0.32711320549757467',
 'RNA5SP290': '-0.32691690398264583',
 'NUDT2': '-0.3251532713516636',
 'SLC25A12': '-0.3245578089587945',
 'UBE2D2': '-0.3239710139683507',
 'IDH3A': '-0.32265763259300906',
 'NRAP': '-0.32210271170519744',
 'CFL1': '-0.32012394127923105',
 'RPS2P5': '-0.3186088262246224',
 'TPI1': '-0.31610888868808806',
 'ERCC1': '-0.31407776407389576',
 'CYB5R1': '-0.313610711891917',
 'ARHGEF9': '-0.31253667392838813',
 'SAMD4A': '-0.3112344128208104',
 'UBC': '-0.30987990686770084',
 'MTRNR2L5': '-0.3094990034291386',
 'RPS4Y1': '-0.3073780492123419',
 'SUMO2': '-0.30547017970276663',
 'RNA5SP180': '-0.30494698801821674',
 'KCNT1': '-0.3047361738258922',
 'ADHFE1': '-0.3031048146248746',
 'LDHA': '-0.300147626305834',
 'DES': '-0.2992964451287847',
 'RBM38': '-0.29929575487403004',
 'ENSA': '-0.2990680811647559',
 'WEE1': '-0.2985599850488402',
 'GRSF1': '-0.29791799676598313',
 'TRAJ19': '-0.296962797922655',
 'MTND5P10': '-0.29480522423452976',
 'RNA5SP442': '-0.2930493503557654',
 'MAPKAPK3': '-0.2918169268925864',
 'ND2': '-0.291155006676771',
 'RNA5SP138': '-0.2868572037993651',
 'PSMF1': '-0.2862730961186969',
 'RNA5SP386': '-0.2854922471019461',
 'STT3B': '-0.2839656077839081',
 'CASQ2': '-0.2833462908094858',
 'POPDC2': '-0.28302652336168044',
 'CHRNA4': '-0.28229297082905885',
 'RNA5SP129': '-0.28111305896170585',
 'ZDHHC7': '-0.28068046202722907',
 'ITGB1BP1': '-0.28041018325886813',
 'C11orf58': '-0.2795082758338184',
 'COX7A2': '-0.2786342151329136',
 'TRAK1': '-0.27824638355692266',
 'TRAPPC2L': '-0.2780465329990619',
 'TLE5': '-0.27654373544935806',
 'AR': '-0.2760290167588672',
 'IGF2': '-0.2749488351878929',
 'GCSH': '-0.27374137948562194',
 'COMMD9': '-0.2727680004596114',
 'HMGN2': '-0.2725460140465725',
 'ANKH': '-0.2720614442330407',
 'CAMK2A': '-0.27170107688185907',
 'ATF1': '-0.26942710338538256',
 'RNA5SP496': '-0.2690523476626365',
 'RNA5SP484': '-0.2686544001140333',
 'ATP6V0E1': '-0.263242176406358',
 'ATP5PB': '-0.26280777242841885',
 'NOL11': '-0.2621977804677205',
 'RTRAF': '-0.26212601732549423',
 'CCT8': '-0.2608476278762176',
 'PRKAG1': '-0.26078563675463545',
 'RNA5SP82': '-0.2606087010317952',
 'RNA5SP206': '-0.2597723591385162',
 'HLA-C': '-0.2590282724778945',
 'RAD23A': '-0.2587265816438435',
 'FHOD1': '-0.25867899930575655',
 'MICOS10': '-0.25831599890635293',
 'COL1A2': '-0.2583073995891994',
 'SCYL2': '-0.2582617936154904',
 'ND4': '-0.2578042891570847',
 'PPIL2': '-0.2577878751827323',
 'UBL7': '-0.25765193975065837',
 'CEP20': '-0.2570931996746144',
 'ATP5MC3': '-0.2559706447382172',
 'RAC1': '-0.25563552887189744',
 'RNASE1': '-0.2549599873937096',
 'RPL9': '-0.25390175893989225',
 'MRPS28': '-0.2524182345257586',
 'RNA5SP276': '-0.2519568332117734',
 'CIZ1': '-0.25066011787149145',
 'VEGFA': '-0.2505544307724965',
 'MFN2': '-0.25045746771187655',
 'ABHD5': '-0.2497407434996638',
 'POLR2L': '-0.2490939549376482',
 'LGALS8': '-0.24871569234388635',
 'MAP2K3': '-0.24723185679042758',
 'RSPO3': '-0.24709973313734368',
 'OPTN': '-0.24563995110978926',
 'MRPS18C': '-0.24478071775596844',
 'EID1': '-0.24444180611750943',
 'CD34': '-0.2441847969526787',
 'RNA5SP64': '-0.2436235439225371',
 'CYTB': '-0.2435784933576024',
 'AGPAT1': '-0.24232863966270968',
 'RRAGD': '-0.24092048423663961',
 'RPS9': '-0.24091766775450518',
 'SRL': '-0.2408991145600469',
 'SDHB': '-0.24075217133682897',
 'SYNC': '-0.24059962188436618',
 'ACTA1': '-0.24041793215568133',
 'IGFN1': '-0.2402971301165181',
 'RAB18': '-0.23977381184292057',
 'HDDC2': '-0.2389435120312003',
 'MICAL2': '-0.2377199182801888',
 'RNA5SP363': '-0.2376324533912348',
 'SLC25A4': '-0.23718223474671024',
 'RNA5SP258': '-0.23680807479253108',
 'MFF': '-0.2364296456474294',
 'MYH9': '-0.23625069680268995',
 'MYL12A': '-0.23603219845694526',
 'COX7C': '-0.23579334715211558',
 'RNA5SP467': '-0.23479263337053502',
 'ABCB6': '-0.23461628748861052',
 'TRPT1': '-0.2333156251940237',
 'SUB1': '-0.23293503587867764',
 'SLC1A3': '-0.23286472443847206',
 'MCF2L2': '-0.23260069724345844',
 'FBXO9': '-0.23239644356169825',
 'PNPLA2': '-0.2319385069550608',
 'SH3BGR': '-0.23118507553976927',
 'RNA5SP382': '-0.2309477086598125',
 'PHTF2': '-0.23061075789718646',
 'UAP1': '-0.2304041516830165',
 'MYOT': '-0.23025969512672267',
 'PARVB': '-0.2297618094810111',
 'NAA15': '-0.22886365053453672',
 'POPDC3': '-0.22878578657721532',
 'SGF29': '-0.22789153922010374',
 'RWDD1': '-0.22770181621690705',
 'TBC1D1': '-0.22713864319974955',
 'ANKRD1': '-0.2267254217636749',
 'ARF4': '-0.22423744473646479',
 'ETFDH': '-0.22360432581756545',
 'RNA5SP78': '-0.2230227812653438',
 'POMGNT1': '-0.22296432392944054',
 'RNA5SP241': '-0.22286726575348675',
 'RAB11A': '-0.22273085510637153',

In [ ]:
# asing the value to the dictionary on the position they have
for i, gene in enumerate(sets_ranks):
    sets_ranks[gene] = i+1

In [78]:
folder_save = f"Results/feature_selection/RNAseq/{algorithm}/csv_file/"

enrichment = gsea.get_GSEA(rank_dict=sets_ranks, database= gmt_database, min_size=5, outdir=folder_save).res2d

/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/.venv/lib/python3.10/site-packages/gseapy/gsea.py:427: RuntimeWarning: invalid value encountered in scalar divide
  dups = rank_metric.apply(lambda df: df.duplicated().sum() / df.size)

In [80]:
algorithm

'ridge_L2_0'

In [79]:
enrichment

Empty DataFrame
Columns: [Name, Term, ES, NES, NOM p-val, FDR q-val, FWER p-val, Tag %, Gene %, Lead_genes]
Index: []

In [ ]:
h_enrichment#["Term"]

Empty DataFrame
Columns: [Name, Term, ES, NES, NOM p-val, FDR q-val, FWER p-val, Tag %, Gene %, Lead_genes]
Index: []

In [85]:
list(enrichment['Term'])

['HALLMARK_MYOGENESIS']

In [ ]:
sets_ranks

{0: 1,
 'KDM5D': 2,
 'EIF1AY': 3,
 'RPS4Y1': 4,
 'GGT7': 5,
 'NPY6R': 6,
 'EGLN3': 7,
 'PUDP': 8,
 'TTTY14': 9,
 'USP9Y': 10,
 'PRKAG3': 11,
 'CAVIN4': 12,
 'TXLNGY': 13,
 'C11orf71': 14,
 'ADAMTSL4': 15,
 'CNNM4': 16,
 'PANK1': 17,
 'CNNM3': 18,
 'PFKFB2': 19,
 'ALDH6A1': 20,
 'ZNF358': 21,
 'MIDN': 22,
 'PATJ': 23,
 'TMEM94': 24,
 'DAPK3': 25,
 'PIK3R1': 26,
 'SNRPN': 27,
 'SLC25A26': 28,
 'NDRG4': 29,
 'CIBAR1': 30,
 'ACTN3': 31,
 'PCGF3': 32,
 'RPL26P6': 33,
 'HPN': 34,
 'UTY': 35,
 'SRPK3': 36,
 'SPATS2L': 37,
 'MOB3C': 38,
 'ILRUN': 39,
 'C4orf54': 40,
 'SLC25A25': 41,
 'GSTM3': 42,
 'RYR3': 43,
 'NMNAT1': 44,
 'ST7': 45,
 'METTL7A': 46,
 'FAH': 47,
 'PTDSS1': 48,
 'C12orf75': 49,
 'PPP1R3B': 50,
 'SLC37A4': 51,
 'CHRDL2': 52,
 'CDK18': 53,
 'ABHD18': 54,
 'DROSHA': 55,
 'LMO1': 56,
 'EIF6': 57,
 'LONRF1': 58,
 'PLAAT3': 59,
 'SLC27A1': 60,
 'CBY1': 61,
 'NEIL2': 62,
 'HYAL1': 63,
 'FRMD6': 64,
 'SRSF1': 65,
 'KIAA1671': 66,
 'VPS35L': 67,
 'FAM118A': 68,
 'CCDC57': 69,
 'SHISA4': 70,
 'GGPS1': 71,
 'IKBKB': 72,
 'BDH1': 73,
 'WNT11': 74,
 'DDX3Y': 75,
 'CYTB': 76,
 'CD99': 77,
 'ACSM5': 78,
 'SFXN5': 79,
 'CCDC69': 80,
 'ORC4': 81,
 'NDFIP2': 82,
 'DTNBP1': 83,
 'GRB10': 84,
 'PHKB': 85,
 'HARS2': 86,
 'CACNA2D3': 87,
 'BNIP3': 88,
 'NAT8L': 89,
 'DAAM2': 90,
 'ZNF273': 91,
 'SNAP29': 92,
 'MED14': 93,
 'PDE4A': 94,
 'OR7E47P': 95,
 'MYL6B': 96,
 'ME3': 97,
 'LINC00869': 98,
 'UCKL1': 99,
 'NUDT16': 100,
 'CACNB1': 101,
 'EIF4A2': 102,
 'OPTN': 103,
 'MDFIC': 104,
 'NINJ2': 105,
 'TPRG1': 106,
 'LACTB': 107,
 'ZFP36L1': 108,
 'ARHGEF10L': 109,
 'UBP1': 110,
 'SGK1': 111,
 'MNAT1': 112,
 'PPP2R2A': 113,
 'CEBPB': 114,
 'PGPEP1L': 115,
 'ECH1': 116,
 'BOLA1': 117,
 'MPP7': 118,
 'DHRS7B': 119,
 'FAM219B': 120,
 'RAB5IF': 121,
 'CD38': 122,
 'CHD4': 123,
 'TRIB1': 124,
 'LDHB': 125,
 'POLR2F': 126,
 'UROD': 127,
 'FBXO3': 128,
 'RBCK1': 129,
 'ATP6V0E2': 130,
 'DGUOK': 131,
 'RIPOR2': 132,
 'DDX3X': 133,
 'NDUFAF4': 134,
 'RASL10B': 135,
 'FHL2': 136,
 'PPP1R14B': 137,
 'HMGN1P13': 138,
 'THUMPD3': 139,
 'POLR2G': 140,
 'CCDC59': 141,
 'NTF4': 142,
 'BCL7B': 143,
 'RPUSD4': 144,
 'CTNNB1': 145,
 'INTS11': 146,
 'SLC25A29': 147,
 'MAPK12': 148,
 'NAA40': 149,
 'GOLGA2P7': 150,
 'PLEKHF1': 151,
 'YIPF4': 152,
 'OTUD1': 153,
 'UROS': 154,
 'VPS72': 155,
 'COQ8A': 156,
 'COX1': 157,
 'TMEM108': 158,
 'GMPS': 159,
 'DPH6': 160,
 'SMTNL2': 161,
 'POLR3H': 162,
 'KLHL21': 163,
 'MCM4': 164,
 'NPHP1': 165,
 'RPL7P3': 166,
 'MTATP6P1': 167,
 'RAB40C': 168,
 'PA2G4': 169,
 'KDM6A': 170,
 'SZRD1': 171,
 'ING1': 172,
 'FASTKD1': 173,
 'CDK2AP2': 174,
 'FAM168B': 175,
 'RGS3': 176,
 'BIN1': 177,
 'DCTD': 178,
 'UBAP1': 179,
 'RPP30': 180,
 'ANAPC15': 181,
 'UNC13B': 182,
 'YJU2B': 183,
 'ALDH1L1': 184,
 'PDLIM7': 185,
 'RTN3': 186,
 'ALDH2': 187,
 'AAGAB': 188,
 'TPSB2': 189,
 'MAFA': 190,
 'GTF3A': 191,
 'GPD1L': 192,
 'TMOD3': 193,
 'PFDN1': 194,
 'BCAT2': 195,
 'STYXL2': 196,
 'BEX3': 197,
 'UBC': 198,
 'SCN4A': 199,
 'SLC41A3': 200,
 'YAF2': 201,
 'SSBP1': 202,
 'C16orf86': 203,
 'EDF1': 204,
 'TMEM38A': 205,
 'SLX9': 206,
 'LAMTOR3': 207,
 'ALDH5A1': 208,
 'CCDC90B': 209,
 'MDH1': 210,
 'METTL21EP': 211,
 'CTSA': 212,
 'GPC1': 213,
 'RCAN2': 214,
 'PLIN5': 215,
 'FABP3': 216,
 'UBE2D4': 217,
 'RETSAT': 218,
 'C1orf198': 219,
 'NFATC1': 220,
 'ARHGEF2': 221,
 'MLYCD': 222,
 'PHKA1': 223,
 'SCUBE2': 224,
 'COPZ2': 225,
 'FGFRL1': 226,
 'RASA4': 227,
 'RAP2C': 228,
 'SMARCD2': 229,
 'TRO': 230,
 'SETD9': 231,
 'RBBP7': 232,
 'PSIP1': 233,
 'ZBTB16': 234,
 'H2AC6': 235,
 'RAP1B': 236,
 'EIF1AX': 237,
 'SART3': 238,
 'COX3': 239,
 'SNRPA1': 240,
 'ASB10': 241,
 'DPP3': 242,
 'MTHFSD': 243,
 'MAP2K5': 244,
 'USP25': 245,
 'P2RX6': 246,
 'DES': 247,
 'PSTPIP2': 248,
 'NUBP2': 249,
 'COMTD1': 250,
 'NFKBIA': 251,
 'RHBDD3': 252,
 'OXNAD1': 253,
 'NENF': 254,
 'SCN1B': 255,
 'SELENOP': 256,
 'LMO2': 257,
 'CETN2': 258,
 'PRKRA': 259,
 'HLA-B': 260,
 'MPC1': 261,
 'HDAC11': 262,
 'ACAD10': 263,
 'KIF9': 264,
 'GREB1L': 265,
 'PGK1': 266,
 'OPLAH': 267,
 'ST3GAL1': 268,
 'NCBP2': 269,
 'ASS1': 270,
 'ACOT11': 271,
 'LMBR1': 272,
 'CCDC43': 273,
 'EFHD1': 274,
 'CTNNBIP1': 275,
 'PLA2G4F': 276,
 'OSBPL6': 277,
 'G6PC3': 278,
 'EDC4': 279,
 'TMEM80': 280,
 'MTHFD2': 281,
 'ROMO1': 282,
 'SIKE1': 283,
 'CSRNP2': 284,
 'NFIB': 285,
 'AHSA1': 286,
 'SEMA4B': 287,
 'PDCD10': 288,
 'PSENEN': 289,
 'SLC29A2': 290,
 'POLB': 291,
 'UGGT1': 292,
 'ADPRHL1': 293,
 'REV1': 294,
 'MASP1': 295,
 'BRWD1': 296,
 'TSPYL2': 297,
 'MYH14': 298,
 'CMSS1': 299,
 'GAPDH': 300,
 'ND4L': 301,
 'SMTNL1': 302,
 'ADHFE1': 303,
 'ATG4D': 304,
 'TBC1D8': 305,
 'TNFRSF1A': 306,
 'SIRT5': 307,
 'ND4': 308,
 'LAMB1': 309,
 'INMT': 310,
 'RNF187': 311,
 'FAM220A': 312,
 'EVL': 313,
 'TIMM21': 314,
 'SLN': 315,
 'BHMT2': 316,
 'SESN1': 317,
 'DOP1B': 318,
 'EEF1AKMT1': 319,
 'PLEKHB1': 320,
 'FGGY': 321,
 'CSTF2T': 322,
 'ACOT2': 323,
 'ANKRD39': 324,
 'ALPK2': 325,
 'DYRK1B': 326,
 'HEXD': 327,
 'ERGIC3': 328,
 'GANC': 329,
 'C11orf1': 330,
 'FGF13': 331,
 'C10orf71': 332,
 'CYB561A3': 333,
 'EML1': 334,
 'ARHGEF6': 335,
 'SYMPK': 336,
 'SGCG': 337,
 'DDX27': 338,
 'MCAT': 339,
 'UBE2H': 340,
 'GGA1': 341,
 'SREBF1': 342,
 'CBX7': 343,
 'EXOSC8': 344,
 'HK2': 345,
 'TMEM120A': 346,
 'CAMK2A': 347,
 'IRAK1': 348,
 'TMEM161A': 349,
 'RPS21': 350,
 'PLIN4': 351,
 'PAICS': 352,
 'TTC23': 353,
 'RIPOR1': 354,
 'PPDPFL': 355,
 'TFEB': 356,
 'RSL1D1': 357,
 'TPM2': 358,
 'NDUFB10': 359,
 'AK6': 360,
 'PAQR4': 361,
 'MSH6': 362,
 'AAMDC': 363,
 'SH3GLB1': 364,
 'KCNQ5': 365,
 'POLL': 366,
 'ECHDC1': 367,
 'SLC25A34': 368,
 'SIAE': 369,
 'ALG1L': 370,
 'TEX30': 371,
 'NXPE3': 372,
 'ESRRA': 373,
 'CDK2': 374,
 'NR4A1': 375,
 'ZFX': 376,
 'HSPB11': 377,
 'MTCO2P22': 378,
 'ZDHHC14': 379,
 'CCDC9': 380,
 'ALKBH7': 381,
 'RNA5SP429': 382,
 'THOC5': 383,
 'PIGS': 384,
 'COQ9': 385,
 'STRBP': 386,
 'NUDT2': 387,
 'NRBP1': 388,
 'ENO1': 389,
 'RSAD1': 390,
 'CD36': 391,
 'PRKCH': 392,
 'ABTB1': 393,
 'C3orf18': 394,
 'ARL6IP4': 395,
 'WDR25': 396,
 'ELMO2': 397,
 'SNU13': 398,
 'ADARB1': 399,
 'LTBP4': 400,
 'ZNF219': 401,
 'ZBTB48': 402,
 'FAM118B': 403,
 'TLCD3B': 404,
 'MSRB2': 405,
 'TMUB1': 406,
 'ZNF362': 407,
 'TMEM185A': 408,
 'KCNA7': 409,
 'ARPC4-TTLL3': 410,
 'UPK3A': 411,
 'NSL1': 412,
 'CASQ2': 413,
 'ATP2B2': 414,
 'THRB': 415,
 'FGFR4': 416,
 'LDAF1': 417,
 'CGRRF1': 418,
 'TMCC1': 419,
 'ZNF429': 420,
 'PODN': 421,
 'OTUB1': 422,
 'MAP6D1': 423,
 'IP6K3': 424,
 'TRBJ2-1': 425,
 'LAYN': 426,
 'MPST': 427,
 'ZNF330': 428,
 'EOGT': 429,
 'MEPCE': 430,
 'RTL8A': 431,
 'DEXI': 432,
 'ATP1B4': 433,
 'COX7A2L': 434,
 'C17orf75': 435,
 'TOLLIP': 436,
 'CBWD6': 437,
 'IFFO1': 438,
 'ANKRD37': 439,
 'COMMD4': 440,
 'NPLOC4': 441,
 'RNA5SP86': 442,
 'RASA4B': 443,
 'CBWD2': 444,
 'GAS8': 445,
 'NFE2L1': 446,
 'QRSL1': 447,
 'QSOX1': 448,
 'PRODH': 449,
 'LMO7': 450,
 'HAUS7': 451,
 'ZNF652': 452,
 'SMARCD1': 453,
 'NR2F2': 454,
 'AOC3': 455,
 'HLA-A': 456,
 'BMPR1A': 457,
 'TMEM150A': 458,
 'PSMC2': 459,
 'AK1': 460,
 'IGKC': 461,
 'CHRAC1': 462,
 'STK25': 463,
 'PIGL': 464,
 'RASSF4': 465,
 'CEBPD': 466,
 'CUTC': 467,
 'SEC61G': 468,
 'TBC1D3': 469,
 'YPEL5': 470,
 'HADHB': 471,
 'NXN': 472,
 'ATF3': 473,
 'AUTS2': 474,
 'MYLPF': 475,
 'TBKBP1': 476,
 'MTHFS': 477,
 'LMOD2': 478,
 'SEC16A': 479,
 'MMP2': 480,
 'KDM5C': 481,
 'RNF44': 482,
 'FNDC5': 483,
 'E2F8': 484,
 'YPEL3': 485,
 'DRAP1': 486,
 'ND1': 487,
 'PHLDB1': 488,
 'MEA1': 489,
 'ETFBKMT': 490,
 'IGFBP3': 491,
 'PDPN': 492,
 'RASSF3': 493,
 'H2BC21': 494,
 'C12orf73': 495,
 'NDUFA10': 496,
 'FBXW5': 497,
 'VEZF1': 498,
 'EIF4G3': 499,
 'HES4': 500,
 'DNASE1L1': 501,
 'COLQ': 502,
 'SLC25A1': 503,
 'EIF2S1': 504,
 'PER3': 505,
 'PSMC4': 506,
 'CLPTM1': 507,
 'PI4KA': 508,
 'HOXA4': 509,
 'ST6GALNAC2': 510,
 'CAPN2': 511,
 'RNF149': 512,
 'MIX23': 513,
 'LANCL2': 514,
 'NR1H3': 515,
 'KLHL41': 516,
 'SHISA2': 517,
 'PPP1R27': 518,
 'AKR1B15': 519,
 'GPNMB': 520,
 'CAMSAP1': 521,
 'TAF4': 522,
 'TRIM55': 523,
 'C2orf88': 524,
 'EIF3FP3': 525,
 'PNKP': 526,
 'PSMG4': 527,
 'STX16-NPEPL1': 528,
 'NUP93': 529,
 'NBDY': 530,
 'COPS7A': 531,
 'ATP8': 532,
 'UBE2Q2': 533,
 'AMPD3': 534,
 'KHNYN': 535,
 'ZMYM2': 536,
 'CSNK2B': 537,
 'MRPL48': 538,
 'CHKB': 539,
 'TBRG4': 540,
 'GAR1': 541,
 'PCCB': 542,
 'SLC25A5': 543,
 'TPD52': 544,
 'ANO6': 545,
 'SULT1A1': 546,
 'PHYH': 547,
 'PAPSS2': 548,
 'MRPS14': 549,
 'KNOP1': 550,
 'HARS1': 551,
 'NPEPL1': 552,
 'MPND': 553,
 'DAZAP1': 554,
 'MRM2': 555,
 'USF2': 556,
 'CASQ1': 557,
 'PYCR1': 558,
 'CADM1': 559,
 'EIF3C': 560,
 'AS3MT': 561,
 'STAG3L4': 562,
 'GLOD4': 563,
 'HPS4': 564,
 'SLAIN2': 565,
 'SAC3D1': 566,
 'KCNT1': 567,
 'PDLIM3': 568,
 'GNB2': 569,
 'PDXK': 570,
 'CTTN': 571,
 'FXN': 572,
 'TRMT1': 573,
 'PCID2': 574,
 'MTND4P24': 575,
 'FZD7': 576,
 'EXOSC9': 577,
 'TMOD4': 578,
 'SLC2A4RG': 579,
 'SPPL3': 580,
 'UBE2V2': 581,
 'HTRA2': 582,
 'SPTB': 583,
 'ADGRE5': 584,
 'HAT1': 585,
 'COMMD6': 586,
 'DYNC2I1': 587,
 'ATP2A1': 588,
 'KANSL3': 589,
 'TM6SF1': 590,
 'CYSTM1': 591,
 'SLC38A7': 592,
 'KALRN': 593,
 'PRKAG1': 594,
 'ENY2': 595,
 'NEURL1': 596,
 'MRPL55': 597,
 'ENO3': 598,
 'C1QA': 599,
 'LGR4': 600,
 'C1orf167': 601,
 'FBXO21': 602,
 'HSPA9': 603,
 'FAM217B': 604,
 'TCEA1': 605,
 'LMNB2': 606,
 'AKR1C2': 607,
 'APIP': 608,
 'UQCRC1': 609,
 'SPTY2D1OS': 610,
 'GATB': 611,
 'ND5': 612,
 'TSEN15': 613,
 'HP1BP3': 614,
 'YIPF7': 615,
 'FHIT': 616,
 'MRPL27': 617,
 'KLHL22': 618,
 'PDLIM1': 619,
 'LYPLAL1': 620,
 'VPS8': 621,
 'DDHD2': 622,
 'RIDA': 623,
 'USP24': 624,
 'MTA2': 625,
 'LACTB2': 626,
 'AFAP1L1': 627,
 'MRPL13': 628,
 'WNK1': 629,
 'UBXN4': 630,
 'DEPP1': 631,
 'GPT': 632,
 'CD74': 633,
 'RPL36': 634,
 'AGAP4': 635,
 'TLE4': 636,
 'PSMD8': 637,
 'HSPE1-MOB4': 638,
 'VEGFA': 639,
 'STYXL1': 640,
 'TFIP11': 641,
 'IL32': 642,
 'ADAMTS9': 643,
 'ABLIM2': 644,
 'NAA60': 645,
 'TTC38': 646,
 'NR2F6': 647,
 'RILPL1': 648,
 'CAV1': 649,
 'DIP2C': 650,
 'RNF167': 651,
 'YWHAB': 652,
 'RFX5': 653,
 'SSPN': 654,
 'MPDU1': 655,
 'PLEC': 656,
 'VPS41': 657,
 'SCHIP1': 658,
 'FADS3': 659,
 'DPH1': 660,
 'PNMT': 661,
 'IGLC3': 662,
 'APTX': 663,
 'NANOS1': 664,
 'DHX9': 665,
 'CYP3A54P': 666,
 'LITAF': 667,
 'MED15': 668,
 'SPIDR': 669,
 'TRMT2A': 670,
 'SLC29A1': 671,
 'DALRD3': 672,
 'PLIN2': 673,
 'CHCHD3': 674,
 'TNNI3': 675,
 'MPPED2': 676,
 'TMEM273': 677,
 'SPG21': 678,
 'DDX24': 679,
 'FAM238C': 680,
 'EBPL': 681,
 'SPAG9': 682,
 'SLC1A4': 683,
 'TNIP2': 684,
 'MYADML2': 685,
 'CTSH': 686,
 'SLC25A23': 687,
 'NARS1': 688,
 'GTF3C3': 689,
 'TSPAN4': 690,
 'COQ5': 691,
 'WDR12': 692,
 'ZIC1': 693,
 'NPM3': 694,
 'PI4KB': 695,
 'S100A6': 696,
 'CSNK2A1': 697,
 'ZEB2': 698,
 'ST3GAL3': 699,
 'ASB15': 700,
 'TIPRL': 701,
 'USP46': 702,
 'CD164': 703,
 'CDC42': 704,
 'AKTIP': 705,
 'EEF1A2': 706,
 'CENPP': 707,
 'ATP23': 708,
 'BUB3': 709,
 'HAUS4': 710,
 'DHRS4': 711,
 'ITSN1': 712,
 'AQP7': 713,
 'SYNGAP1': 714,
 'PUF60': 715,
 'H1-2': 716,
 'PARD3': 717,
 'EPN2': 718,
 'XRCC5': 719,
 'COPS7B': 720,
 'ACSL1': 721,
 'SP100': 722,
 'DUSP13': 723,
 'TSR3': 724,
 'RNF41': 725,
 'CDK16': 726,
 'HEXIM2': 727,
 'FOXO3': 728,
 'LRRC23': 729,
 'PPM1B': 730,
 'UPF3A': 731,
 'IFT46': 732,
 'TPD52L1': 733,
 'SAFB2': 734,
 'CFAP95': 735,
 'PDPR': 736,
 'CYB5R1': 737,
 'VASP': 738,
 'PEX19': 739,
 'ATP6V0B': 740,
 'TIMM10': 741,
 'BIRC6': 742,
 'PDGFRL': 743,
 'BRD8': 744,
 'IGLC2': 745,
 'DPH7': 746,
 'IPO11': 747,
 'DESI1': 748,
 'NADK': 749,
 'PPP1R16A': 750,
 'H2AC18': 751,
 'MPDZ': 752,
 'EIF3B': 753,
 'UBE2Q1': 754,
 'SMARCA5': 755,
 'TKFC': 756,
 'ZRSR2': 757,
 'PPP6R1': 758,
 'HIBCH': 759,
 'TMEM161B': 760,
 'U2AF1': 761,
 'PSMA7': 762,
 'SLC44A1': 763,
 'HEXIM1': 764,
 'UBALD2': 765,
 'MTFR1L': 766,
 'PTRHD1': 767,
 'ORAI1': 768,
 'EXOC6': 769,
 'TRBJ2-6': 770,
 'WDR47': 771,
 'E2F4': 772,
 'ND3': 773,
 'POP7': 774,
 'MAP1LC3A': 775,
 'MAP4': 776,
 'PHC1': 777,
 'UBE2S': 778,
 'CIPC': 779,
 'IGKJ2': 780,
 'GLCE': 781,
 'IGSF8': 782,
 'TMEM43': 783,
 'PPP2R3C': 784,
 'TOMM40': 785,
 'TCF3': 786,
 'TMEM141': 787,
 'MTND2P28': 788,
 'STMP1': 789,
 'CCS': 790,
 'GPSM2': 791,
 'SMIM7': 792,
 'AMDHD1': 793,
 'CDADC1': 794,
 'FLYWCH1': 795,
 'CD55': 796,
 'SH2B1': 797,
 'GATM': 798,
 'PSPC1': 799,
 'DYRK2': 800,
 'SMIM27': 801,
 'ZNF784': 802,
 'FGFR1OP2': 803,
 'NOLC1': 804,
 'LIFR': 805,
 'POLE': 806,
 'ZNF91': 807,
 'BABAM1': 808,
 'FBLN2': 809,
 'NUDT16L1': 810,
 'THBD': 811,
 'UBXN1': 812,
 'SMTN': 813,
 'SMO': 814,
 'KHSRP': 815,
 'RAB11FIP3': 816,
 'AURKA': 817,
 'EN1': 818,
 'MBNL2': 819,
 'RUVBL2': 820,
 'CAVIN3': 821,
 'RHBDF2': 822,
 'MRPL35': 823,
 'NRG4': 824,
 'POLE4': 825,
 'NNMT': 826,
 'ALPK3': 827,
 'ZNF682': 828,
 'ACADVL': 829,
 'RND3': 830,
 'ADCY3': 831,
 'GOLGA7': 832,
 'TLE1': 833,
 'ST3GAL5': 834,
 'SLC39A3': 835,
 'PCNT': 836,
 'PARVB': 837,
 'PPP2R5D': 838,
 'MED25': 839,
 'NDUFAF6': 840,
 'TAL2': 841,
 'GDE1': 842,
 'LRMDA': 843,
 'FIBP': 844,
 'RETREG2': 845,
 'TP63': 846,
 'PHF23': 847,
 'HSD11B1L': 848,
 'C11orf49': 849,
 'CCDC141': 850,
 'AKAP13': 851,
 'IDS': 852,
 'PRKD2': 853,
 'WBP1': 854,
 'ARFGAP2': 855,
 'TMEM222': 856,
 'TMEM9B': 857,
 'EMC1': 858,
 'SP2': 859,
 'SLC26A9': 860,
 'SBF2': 861,
 'ZNF598': 862,
 'CERS1': 863,
 'SLC40A1': 864,
 'VPS26B': 865,
 'PNPLA6': 866,
 'RGS14': 867,
 'SEPTIN4': 868,
 'CACNG6': 869,
 'TMEM106C': 870,
 'SNTA1': 871,
 'MRPL19': 872,
 'UBE2L6': 873,
 'ZBTB7B': 874,
 'PEBP4': 875,
 'PEX2': 876,
 'RYR1': 877,
 'ZADH2': 878,
 'SAMD4A': 879,
 'NUDT4': 880,
 'DERL2': 881,
 'TMEM220': 882,
 'THTPA': 883,
 'PTPN11': 884,
 'EMG1': 885,
 'TUBGCP2': 886,
 'TREX1': 887,
 'DMAC2L': 888,
 'GTF3C2': 889,
 'TMCO1': 890,
 'FOXO4': 891,
 'KBTBD12': 892,
 'GIMAP6': 893,
 'TMEM116': 894,
 'STS': 895,
 'RAD52': 896,
 'BCL2': 897,
 'PARM1': 898,
 'RBM7': 899,
 'FBXW2': 900,
 'TMEM184C': 901,
 'NEDD4L': 902,
 'GNPDA2': 903,
 'SERPINF1': 904,
 'EIF4A1': 905,
 'USP11': 906,
 'CSNK2A2': 907,
 'TNNT3': 908,
 'FAM210A': 909,
 'CALM3': 910,
 'DBNL': 911,
 'PLCD4': 912,
 'ARL8A': 913,
 'SAFB': 914,
 'WDR20': 915,
 'ACY1': 916,
 'TSPAN33': 917,
 'NUPR1': 918,
 'CPT1B': 919,
 'NCAPH2': 920,
 'SYNJ2BP-COX16': 921,
 'ARMC8': 922,
 'TIMM8B': 923,
 'ADA': 924,
 'HGH1': 925,
 'AP4M1': 926,
 'FN1': 927,
 'BAX': 928,
 'ZBTB43': 929,
 'CDC37L1': 930,
 'EIF2B2': 931,
 'ANXA4': 932,
 'MSANTD3': 933,
 'HNRNPD': 934,
 'WIPF3': 935,
 'PFKFB1': 936,
 'CDKL1': 937,
 'PALM': 938,
 'RUBCN': 939,
 'UBA1': 940,
 'LOC102724023': 941,
 'CCDC80': 942,
 'IFI35': 943,
 'HSBP1L1': 944,
 'CCNY': 945,
 'RPL36AP37': 946,
 'TNS1': 947,
 'EIF5A': 948,
 'MTERF3': 949,
 'ANK2': 950,
 'PPP2CA': 951,
 'LUC7L': 952,
 'FAM234A': 953,
 'CDIN1': 954,
 'GYPC': 955,
 'PTPRS': 956,
 'NMT1': 957,
 'RNA5SP298': 958,
 'SLC5A6': 959,
 'SH3RF3': 960,
 'SSH1': 961,
 'LAMP2': 962,
 'NFX1': 963,
 'AQP1': 964,
 'ZFYVE19': 965,
 'UPP1': 966,
 'DECR1': 967,
 'CDKN1A': 968,
 'AP1S1': 969,
 'ANKRD10': 970,
 'H2AJ': 971,
 'LYRM1': 972,
 'SLC38A9': 973,
 'BCKDHA': 974,
 'VPS52': 975,
 'PIGF': 976,
 'OSBPL9': 977,
 'GORASP2': 978,
 'CKLF': 979,
 'AMOTL2': 980,
 'RNA5SP37': 981}

In [ ]:
lab_mirna_targets= ["gap43",
"acvr2a",
"hdac9",
"grp78",
"atf6",
"pgc1-a",
"acvr1b",
"NCAM",
"Hmbox1",
"p2ry6",
"camk2a",
"cadps",
"lch1",
"Il1rapl1",
"Carf",
"Aak1",
"P2ry1",
"Yy1",
"Psme3",
"Bach2",
"Smurf2",
"Atp6v1g1",
"Kcnk10",
"Gpx4",
"Psmg4",
"bach2",
"pten",
"p62",
"Prdx6"]

In [87]:
sections_df

,name,symbols,coef,description,/home/karen/Documents/phd/Resources/Enrichment_dbs/HALLMARK_MYOGENESIS.v2023.2.Hs.gmt
0,Experiment_GSE129643_feature_selection_Symbols...,"[MTERF3, TRAJ39, ABCE1, YWHAH, STYX, ACSL1, DN...","[0.06874883466850641, -0.04945602400059417, 0....",RNAseq ridge_L2_0,"0 HALLMARK_MYOGENESIS Name: Term, dtype: ob..."
1,Experiment_GSE167186_feature_selection_Symbols...,"[MTERF3, ALG9, BTBD3, DNAJC2, ABCE1, TAB2, CAM...","[-0.05401227064808972, 0.04958098566201505, 0....",RNAseq ridge_L2_0,"0 HALLMARK_MYOGENESIS Name: Term, dtype: ob..."
2,Experiment_GSE152558_feature_selection_Symbols...,"[ZNF418, CAPNS1, MYH3, EIF3EP3, RANBP9, TRBV26...","[-0.006172467081098095, 0.01105299609572099, 0...",RNAseq ridge_L2_0,"0 HALLMARK_MYOGENESIS Name: Term, dtype: ob..."
3,RNAseq_All_abundances_adjusted_feature_selecti...,"[MTERF3, SATL1, PATJ, PTMS, CAPZA2, HLA-B, IKB...","[0.1882640921440763, -0.18212858894399941, -1....",RNAseq ridge_L2_0,"0 HALLMARK_MYOGENESIS Name: Term, dtype: ob..."
4,Sex_male_feature_selection_Symbols.csv,"[SATL1, RNA5SP513, RNA5SP509, RNA5SP48, RNA5SP...","[-0.08499529972192735, 0.14201529597074714, 0....",RNAseq ridge_L2_0,"0 HALLMARK_MYOGENESIS Name: Term, dtype: ob..."
5,Status_Sarcopenia_feature_selection_Symbols.csv,"[TCERG1, ABHD1, SATL1, HSPB11, DNAJC2, TAB2, M...","[0.006759327195045021, 0.014183280598438692, 0...",RNAseq ridge_L2_0,"0 HALLMARK_MYOGENESIS Name: Term, dtype: ob..."
6,Experiment_GSE157585_feature_selection_Symbols...,"[EGFL7, TXLNGY, HIGD1A, CCR10, RABEP2, PRRG1, ...","[-0.06730714876104968, 0.05630011864377938, 0....",RNAseq ridge_L2_0,"0 HALLMARK_MYOGENESIS Name: Term, dtype: ob..."
7,Experiment_GSE164471_feature_selection_Symbols...,"[SATL1, MYH3, ANKRD23, ABCE1, MAST4, RNA5SP20,...","[0.24704592192589134, 0.1649144498630691, 0.10...",RNAseq ridge_L2_0,"0 HALLMARK_MYOGENESIS Name: Term, dtype: ob..."
8,Sex_female_feature_selection_Symbols.csv,"[EIF3EP3, RNA5SP509, ABCE1, TBCE, TRAJ39, YWHA...","[-0.15791264946863784, 0.12392276183217599, 0....",RNAseq ridge_L2_0,"0 HALLMARK_MYOGENESIS Name: Term, dtype: ob..."
9,Status_trained_feature_selection_Symbols.csv,"[WNT11, NSL1, TTC23, COLQ, MTERF3, HSPB11, AKR...","[0.00045621832607647907, -0.000460894897275739...",RNAseq ridge_L2_0,"0 HALLMARK_MYOGENESIS Name: Term, dtype: ob..."

In [59]:
sections_df["Tabula_Sapiens"][3]

0                                 Trachea-ciliated Cell
1                             Eye-retinal Ganglion Cell
2                               Thymus-fast Muscle Cell
3                               Spleen-endothelial Cell
4                       Uterus-ciliated Epithelial Cell
5                                      Muscle-mast Cell
6                                         Liver-nk Cell
7     Small Intestine-transit Amplifying Cell Of Sma...
8                   Eye-epithelial Cell Of Lacrimal Sac
9                         Pancreas-pancreatic Beta Cell
10                              Eye-limbal Stromal Cell
11                          Pancreas-pancreatic Pp Cell
12                                    Muscle-macrophage
13                                       Fat-macrophage
14                          Large Intestine-goblet Cell
15         Prostate-luminal Cell Of Prostate Epithelium
16                                     Eye-ciliary Body
17                  Bone Marrow-hematopoietic Stem Cell
18                                       Blood-basophil
19                        Blood-hematopoietic Stem Cell
20                       Bone Marrow-myeloid Progenitor
21                              Lung-pulmonary Ionocyte
22           Prostate-basal Cell Of Prostate Epithelium
23                                     Heart-macrophage
24                                     Trachea-ionocyte
25                            Prostate-endothelial Cell
26                                       Eye-fibroblast
27           Muscle-skeletal Muscle Satellite Stem Cell
28                            Heart-cardiac Muscle Cell
29                    Large Intestine-mature Enterocyte
30                 Small Intestine-intestinal Tuft Cell
31                                     Liver-hepatocyte
32                      Pancreas-pancreatic Ductal Cell
33                 Large Intestine-intestinal Tuft Cell
34                              Thymus-mesothelial Cell
35                       Trachea-connective Tissue Cell
Name: Term, dtype: object

In [51]:
for row in sections_df.iterrows():
    symbols = row[1]["symbols"]
    known_genes = [gene for gene in symbols if gene in lab_mirna_targets]
    print (row[1]["name"], len(known_genes))

Experiment_GSE167186_feature_selection_Symbols.csv 0
Sex_male_feature_selection_Symbols.csv 0
Status_Sarcopenia_feature_selection_Symbols.csv 0
Status_Healthy_feature_selection_Symbols.csv 0
feature_importance_Symbols.csv 0
Experiment_GSE60590_feature_selection_Symbols.csv 0
Experiment_GSE164471_feature_selection_Symbols.csv 0
Sex_female_feature_selection_Symbols.csv 0

In [ ]:
symbols

['WNT11',
 'NSL1',
 'TTC23',
 'COLQ',
 'MTERF3',
 'HSPB11',
 'AKR1B15',
 'LACTB2',
 'CBX7',
 'PATJ',
 'SLC25A34',
 'ACSL1',
 'TXLNGY',
 'RSAD1',
 'C11orf71',
 'DROSHA',
 'EFHD1',
 'HLA-B',
 'IKBKB',
 'MIDN',
 'SAFB',
 'TLCD3B',
 'PI4KB',
 'PRKCH',
 'VPS26B',
 'ND4L',
 'SYNJ2BP-COX16',
 'NUDT16L1',
 'SNAP29',
 'ALDH2',
 'RNA5SP37',
 'GGPS1',
 'ALKBH7',
 'FAM238C',
 'ZNF362',
 'LMBR1',
 'PARD3',
 'LRRC23',
 'U2AF1',
 'CCDC141',
 'PARVB',
 'TBRG4',
 'CYP3A54P',
 'STYXL2',
 'DDHD2',
 'ZNF598',
 'TEX30',
 'UBE2D4',
 'SLC37A4',
 'YWHAB',
 'KCNT1',
 'LRMDA',
 'NFKBIA',
 'BAX',
 'PFKFB1',
 'DECR1',
 'ATP8',
 'GGA1',
 'YIPF7',
 'PLEC',
 'FRMD6',
 'DDX24',
 'FBXO3',
 'USF2',
 'NAT8L',
 'ADCY3',
 'MRPL27',
 'NUDT2',
 'E2F8',
 'C4orf54',
 'TRBJ2-6',
 'TMEM38A',
 'MRPL48',
 'ADAMTSL4',
 'RTN3',
 'UBE2V2',
 'DYRK1B',
 'FLYWCH1',
 'HES4',
 'CSRNP2',
 'MPP7',
 'SPAG9',
 'SSH1',
 'EIF3C',
 'NR1H3',
 'POLR3H',
 'TNIP2',
 'TIMM10',
 'AMPD3',
 'KLHL41',
 'YJU2B',
 'AP4M1',
 'YAF2',
 'LMO7',
 'USP24',
 'HNRNPD',
 'EXOSC9',
 'NR2F2',
 'ZNF784',
 'PSIP1',
 'METTL21EP',
 'PI4KA',
 'MAFA',
 'SZRD1',
 'ADGRE5',
 'ACAD10',
 'THOC5',
 'CETN2',
 'TIPRL',
 'PA2G4',
 'NMNAT1',
 'EIF5A',
 'CSNK2B',
 'POLR2G',
 'TPSB2',
 'STYXL1',
 'LAMTOR3',
 'ENO1',
 'DIP2C',
 'NUDT16',
 'RIDA',
 'RILPL1',
 'COMMD4',
 'MDFIC',
 'LANCL2',
 'PARM1',
 'ROMO1',
 'G6PC3',
 'POLR2F',
 'EEF1AKMT1',
 'SPPL3',
 'CALM3',
 'TMOD3',
 'TMEM94',
 'USP46',
 'RASSF4',
 'SLC29A2',
 'C10orf71',
 'UBE2H',
 'CDK2AP2',
 'PRODH',
 'SMO',
 'TP63',
 'COMTD1',
 'BCAT2',
 'KCNQ5',
 'CTNNBIP1',
 'LOC102724023',
 'ATP2B2',
 'EIF4A2',
 'C1orf198',
 'MSRB2',
 'BIRC6',
 'AMDHD1',
 'MSANTD3',
 'TNS1',
 'CDC37L1',
 'BIN1',
 'ZFYVE19',
 'MCAT',
 'GAS8',
 'ANKRD39',
 'PTDSS1',
 'AHSA1',
 'ZNF91',
 'PSENEN',
 'PHLDB1',
 'MPDZ',
 'EMC1',
 'METTL7A',
 'USP25',
 'TAF4',
 'NXN',
 'TRO',
 'NR2F6',
 'SNU13',
 'RHBDD3',
 'LYPLAL1',
 'BABAM1',
 'LMO1',
 'ECH1',
 'NDUFB10',
 'HAUS4',
 'PIGF',
 'LTBP4',
 'ZIC1',
 'HSPE1-MOB4',
 'SLC38A9',
 'ATP1B4',
 'MTHFD2',
 'SMTN',
 'C3orf18',
 'ZNF429',
 'RFX5',
 'GDE1',
 'EMG1',
 'UBAP1',
 'SMIM27',
 'MEPCE',
 'TSPAN33',
 'BRWD1',
 'RNF44',
 'RETSAT',
 'RASA4',
 'PEBP4',
 'SRSF1',
 'SAFB2',
 'CAMK2A',
 'PPP6R1',
 'MYH14',
 'PRKAG3',
 'CAVIN4',
 'EIF4G3',
 'STX16-NPEPL1',
 'ENY2',
 'LACTB',
 'TAL2',
 'ST3GAL5',
 'HSD11B1L',
 'SFXN5',
 'DPH1',
 'SPTB',
 'EEF1A2',
 'SREBF1',
 'NNMT',
 'AFAP1L1',
 'COPS7B',
 'PLEKHB1',
 'MCM4',
 'UNC13B',
 'PRKRA',
 'ABTB1',
 'FAM118B',
 'FGF13',
 'PPDPFL',
 'UQCRC1',
 'TPRG1',
 'PDGFRL',
 'EIF6',
 'SP100',
 'AOC3',
 'ARFGAP2',
 'IP6K3',
 'DEXI',
 'FADS3',
 'MPPED2',
 'ARL6IP4',
 'PYCR1',
 'SIRT5',
 'EIF1AX',
 'ST3GAL3',
 'KLHL22',
 'RETREG2',
 'SEPTIN4',
 'ANKRD37',
 'CFAP95',
 'TPM2',
 'ZBTB48',
 'RNA5SP298',
 'VPS52',
 'PLCD4',
 'CADM1',
 'RPL36AP37',
 'DHRS7B',
 'MNAT1',
 'NOLC1',
 'MEA1',
 'GIMAP6',
 'TIMM21',
 'CDK2',
 'ZNF273',
 'USP9Y',
 'UBXN4',
 'NRG4',
 'PPP2CA',
 'RAB40C',
 'KCNA7',
 'TLE1',
 'C1orf167',
 'FAM219B',
 'RYR1',
 'CAVIN3',
 'FGFR1OP2',
 'PDLIM7',
 'SSBP1',
 'FABP3',
 'CNNM4',
 'ARHGEF10L',
 'PAQR4',
 'SLC5A6',
 'TMOD4',
 'SRPK3',
 'ST3GAL1',
 'TMUB1',
 'SCHIP1',
 'FBLN2',
 'PIK3R1',
 'LAMP2',
 'TMCO1',
 'GTF3A',
 'DDX3X',
 'PLIN5',
 'RPS21',
 'PHF23',
 'AAGAB',
 'GYPC',
 'CERS1',
 'NR4A1',
 'SCUBE2',
 'CD164',
 'DRAP1',
 'MYADML2',
 'SART3',
 'LAYN',
 'APIP',
 'GTF3C3',
 'GGT7',
 'RAB11FIP3',
 'SLC25A5',
 'ORAI1',
 'PFDN1',
 'MTCO2P22',
 'MAP2K5',
 'PGK1',
 'TIMM8B',
 'UBE2Q2',
 'PDLIM1',
 'CEBPB',
 'WNK1',
 'DDX3Y',
 'FBXW5',
 'GATB',
 'ANAPC15',
 'GANC',
 'CSNK2A1',
 'SH3RF3',
 'AP1S1',
 'CDADC1',
 'EVL',
 'UBA1',
 'PDXK',
 'H2AC6',
 'LITAF',
 'FAH',
 'ORC4',
 'COMMD6',
 'TNNI3',
 'DPP3',
 'ZBTB43',
 'FHIT',
 'RPL26P6',
 'AS3MT',
 'PALM',
 'EXOSC8',
 'PDPR',
 'SLC1A4',
 'E2F4',
 'CASQ2',
 'CACNG6',
 'RCAN2',
 'PHC1',
 'KHNYN',
 'TNFRSF1A',
 'H1-2',
 'HARS2',
 'AUTS2',
 'TSPYL2',
 'DDX27',
 'EXOC6',
 'ECHDC1',
 'HARS1',
 'VPS35L',
 'MMP2',
 'GAR1',
 'NEURL1',
 'ATP6V0B',
 'ADHFE1',
 'NCAPH2',
 'IFI35',
 'CASQ1',
 'DESI1',
 'SPG21',
 'TM6SF1',
 'OTUD1',
 'NXPE3',
 'ZNF330',
 'GOLGA2P7',
 'UPF3A',
 'HPS4',
 'MTND4P24',
 'EBPL',
 'UROS',
 'PAICS',
 'SLC41A3',
 'SIAE',
 'CD74',
 'ING1',
 'TSR3',
 'AURKA',
 'RAB5IF',
 'GOLGA7',
 'PTRHD1',
 'UBXN1',
 'NUBP2',
 'SCN4A',
 'OPTN',
 'PIGL',
 'MED15',
 'SAC3D1',
 'SEC61G',
 'THUMPD3',
 'EIF3B',
 'MTA2',
 'UPP1',
 'ME3',
 'TMEM108',
 'HSPA9',
 'PLA2G4F',
 'CUTC',
 'CDKL1',
 'ADARB1',
 'WDR25',
 'CTNNB1',
 'CYTB',
 'CCDC80',
 'MPC1',
 'BEX3',
 'VASP',
 'OR7E47P',
 'CSNK2A2',
 'ILRUN',
 'NPM3',
 'MPST',
 'C17orf75',
 'EIF3FP3',
 'ITSN1',
 'ALPK3',
 'RUVBL2',
 'RUBCN',
 'EN1',
 'KDM5D',
 'NTF4',
 'PDLIM3',
 'SH3GLB1',
 'ERGIC3',
 'CD36',
 'GORASP2',
 'MAP4',
 'CYSTM1',
 'HEXD',
 'NEIL2',
 'AK6',
 'TREX1',
 'PPP1R14B',
 'SMARCD2',
 'NINJ2',
 'RAP2C',
 'PLIN2',
 'CHRDL2',
 'MYLPF',
 'TLE4',
 'RNA5SP429',
 'ARPC4-TTLL3',
 'POP7',
 'SPIDR',
 'CDIN1',
 'CTTN',
 'PANK1',
 'THTPA',
 'ZBTB16',
 'RPS4Y1',
 'RPP30',
 'DALRD3',
 'UBE2L6',
 'CIBAR1',
 'PDPN',
 'VPS8',
 'ZMYM2',
 'DBNL',
 'COX7A2L',
 'LMOD2',
 'FAM168B',
 'ATF3',
 'FOXO3',
 'MRPL19',
 'NMT1',
 'RASSF3',
 'NPEPL1',
 'ACTN3',
 'ZDHHC14',
 'CACNB1',
 'SPATS2L',
 'FAM217B',
 'P2RX6',
 'GPNMB',
 'AKAP13',
 'CDKN1A',
 'ABLIM2',
 'PUDP',
 'LDHB',
 'SLC40A1',
 'RASA4B',
 'SLAIN2',
 'RIPOR1',
 'RPL36',
 'IL32',
 'ASS1',
 'PTPN11',
 'SLC27A1',
 'PAPSS2',
 'ZNF219',
 'TMEM150A',
 'CACNA2D3',
 'GNB2',
 'ZNF682',
 'HLA-A',
 'CNNM3',
 'OPLAH',
 'MTATP6P1',
 'RNA5SP86',
 'GLCE',
 'WDR20',
 'QRSL1',
 'NBDY',
 'CENPP',
 'H2AC18',
 'MTND2P28',
 'IGSF8',
 'PODN',
 'RAD52',
 'ZEB2',
 'WBP1',
 'ABHD18',
 'PSPC1',
 'PSMC2',
 'FGGY',
 'FOXO4',
 'SLC25A26',
 'CAMSAP1',
 'IGKJ2',
 'MYL6B',
 'KIF9',
 'IFT46',
 'ADAMTS9',
 'RND3',
 'CHD4',
 'NARS1',
 'CSTF2T',
 'HTRA2',
 'TMEM141',
 'YPEL3',
 'MBNL2',
 'PUF60',
 'FAM118A',
 'TBC1D3',
 'FAM210A',
 'OSBPL6',
 'BMPR1A',
 'POLE',
 'VPS72',
 'DMAC2L',
 'AK1',
 'TTTY14',
 'PLIN4',
 'AMOTL2',
 'LMO2',
 'ATP6V0E2',
 'ATG4D',
 'MPDU1',
 'ND3',
 'ST6GALNAC2',
 'RHBDF2',
 'BDH1',
 'FZD7',
 'SETD9',
 'ASB10',
 'ZFP36L1',
 'LGR4',
 'HAUS7',
 'COQ8A',
 'GRB10',
 'GPC1',
 'THRB',
 'FGFRL1',
 'PPM1B',
 'CHKB',
 'CD55',
 'CCDC57',
 'CYB561A3',
 'CBWD2',
 'GSTM3',
 'SPTY2D1OS',
 'CBWD6',
 'PNMT',
 'RPUSD4',
 'RSL1D1',
 'FAM220A',
 'NADK',
 'CCS',
 'MAPK12',
 'TSPAN4',
 'CCNY',
 'OSBPL9',
 'TRBJ2-1',
 'AQP7',
 'POLL',
 'H2BC21',
 'CTSA',
 'CCDC59',
 'KLHL21',
 'IFFO1',
 'CAPN2',
 'VPS41',
 'DAPK3',
 'COX3',
 'WIPF3',
 'DAAM2',
 'AQP1',
 'SESN1',
 'ADPRHL1',
 'ANO6',
 'MTHFSD',
 'NPHP1',
 'ARHGEF2',
 'ARL8A',
 'TMEM222',
 'ACADVL',
 'PHKB',
 'UROD',
 'PSMC4',
 'PRKAG1',
 'TMCC1',
 'DGUOK',
 'PGPEP1L',
 'AAMDC',
 'FNDC5',
 'KBTBD12',
 'PCID2',
 'EGLN3',
 'EIF2B2',
 'HIBCH',
 'CHRAC1',
 'MRPL35',
 'SLC25A25',
 'PEX19',
 'H2AJ',
 'DES',
 'AKR1C2',
 'ZNF652',
 'UGGT1',
 'DPH7',
 'RASL10B',
 'COPS7A',
 'EIF2S1',
 'ASB15',
 'CDK16',
 'CCDC69',
 'KANSL3',
 'UBP1',
 'MDH1',
 'TBKBP1',
 'SLC29A1',
 'UBE2S',
 'MLYCD',
 'EIF4A1',
 'TFEB',
 'DYNC2I1',
 'ATP23',
 'REV1',
 'ALDH1L1',
 'BCL2',
 'HGH1',
 'SNRPA1',
 'TRIM55',
 'UBE2Q1',
 'SLC26A9',
 'SLN',
 'NCBP2',
 'VEZF1',
 'MRPL55',
 'ZFX',
 'RBCK1',
 'ACSM5',
 'PLEKHF1',
 'MRPS14',
 'DHRS4',
 'TBC1D8',
 'TMEM80',
 'CD38',
 'NFIB',
 'ARHGEF6',
 'NRBP1',
 'QSOX1',
 'POLB',
 'IGLC3',
 'HK2',
 'PFKFB2',
 'ALG1L',
 'SBF2',
 'PEX2',
 'NDRG4',
 'LAMB1',
 'TOLLIP',
 'IGFBP3',
 'MRPL13',
 'CAV1',
 'SLC39A3',
 'UBC',
 'FXN',
 'LUC7L',
 'SELENOP',
 'YPEL5',
 'PDCD10',
 'C11orf49',
 'MSH6',
 'SAMD4A',
 'BRD8',
 'TMEM220',
 'HEXIM2',
 'CDC42',
 'NUPR1',
 'RPL7P3',
 'BUB3',
 'NPY6R',
 'KNOP1',
 'FBXW2',
 'C12orf75',
 'KALRN',
 'GATM',
 'TMEM116',
 'IDS',
 'SHISA4',
 'PSMA7',
 'ACOT2',
 'NUDT4',
 'PPP1R27',
 'FN1',
 'SLC44A1',
 'TCF3',
 'CKLF',
 'PSMG4',
 'WDR47',
 'KDM5C',
 'BCL7B',
 'FAM234A',
 'TRIB1',
 'GREB1L',
 'CLPTM1',
 'DERL2',
 'HEXIM1',
 'POLE4',
 'ANK2',
 'BHMT2',
 'LDAF1',
 'ADA',
 'SMTNL2',
 'RNF41',
 'S100A6',
 'TMEM106C',
 'GNPDA2',
 'ZNF358',
 'MAP6D1',
 'WDR12',
 'IGLC2',
 'MOB3C',
 'USP11',
 'PPP1R3B',
 'SP2',
 'FHL2',
 'UPK3A',
 'NANOS1',
 'RBBP7',
 'C16orf86',
 'TMEM9B',
 'DYRK2',
 'PSTPIP2',
 'MED25',
 'NDUFAF6',
 'MASP1',
 'LYRM1',
 'STRBP',
 'DHX9',
 'ANKRD10',
 'BOLA1',
 'CCDC9',
 'ACOT11',
 'GTF3C2',
 'APTX',
 'SEC16A',
 'TMEM273',
 'CD99',
 'GPD1L',
 'TKFC',
 'PPP2R3C',
 'STAG3L4',
 'IPO11',
 'ALPK2',
 'MTFR1L',
 'COQ9',
 'TPD52',
 'SYMPK',
 'BNIP3',
 'VEGFA',
 'THBD',
 'EDF1',
 'SSPN',
 'NDUFA10',
 'SCN1B',
 'TFIP11',
 'ACY1',
 'DTNBP1',
 'SGK1',
 'TMEM161B',
 'EIF1AY',
 'PNPLA6',
 'STS',
 'PTPRS',
 'DNASE1L1',
 'SMARCD1',
 'UTY',
 'ALDH5A1',
 'TMEM43',
 'UCKL1',
 'HMGN1P13',
 'NFE2L1',
 'TUBGCP2',
 'MAP1LC3A',
 'RAP1B',
 'CEBPD',
 'EDC4',
 'CCDC43',
 'CMSS1',
 'PDE4A',
 'PHKA1',
 'PCNT',
 'KDM6A',
 'TMEM185A',
 'UBALD2',
 'BCKDHA',
 'STK25',
 'DEPP1',
 'C11orf1',
 'C12orf73',
 'SMARCA5',
 'LIFR',
 'YIPF4',
 'PRKD2',
 'COX1',
 'HADHB',
 'FGFR4',
 'HAT1',
 'RGS3',
 'SEMA4B',
 'LONRF1',
 'OTUB1',
 'DOP1B',
 'ESRRA',
 'FASTKD1',
 'CPT1B',
 'SLC2A4RG',
 'RIPOR2',
 'NFX1',
 'MED14',
 'ZADH2',
 'AGAP4',
 'ARMC8',
 'PIGS',
 'NEDD4L',
 'PLAAT3',
 'SLC25A29',
 'SLX9',
 'FIBP',
 'ELMO2',
 'RNF187',
 'RYR3',
 'GMPS',
 'C2orf88',
 'NPLOC4',
 'CBY1',
 'OXNAD1',
 'MIX23',
 'CIPC',
 'DCTD',
 'NUP93',
 'ZRSR2',
 'SLC38A7',
 'RBM7',
 'HSBP1L1',
 'ETFBKMT',
 'SULT1A1',
 'COQ5',
 'ANXA4',
 'TSEN15',
 'NAA40',
 'GAPDH',
 'PHYH',
 'MTHFS',
 'GPT',
 'RGS14',
 'MPND',
 'PNKP',
 'ND5',
 'SNRPN',
 'STMP1',
 'PPP2R2A',
 'NFATC1',
 'NENF',
 'DAZAP1',
 'TOMM40',
 'DPH6',
 'PSMD8',
 'ZBTB7B',
 'TRMT2A',
 'DUSP13',
 'PCCB',
 'TMEM120A',
 'TRMT1',
 'TTC38',
 'GPSM2',
 'SLC25A1',
 'COPZ2',
 'CCDC90B',
 'LINC00869',
 'SYNGAP1',
 'CYB5R1',
 'TMEM161A',
 'NAA60',
 'TMEM184C',
 'HYAL1',
 'EOGT',
 'MRM2',
 'C1QA',
 'ST7',
 'ND4',
 'SH2B1',
 'IRAK1',
 'SIKE1',
 'IGKC',
 'PPP2R5D',
 'TNNT3',
 'ENO3',
 'GLOD4',
 'RNF149',
 'HP1BP3',
 'SMTNL1',
 'SGCG',
 'CHCHD3',
 'CTSH',
 'FBXO21',
 'TPD52L1',
 'NDFIP2',
 'TCEA1',
 'KIAA1671',
 'SLC25A23',
 'CGRRF1',
 'ATP2A1',
 'HOXA4',
 'XRCC5',
 'ALDH6A1',
 'KHSRP',
 'LMNB2',
 'INMT',
 'SNTA1',
 'ND1',
 'EML1',
 'HPN',
 'HDAC11',
 'RNF167',
 'INTS11',
 'CDK18',
 'PER3',
 'PCGF3',
 'RTL8A',
 'EPN2',
 'SHISA2',
 'SERPINF1',
 'AKTIP',
 'SMIM7',
 'NDUFAF4',
 'PPP1R16A']

In [57]:
repeated_terms = []
for row in sections_df.iterrows():
    terms = row[1][database]
    repeated_terms.append(set(terms))
repeated_terms

[{'Blood-erythrocyte',
  'Bone Marrow-erythrocyte',
  'Bone Marrow-nampt Neutrophil',
  'Bone Marrow-neutrophil',
  'Eye-erythroid Lineage Cell',
  'Eye-macrophage',
  'Fat-macrophage',
  'Large Intestine-mature Enterocyte',
  'Large Intestine-monocyte',
  'Lung-capillary Aerocyte',
  'Lung-neutrophil',
  'Lymph Node-macrophage',
  'Prostate-basal Cell Of Prostate Epithelium',
  'Prostate-erythroid Progenitor',
  'Salivary Gland-monocyte',
  'Small Intestine-monocyte',
  'Thymus-erythrocyte',
  'Tongue-pericyte Cell',
  'Trachea-neutrophil',
  'Vasculature-macrophage'},
 {'Fat-smooth Muscle Cell',
  'Salivary Gland-adventitial Cell',
  'Salivary Gland-monocyte',
  'Salivary Gland-pericyte Cell',
  'Thymus-vascular Associated Smooth Muscle Cell',
  'Vasculature-smooth Muscle Cell'},
 {'Thymus-erythrocyte'},
 {'Blood-basophil',
  'Blood-hematopoietic Stem Cell',
  'Bone Marrow-hematopoietic Stem Cell',
  'Bone Marrow-myeloid Progenitor',
  'Eye-ciliary Body',
  'Eye-epithelial Cell Of Lacrimal Sac',
  'Eye-fibroblast',
  'Eye-limbal Stromal Cell',
  'Eye-retinal Ganglion Cell',
  'Fat-macrophage',
  'Heart-cardiac Muscle Cell',
  'Heart-macrophage',
  'Large Intestine-goblet Cell',
  'Large Intestine-intestinal Tuft Cell',
  'Large Intestine-mature Enterocyte',
  'Liver-hepatocyte',
  'Liver-nk Cell',
  'Lung-pulmonary Ionocyte',
  'Muscle-macrophage',
  'Muscle-mast Cell',
  'Muscle-skeletal Muscle Satellite Stem Cell',
  'Pancreas-pancreatic Beta Cell',
  'Pancreas-pancreatic Ductal Cell',
  'Pancreas-pancreatic Pp Cell',
  'Prostate-basal Cell Of Prostate Epithelium',
  'Prostate-endothelial Cell',
  'Prostate-luminal Cell Of Prostate Epithelium',
  'Small Intestine-intestinal Tuft Cell',
  'Small Intestine-transit Amplifying Cell Of Small Intestine',
  'Spleen-endothelial Cell',
  'Thymus-fast Muscle Cell',
  'Thymus-mesothelial Cell',
  'Trachea-ciliated Cell',
  'Trachea-connective Tissue Cell',
  'Trachea-ionocyte',
  'Uterus-ciliated Epithelial Cell'},
 {'Bladder-b Cell',
  'Bladder-bladder Urothelial Cell',
  'Bladder-capillary Endothelial Cell',
  'Bladder-endothelial Cell Of Lymphatic Vessel',
  'Bladder-fibroblast',
  'Bladder-mast Cell',
  'Bladder-myofibroblast Cell',
  'Bladder-pericyte Cell',
  'Bladder-plasma Cell',
  'Bladder-plasmacytoid Dendritic Cell',
  'Bladder-smooth Muscle Cell',
  'Bladder-t Cell',
  'Bladder-vein Endothelial Cell',
  'Blood-basophil',
  'Blood-cd141-positive Myeloid Dendritic Cell',
  'Blood-cd4-positive, Alpha-Beta Memory T Cell',
  'Blood-cd4-positive, Alpha-Beta T Cell',
  'Blood-cd8-positive, Alpha-Beta Cytokine Secreting Effector T Cell',
  'Blood-cd8-positive, Alpha-Beta T Cell',
  'Blood-erythrocyte',
  'Blood-granulocyte',
  'Blood-hematopoietic Stem Cell',
  'Blood-macrophage',
  'Blood-memory B Cell',
  'Blood-monocyte',
  'Blood-myeloid Progenitor',
  'Blood-naive B Cell',
  'Blood-naive Thymus-Derived Cd4-Positive, Alpha-Beta T Cell',
  'Blood-nk Cell',
  'Blood-non-classical Monocyte',
  'Blood-plasma Cell',
  'Blood-plasmablast',
  'Blood-plasmacytoid Dendritic Cell',
  'Blood-platelet',
  'Blood-t Cell',
  'Blood-type I Nk T Cell',
  'Bone Marrow-cd24 Neutrophil',
  'Bone Marrow-cd4-positive, Alpha-Beta T Cell',
  'Bone Marrow-cd8-positive, Alpha-Beta T Cell',
  'Bone Marrow-erythrocyte',
  'Bone Marrow-erythroid Progenitor',
  'Bone Marrow-granulocyte',
  'Bone Marrow-hematopoietic Stem Cell',
  'Bone Marrow-macrophage',
  'Bone Marrow-memory B Cell',
  'Bone Marrow-monocyte',
  'Bone Marrow-myeloid Progenitor',
  'Bone Marrow-naive B Cell',
  'Bone Marrow-nampt Neutrophil',
  'Bone Marrow-nk Cell',
  'Eye-adipocyte',
  'Eye-b Cell',
  'Eye-cd4-positive, Alpha-Beta T Cell',
  'Eye-cd8-positive, Alpha-Beta T Cell',
  'Eye-ciliary Body',
  'Eye-corneal Keratocyte',
  'Eye-dendritic Cell',
  'Eye-endothelial Cell',
  'Eye-erythroid Lineage Cell',
  'Eye-eye Photoreceptor Cell',
  'Eye-lacrimal Gland Functional Unit Cell',
  'Eye-limbal Stromal Cell',
  'Eye-mast Cell',
  'Eye-melanocyte',
  'Eye-monocyte',
  'Eye-muller Cell',
  'Eye-ocular Surface Cell',
  'Eye-plasma Cell',
  'Eye-retina Horizontal Cell',
  'Eye-retinal Blood Vessel Endothelial Cell',
  'Eye-retinal Ganglion Cell',
  'Eye-t Cell',
  'Fat-fibroblast',
  'Fat-leucocyte',
  'Fat-mast Cell',
  'Fat-mesenchymal Stem Cell',
  'Fat-myofibroblast Cell',
  'Fat-nk Cell',
  'Fat-plasma Cell',
  'Fat-smooth Muscle Cell',
  'Fat-t Cell',
  'Heart-cardiac Endothelial Cell',
  'Heart-cardiac Muscle Cell',
  'Heart-fibroblast Of Cardiac Tissue',
  'Heart-hepatocyte',
  'Heart-macrophage',
  'Heart-smooth Muscle Cell',
  'Kidney-b Cell',
  'Kidney-cd4-positive Helper T Cell',
  'Kidney-cd8-positive, Alpha-Beta T Cell',
  'Kidney-kidney Epithelial Cell',
  'Kidney-macrophage',
  'Large Intestine-b Cell',
  'Large Intestine-cd4-positive, Alpha-Beta T Cell',
  'Large Intestine-cd8-positive, Alpha-Beta T Cell',
  'Large Intestine-enterocyte Of Epithelium Of Large Intestine',
  'Large Intestine-gut Endothelial Cell',
  'Large Intestine-immature Enterocyte',
  'Large Intestine-intestinal Crypt Stem Cell',
  'Large Intestine-mast Cell',
  'Large Intestine-monocyte',
  'Large Intestine-plasma Cell',
  'Large Intestine-transit Amplifying Cell Of Large Intestine',
  'Liver-erythrocyte',
  'Liver-fibroblast',
  'Liver-liver Dendritic Cell',
  'Liver-macrophage',
  'Liver-monocyte',
  'Liver-neutrophil',
  'Liver-nk Cell',
  'Liver-plasma Cell',
  'Liver-t Cell',
  'Lung-adventitial Cell',
  'Lung-alveolar Fibroblast',
  'Lung-b Cell',
  'Lung-basal Cell',
  'Lung-basophil',
  'Lung-bronchial Smooth Muscle Cell',
  'Lung-bronchial Vessel Endothelial Cell',
  'Lung-capillary Endothelial Cell',
  'Lung-cd4-positive Alpha-Beta T Cell',
  'Lung-cd4-positive, Alpha-Beta T Cell',
  'Lung-cd8-positive Alpha-Beta T Cell',
  'Lung-cd8-positive, Alpha-Beta T Cell',
  'Lung-classical Monocyte',
  'Lung-club Cell',
  'Lung-dendritic Cell',
  'Lung-endothelial Cell Of Lymphatic Vessel',
  'Lung-intermediate Monocyte',
  'Lung-lung Microvascular Endothelial Cell',
  'Lung-mesothelial Cell',
  'Lung-myofibroblast Cell',
  'Lung-plasma Cell',
  'Lung-plasmacytoid Dendritic Cell',
  'Lung-respiratory Goblet Cell',
  'Lung-respiratory Mucous Cell',
  'Lung-smooth Muscle Cell',
  'Lung-type Ii Pneumocyte',
  'Lung-vascular Associated Smooth Muscle Cell',
  'Lymph Node-b Cell',
  'Lymph Node-cd141-positive Myeloid Dendritic Cell',
  'Lymph Node-cd1c-positive Myeloid Dendritic Cell',
  'Lymph Node-cd4-positive Alpha-Beta T Cell',
  'Lymph Node-cd4-positive, Alpha-Beta Memory T Cell',
  'Lymph Node-cd8-positive Alpha-Beta T Cell',
  'Lymph Node-cd8-positive, Alpha-Beta Memory T Cell',
  'Lymph Node-classical Monocyte',
  'Lymph Node-endothelial Cell',
  'Lymph Node-erythrocyte',
  'Lymph Node-hematopoietic Stem Cell',
  'Lymph Node-innate Lymphoid Cell',
  'Lymph Node-intermediate Monocyte',
  'Lymph Node-mast Cell',
  'Lymph Node-mature Conventional Dendritic Cell',
  'Lymph Node-mature Nk T Cell',
  'Lymph Node-memory B Cell',
  'Lymph Node-naive B Cell',
  'Lymph Node-naive Thymus-Derived Cd4-Positive, Alpha-Beta T Cell',
  'Lymph Node-neutrophil',
  'Lymph Node-nk Cell',
  'Lymph Node-non-classical Monocyte',
  'Lymph Node-plasma Cell',
  'Lymph Node-plasmacytoid Dendritic Cell',
  'Lymph Node-regulatory T Cell',
  'Lymph Node-stromal Cell',
  'Lymph Node-t Cell',
  'Lymph Node-type I Nk T Cell',
  'Mammary-b Cell',
  'Mammary-basal Cell',
  'Mammary-endothelial Cell Of Lymphatic Vessel',
  'Mammary-fibroblast Of Breast',
  'Mammary-pericyte Cell',
  'Mammary-t Cell',
  'Mammary-vascular Associated Smooth Muscle Cell',
  'Mammary-vein Endothelial Cell',
  'Muscle-cd4-positive, Alpha-Beta T Cell',
  'Muscle-cd8-positive, Alpha-Beta T Cell',
  'Muscle-endothelial Cell Of Artery',
  'Muscle-endothelial Cell Of Lymphatic Vessel',
  'Muscle-endothelial Cell Of Vascular Tree',
  'Muscle-erythrocyte',
  'Muscle-fast Muscle Cell',
  'Muscle-mast Cell',
  'Muscle-mature Nk T Cell',
  'Muscle-mesenchymal Stem Cell',
  'Muscle-mesothelial Cell',
  'Muscle-skeletal Muscle Satellite Stem Cell',
  'Muscle-slow Muscle Cell',
  'Muscle-smooth Muscle Cell',
  'Muscle-t Cell',
  'Muscle-tendon Cell',
  'Pancreas-b Cell',
  'Pancreas-fibroblast',
  'Pancreas-mast Cell',
  'Pancreas-nk Cell',
  'Pancreas-pancreatic Beta Cell',
  'Pancreas-pancreatic Delta Cell',
  'Pancreas-pancreatic Pp Cell',
  'Pancreas-pancreatic Stellate Cell',
  'Pancreas-plasma Cell',
  'Pancreas-t Cell',
  'Prostate-basal Cell Of Prostate Epithelium',
  'Prostate-cd8-positive, Alpha-Beta T Cell',
  'Prostate-cd8b-positive Nk T Cell',
  'Prostate-club Cell Of Prostate Epithelium',
  'Prostate-endothelial Cell',
  'Prostate-epithelial Cell',
  'Prostate-erythroid Progenitor',
  'Prostate-fibroblast',
  'Prostate-hillock Cell Of Prostate Epithelium',
  'Prostate-luminal Cell Of Prostate Epithelium',
  'Prostate-macrophage',
  'Prostate-mast Cell',
  'Prostate-myeloid Cell',
  'Prostate-neutrophil',
  'Prostate-nkt Cell',
  'Prostate-smooth Muscle Cell',
  'Prostate-sperm',
  'Prostate-t Cell',
  'Salivary Gland-adventitial Cell',
  'Salivary Gland-b Cell',
  'Salivary Gland-basal Cell',
  'Salivary Gland-cd4-positive Helper T Cell',
  'Salivary Gland-cd8-positive, Alpha-Beta T Cell',
  'Salivary Gland-endothelial Cell Of Lymphatic Vessel',
  'Salivary Gland-fibroblast',
  'Salivary Gland-macrophage',
  'Salivary Gland-memory B Cell',
  'Salivary Gland-myoepithelial Cell',
  'Salivary Gland-naive B Cell',
  'Salivary Gland-neutrophil',
  'Salivary Gland-nk Cell',
  'Salivary Gland-pericyte Cell',
  'Salivary Gland-plasma Cell',
  'Salivary Gland-t Cell',
  'Skin-cd141-positive Myeloid Dendritic Cell',
  'Skin-cd1c-positive Myeloid Dendritic Cell',
  'Skin-cd4-positive Helper T Cell',
  'Skin-cd4-positive, Alpha-Beta Memory T Cell',
  'Skin-cd8-positive, Alpha-Beta Cytotoxic T Cell',
  'Skin-cd8-positive, Alpha-Beta Memory T Cell',
  'Skin-cell Of Skeletal Muscle',
  'Skin-endothelial Cell',
  'Skin-epithelial Cell',
  'Skin-langerhans Cell',
  'Skin-macrophage',
  'Skin-mast Cell',
  'Skin-melanocyte',
  'Skin-memory B Cell',
  'Skin-muscle Cell',
  'Skin-naive B Cell',
  'Skin-naive Thymus-Derived Cd4-Positive, Alpha-Beta T Cell',
  'Skin-naive Thymus-Derived Cd8-Positive, Alpha-Beta T Cell',
  'Skin-nk Cell',
  'Skin-nkt Cell',
  'Skin-plasma Cell',
  'Skin-regulatory T Cell',
  'Skin-smooth Muscle Cell',
  'Skin-stromal Cell',
  'Skin-t Cell',
  'Small Intestine-b Cell',
  'Small Intestine-cd4-positive, Alpha-Beta T Cell',
  'Small Intestine-cd8-positive, Alpha-Beta T Cell',
  'Small Intestine-enterocyte Of Epithelium Of Small Intestine',
  'Small Intestine-fibroblast',
  'Small Intestine-gut Endothelial Cell',
  'Small Intestine-intestinal Crypt Stem Cell',
  'Small Intestine-mast Cell',
  'Small Intestine-monocyte',
  'Small Intestine-paneth Cell Of Epithelium Of Small Intestine',
  'Small Intestine-plasma Cell',
  'Small Intestine-transit Amplifying Cell Of Small Intestine',
  'Spleen-cd141-positive Myeloid Dendritic Cell',
  'Spleen-cd4-positive, Alpha-Beta Memory T Cell',
  'Spleen-cd8-positive, Alpha-Beta Memory T Cell',
  'Spleen-cd8-positive, Alpha-Beta T Cell',
  'Spleen-classical Monocyte',
  'Spleen-erythrocyte',
  'Spleen-hematopoietic Stem Cell',
  'Spleen-innate Lymphoid Cell',
  'Spleen-intermediate Monocyte',
  'Spleen-mature Nk T Cell',
  'Spleen-memory B Cell',
  'Spleen-naive B Cell',
  'Spleen-naive Thymus-Derived Cd4-Positive, Alpha-Beta T Cell',
  'Spleen-naive Thymus-Derived Cd8-Positive, Alpha-Beta T Cell',
  'Spleen-nk Cell',
  'Spleen-plasma Cell',
  'Spleen-plasmacytoid Dendritic Cell',
  'Spleen-platelet',
  'Spleen-regulatory T Cell',
  'Spleen-type I Nk T Cell',
  'Thymus-b Cell',
  'Thymus-cd4-positive Helper T Cell',
  'Thymus-cd8-positive, Alpha-Beta Cytotoxic T Cell',
  'Thymus-cd8-positive, Alpha-Beta T Cell',
  'Thymus-dendritic Cell',
  'Thymus-dn1 Thymic Pro-T Cell',
  'Thymus-dn3 Thymocyte',
  'Thymus-dn4 Thymocyte',
  'Thymus-endothelial Cell Of Lymphatic Vessel',
  'Thymus-fast Muscle Cell',
  'Thymus-fibroblast',
  'Thymus-immature Natural Killer Cell',
  'Thymus-innate Lymphoid Cell',
  'Thymus-mast Cell',
  'Thymus-mature Nk T Cell',
  'Thymus-medullary Thymic Epithelial Cell',
  'Thymus-memory B Cell',
  'Thymus-mesothelial Cell',
  'Thymus-myeloid Dendritic Cell',
  'Thymus-naive B Cell',
  'Thymus-naive Regulatory T Cell',
  'Thymus-nk Cell',
  'Thymus-plasma Cell',
  'Thymus-t Follicular Helper Cell',
  'Thymus-thymocyte',
  'Thymus-vascular Associated Smooth Muscle Cell',
  'Thymus-vein Endothelial Cell',
  'Tongue-capillary Endothelial Cell',
  'Tongue-endothelial Cell Of Artery',
  'Tongue-endothelial Cell Of Lymphatic Vessel',
  'Tongue-epithelial Cell',
  'Tongue-fibroblast',
  'Tongue-immune Cell',
  'Tongue-pericyte Cell',
  'Tongue-schwann Cell',
  'Tongue-tongue Muscle Cell',
  'Tongue-vein Endothelial Cell',
  'Trachea-b Cell',
  'Trachea-basal Cell',
  'Trachea-cd4-positive, Alpha-Beta T Cell',
  'Trachea-cd8-positive, Alpha-Beta T Cell',
  'Trachea-connective Tissue Cell',
  'Trachea-double-positive, Alpha-Beta Thymocyte',
  'Trachea-endothelial Cell',
  'Trachea-fibroblast',
  'Trachea-mast Cell',
  'Trachea-smooth Muscle Cell',
  'Trachea-t Cell',
  'Uterus-b Cell',
  'Uterus-epithelial Cell',
  'Uterus-fibroblast',
  'Uterus-myometrial Cell',
  'Uterus-pericyte Cell',
  'Uterus-t Cell',
  'Uterus-vascular Associated Smooth Muscle Cell',
  'Vasculature-b Cell',
  'Vasculature-endothelial Cell',
  'Vasculature-epithelial Cell',
  'Vasculature-erythrocyte',
  'Vasculature-fibroblast',
  'Vasculature-lymphatic Endothelial Cell',
  'Vasculature-mast Cell',
  'Vasculature-nk Cell',
  'Vasculature-pericyte Cell',
  'Vasculature-plasma Cell',
  'Vasculature-smooth Muscle Cell',
  'Vasculature-t Cell'},
 {'Bone Marrow-erythrocyte', 'Muscle-erythrocyte', 'Thymus-erythrocyte'},
 {'Bladder-pericyte Cell',
  'Bladder-smooth Muscle Cell',
  'Blood-erythrocyte',
  'Eye-endothelial Cell',
  'Fat-myofibroblast Cell',
  'Fat-smooth Muscle Cell',
  'Large Intestine-mature Enterocyte',
  'Lung-bronchial Smooth Muscle Cell',
  'Lung-vascular Associated Smooth Muscle Cell',
  'Muscle-smooth Muscle Cell',
  'Prostate-smooth Muscle Cell',
  'Salivary Gland-myoepithelial Cell',
  'Salivary Gland-pericyte Cell',
  'Skin-cell Of Skeletal Muscle',
  'Thymus-erythrocyte',
  'Tongue-pericyte Cell',
  'Uterus-myometrial Cell',
  'Uterus-vascular Associated Smooth Muscle Cell',
  'Vasculature-pericyte Cell',
  'Vasculature-smooth Muscle Cell'},
 {'Lung-capillary Aerocyte',
  'Lung-capillary Endothelial Cell',
  'Muscle-fast Muscle Cell',
  'Pancreas-fibroblast',
  'Prostate-endothelial Cell',
  'Prostate-sperm',
  'Salivary Gland-endothelial Cell',
  'Thymus-fast Muscle Cell'}]

In [58]:
# count repetiton of terms
from collections import Counter
count_terms = Counter()
for terms in repeated_terms:
    count_terms.update(terms)
count_terms

Counter({'Thymus-erythrocyte': 4,
         'Prostate-basal Cell Of Prostate Epithelium': 3,
         'Tongue-pericyte Cell': 3,
         'Large Intestine-mature Enterocyte': 3,
         'Blood-erythrocyte': 3,
         'Bone Marrow-erythrocyte': 3,
         'Fat-smooth Muscle Cell': 3,
         'Vasculature-smooth Muscle Cell': 3,
         'Salivary Gland-pericyte Cell': 3,
         'Prostate-endothelial Cell': 3,
         'Thymus-fast Muscle Cell': 3,
         'Fat-macrophage': 2,
         'Small Intestine-monocyte': 2,
         'Bone Marrow-nampt Neutrophil': 2,
         'Eye-erythroid Lineage Cell': 2,
         'Lung-capillary Aerocyte': 2,
         'Salivary Gland-monocyte': 2,
         'Large Intestine-monocyte': 2,
         'Prostate-erythroid Progenitor': 2,
         'Thymus-vascular Associated Smooth Muscle Cell': 2,
         'Salivary Gland-adventitial Cell': 2,
         'Eye-ciliary Body': 2,
         'Liver-nk Cell': 2,
         'Small Intestine-transit Amplifying Cell Of Small Intestine': 2,
         'Bone Marrow-myeloid Progenitor': 2,
         'Muscle-mast Cell': 2,
         'Pancreas-pancreatic Beta Cell': 2,
         'Bone Marrow-hematopoietic Stem Cell': 2,
         'Blood-basophil': 2,
         'Prostate-luminal Cell Of Prostate Epithelium': 2,
         'Thymus-mesothelial Cell': 2,
         'Eye-limbal Stromal Cell': 2,
         'Muscle-skeletal Muscle Satellite Stem Cell': 2,
         'Heart-macrophage': 2,
         'Eye-retinal Ganglion Cell': 2,
         'Heart-cardiac Muscle Cell': 2,
         'Blood-hematopoietic Stem Cell': 2,
         'Trachea-connective Tissue Cell': 2,
         'Pancreas-pancreatic Pp Cell': 2,
         'Muscle-fast Muscle Cell': 2,
         'Bladder-smooth Muscle Cell': 2,
         'Lung-vascular Associated Smooth Muscle Cell': 2,
         'Skin-cell Of Skeletal Muscle': 2,
         'Uterus-myometrial Cell': 2,
         'Lung-bronchial Smooth Muscle Cell': 2,
         'Vasculature-pericyte Cell': 2,
         'Prostate-sperm': 2,
         'Prostate-smooth Muscle Cell': 2,
         'Pancreas-fibroblast': 2,
         'Salivary Gland-myoepithelial Cell': 2,
         'Muscle-smooth Muscle Cell': 2,
         'Uterus-vascular Associated Smooth Muscle Cell': 2,
         'Eye-endothelial Cell': 2,
         'Bladder-pericyte Cell': 2,
         'Muscle-erythrocyte': 2,
         'Lung-capillary Endothelial Cell': 2,
         'Fat-myofibroblast Cell': 2,
         'Eye-macrophage': 1,
         'Lung-neutrophil': 1,
         'Vasculature-macrophage': 1,
         'Bone Marrow-neutrophil': 1,
         'Lymph Node-macrophage': 1,
         'Trachea-neutrophil': 1,
         'Lung-pulmonary Ionocyte': 1,
         'Muscle-macrophage': 1,
         'Trachea-ionocyte': 1,
         'Small Intestine-intestinal Tuft Cell': 1,
         'Liver-hepatocyte': 1,
         'Spleen-endothelial Cell': 1,
         'Large Intestine-goblet Cell': 1,
         'Uterus-ciliated Epithelial Cell': 1,
         'Large Intestine-intestinal Tuft Cell': 1,
         'Eye-epithelial Cell Of Lacrimal Sac': 1,
         'Trachea-ciliated Cell': 1,
         'Pancreas-pancreatic Ductal Cell': 1,
         'Eye-fibroblast': 1,
         'Kidney-cd4-positive Helper T Cell': 1,
         'Lymph Node-cd8-positive Alpha-Beta T Cell': 1,
         'Vasculature-fibroblast': 1,
         'Thymus-cd8-positive, Alpha-Beta Cytotoxic T Cell': 1,
         'Skin-memory B Cell': 1,
         'Skin-stromal Cell': 1,
         'Skin-cd4-positive Helper T Cell': 1,
         'Eye-b Cell': 1,
         'Lymph Node-cd141-positive Myeloid Dendritic Cell': 1,
         'Spleen-memory B Cell': 1,
         'Thymus-cd8-positive, Alpha-Beta T Cell': 1,
         'Small Intestine-intestinal Crypt Stem Cell': 1,
         'Bone Marrow-granulocyte': 1,
         'Thymus-vein Endothelial Cell': 1,
         'Lung-type Ii Pneumocyte': 1,
         'Salivary Gland-basal Cell': 1,
         'Blood-nk Cell': 1,
         'Mammary-basal Cell': 1,
         'Thymus-b Cell': 1,
         'Spleen-naive Thymus-Derived Cd4-Positive, Alpha-Beta T Cell': 1,
         'Lymph Node-innate Lymphoid Cell': 1,
         'Thymus-memory B Cell': 1,
         'Salivary Gland-fibroblast': 1,
         'Tongue-epithelial Cell': 1,
         'Thymus-dn3 Thymocyte': 1,
         'Kidney-macrophage': 1,
         'Mammary-vascular Associated Smooth Muscle Cell': 1,
         'Uterus-b Cell': 1,
         'Prostate-myeloid Cell': 1,
         'Vasculature-erythrocyte': 1,
         'Eye-t Cell': 1,
         'Muscle-tendon Cell': 1,
         'Blood-myeloid Progenitor': 1,
         'Thymus-myeloid Dendritic Cell': 1,
         'Trachea-t Cell': 1,
         'Eye-cd4-positive, Alpha-Beta T Cell': 1,
         'Spleen-classical Monocyte': 1,
         'Fat-leucocyte': 1,
         'Lung-b Cell': 1,
         'Skin-naive Thymus-Derived Cd8-Positive, Alpha-Beta T Cell': 1,
         'Lung-club Cell': 1,
         'Salivary Gland-cd4-positive Helper T Cell': 1,
         'Lung-plasmacytoid Dendritic Cell': 1,
         'Trachea-cd4-positive, Alpha-Beta T Cell': 1,
         'Eye-retinal Blood Vessel Endothelial Cell': 1,
         'Bone Marrow-macrophage': 1,
         'Skin-t Cell': 1,
         'Eye-monocyte': 1,
         'Bone Marrow-cd24 Neutrophil': 1,
         'Kidney-kidney Epithelial Cell': 1,
         'Spleen-cd141-positive Myeloid Dendritic Cell': 1,
         'Lymph Node-plasmacytoid Dendritic Cell': 1,
         'Thymus-t Follicular Helper Cell': 1,
         'Thymus-immature Natural Killer Cell': 1,
         'Heart-fibroblast Of Cardiac Tissue': 1,
         'Skin-muscle Cell': 1,
         'Large Intestine-intestinal Crypt Stem Cell': 1,
         'Skin-epithelial Cell': 1,
         'Spleen-naive Thymus-Derived Cd8-Positive, Alpha-Beta T Cell': 1,
         'Liver-neutrophil': 1,
         'Large Intestine-gut Endothelial Cell': 1,
         'Skin-cd1c-positive Myeloid Dendritic Cell': 1,
         'Spleen-type I Nk T Cell': 1,
         'Muscle-slow Muscle Cell': 1,
         'Bone Marrow-memory B Cell': 1,
         'Vasculature-epithelial Cell': 1,
         'Heart-cardiac Endothelial Cell': 1,
         'Muscle-endothelial Cell Of Vascular Tree': 1,
         'Small Intestine-b Cell': 1,
         'Vasculature-lymphatic Endothelial Cell': 1,
         'Thymus-nk Cell': 1,
         'Lymph Node-type I Nk T Cell': 1,
         'Pancreas-pancreatic Delta Cell': 1,
         'Tongue-immune Cell': 1,
         'Muscle-endothelial Cell Of Artery': 1,
         'Lung-endothelial Cell Of Lymphatic Vessel': 1,
         'Large Intestine-enterocyte Of Epithelium Of Large Intestine': 1,
         'Vasculature-endothelial Cell': 1,
         'Kidney-cd8-positive, Alpha-Beta T Cell': 1,
         'Skin-endothelial Cell': 1,
         'Prostate-nkt Cell': 1,
         'Salivary Gland-b Cell': 1,
         'Blood-cd141-positive Myeloid Dendritic Cell': 1,
         'Small Intestine-fibroblast': 1,
         'Eye-retina Horizontal Cell': 1,
         'Liver-erythrocyte': 1,
         'Liver-macrophage': 1,
         'Liver-t Cell': 1,
         'Mammary-t Cell': 1,
         'Lymph Node-naive B Cell': 1,
         'Bladder-bladder Urothelial Cell': 1,
         'Salivary Gland-memory B Cell': 1,
         'Prostate-epithelial Cell': 1,
         'Lung-adventitial Cell': 1,
         'Thymus-cd4-positive Helper T Cell': 1,
         'Thymus-naive B Cell': 1,
         'Blood-cd4-positive, Alpha-Beta T Cell': 1,
         'Skin-cd8-positive, Alpha-Beta Memory T Cell': 1,
         'Thymus-dn1 Thymic Pro-T Cell': 1,
         'Large Intestine-plasma Cell': 1,
         'Salivary Gland-naive B Cell': 1,
         'Fat-t Cell': 1,
         'Tongue-endothelial Cell Of Artery': 1,
         'Thymus-mast Cell': 1,
         'Lung-basophil': 1,
         'Fat-fibroblast': 1,
         'Lymph Node-nk Cell': 1,
         'Spleen-innate Lymphoid Cell': 1,
         'Spleen-regulatory T Cell': 1,
         'Pancreas-nk Cell': 1,
         'Lymph Node-cd4-positive, Alpha-Beta Memory T Cell': 1,
         'Trachea-double-positive, Alpha-Beta Thymocyte': 1,
         'Lung-respiratory Goblet Cell': 1,
         'Heart-smooth Muscle Cell': 1,
         'Lung-myofibroblast Cell': 1,
         'Trachea-b Cell': 1,
         'Spleen-platelet': 1,
         'Lymph Node-stromal Cell': 1,
         'Thymus-dn4 Thymocyte': 1,
         'Salivary Gland-plasma Cell': 1,
         'Trachea-basal Cell': 1,
         'Pancreas-plasma Cell': 1,
         'Lymph Node-classical Monocyte': 1,
         'Lymph Node-naive Thymus-Derived Cd4-Positive, Alpha-Beta T Cell': 1,
         'Lymph Node-hematopoietic Stem Cell': 1,
         'Lymph Node-regulatory T Cell': 1,
         'Bladder-fibroblast': 1,
         'Salivary Gland-nk Cell': 1,
         'Salivary Gland-endothelial Cell Of Lymphatic Vessel': 1,
         'Bladder-t Cell': 1,
         'Vasculature-t Cell': 1,
         'Trachea-endothelial Cell': 1,
         'Skin-cd8-positive, Alpha-Beta Cytotoxic T Cell': 1,
         'Blood-plasmacytoid Dendritic Cell': 1,
         'Spleen-cd8-positive, Alpha-Beta T Cell': 1,
         'Lung-basal Cell': 1,
         'Mammary-b Cell': 1,
         'Lung-cd4-positive, Alpha-Beta T Cell': 1,
         'Small Intestine-cd8-positive, Alpha-Beta T Cell': 1,
         'Lymph Node-intermediate Monocyte': 1,
         'Skin-nkt Cell': 1,
         'Bladder-mast Cell': 1,
         'Mammary-fibroblast Of Breast': 1,
         'Vasculature-nk Cell': 1,
         'Blood-granulocyte': 1,
         'Muscle-mesenchymal Stem Cell': 1,
         'Lymph Node-mast Cell': 1,
         'Prostate-cd8b-positive Nk T Cell': 1,
         'Lymph Node-neutrophil': 1,
         'Lung-cd4-positive Alpha-Beta T Cell': 1,
         'Pancreas-t Cell': 1,
         'Skin-naive Thymus-Derived Cd4-Positive, Alpha-Beta T Cell': 1,
         'Skin-cd4-positive, Alpha-Beta Memory T Cell': 1,
         'Bladder-myofibroblast Cell': 1,
         'Salivary Gland-macrophage': 1,
         'Lymph Node-endothelial Cell': 1,
         'Prostate-club Cell Of Prostate Epithelium': 1,
         'Lung-intermediate Monocyte': 1,
         'Spleen-hematopoietic Stem Cell': 1,
         'Large Intestine-cd4-positive, Alpha-Beta T Cell': 1,
         'Prostate-hillock Cell Of Prostate Epithelium': 1,
         'Bone Marrow-cd8-positive, Alpha-Beta T Cell': 1,
         'Vasculature-mast Cell': 1,
         'Thymus-naive Regulatory T Cell': 1,
         'Lymph Node-erythrocyte': 1,
         'Spleen-mature Nk T Cell': 1,
         'Liver-plasma Cell': 1,
         'Trachea-mast Cell': 1,
         'Large Intestine-transit Amplifying Cell Of Large Intestine': 1,
         'Lung-cd8-positive, Alpha-Beta T Cell': 1,
         'Bladder-plasma Cell': 1,
         'Lymph Node-memory B Cell': 1,
         'Bladder-vein Endothelial Cell': 1,
         'Bone Marrow-monocyte': 1,
         'Skin-macrophage': 1,
         'Spleen-plasma Cell': 1,
         'Blood-plasmablast': 1,
         'Lung-dendritic Cell': 1,
         'Trachea-cd8-positive, Alpha-Beta T Cell': 1,
         'Eye-melanocyte': 1,
         'Eye-eye Photoreceptor Cell': 1,
         'Lung-mesothelial Cell': 1,
         'Lymph Node-mature Nk T Cell': 1,
         'Prostate-macrophage': 1,
         'Large Intestine-cd8-positive, Alpha-Beta T Cell': 1,
         'Salivary Gland-cd8-positive, Alpha-Beta T Cell': 1,
         'Lymph Node-plasma Cell': 1,
         'Skin-regulatory T Cell': 1,
         'Prostate-neutrophil': 1,
         'Thymus-medullary Thymic Epithelial Cell': 1,
         'Lung-cd8-positive Alpha-Beta T Cell': 1,
         'Lung-bronchial Vessel Endothelial Cell': 1,
         'Spleen-plasmacytoid Dendritic Cell': 1,
         'Spleen-cd8-positive, Alpha-Beta Memory T Cell': 1,
         'Tongue-vein Endothelial Cell': 1,
         'Lymph Node-cd1c-positive Myeloid Dendritic Cell': 1,
         'Lung-smooth Muscle Cell': 1,
         'Vasculature-plasma Cell': 1,
         'Uterus-pericyte Cell': 1,
         'Mammary-pericyte Cell': 1,
         'Blood-cd8-positive, Alpha-Beta Cytokine Secreting Effector T Cell': 1,
         'Lung-alveolar Fibroblast': 1,
         'Eye-mast Cell': 1,
         'Pancreas-b Cell': 1,
         'Spleen-naive B Cell': 1,
         'Tongue-schwann Cell': 1,
         'Eye-plasma Cell': 1,
         'Eye-corneal Keratocyte': 1,
         'Lymph Node-t Cell': 1,
         'Bladder-capillary Endothelial Cell': 1,
         'Thymus-thymocyte': 1,
         'Fat-plasma Cell': 1,
         'Tongue-tongue Muscle Cell': 1,
         'Blood-macrophage': 1,
         'Blood-non-classical Monocyte': 1,
         'Trachea-fibroblast': 1,
         'Mammary-endothelial Cell Of Lymphatic Vessel': 1,
         'Heart-hepatocyte': 1,
         'Small Intestine-gut Endothelial Cell': 1,
         'Lung-lung Microvascular Endothelial Cell': 1,
         'Large Intestine-mast Cell': 1,
         'Salivary Gland-neutrophil': 1,
         'Bladder-b Cell': 1,
         'Kidney-b Cell': 1,
         'Fat-mast Cell': 1,
         'Blood-memory B Cell': 1,
         'Skin-cd141-positive Myeloid Dendritic Cell': 1,
         'Prostate-fibroblast': 1,
         'Thymus-fibroblast': 1,
         'Blood-monocyte': 1,
         'Uterus-t Cell': 1,
         'Bladder-plasmacytoid Dendritic Cell': 1,
         'Muscle-t Cell': 1,
         'Bone Marrow-naive B Cell': 1,
         'Eye-lacrimal Gland Functional Unit Cell': 1,
         'Prostate-t Cell': 1,
         'Fat-nk Cell': 1,
         'Small Intestine-enterocyte Of Epithelium Of Small Intestine': 1,
         'Blood-naive B Cell': 1,
         'Blood-t Cell': 1,
         'Bone Marrow-erythroid Progenitor': 1,
         'Blood-cd8-positive, Alpha-Beta T Cell': 1,
         'Eye-cd8-positive, Alpha-Beta T Cell': 1,
         'Spleen-erythrocyte': 1,
         'Large Intestine-b Cell': 1,
         'Thymus-endothelial Cell Of Lymphatic Vessel': 1,
         'Skin-plasma Cell': 1,
         'Tongue-fibroblast': 1,
         'Tongue-endothelial Cell Of Lymphatic Vessel': 1,
         'Thymus-innate Lymphoid Cell': 1,
         'Small Intestine-plasma Cell': 1,
         'Trachea-smooth Muscle Cell': 1,
         'Pancreas-mast Cell': 1,
         'Thymus-mature Nk T Cell': 1,
         'Skin-smooth Muscle Cell': 1,
         'Skin-nk Cell': 1,
         'Eye-muller Cell': 1,
         'Skin-naive B Cell': 1,
         'Spleen-nk Cell': 1,
         'Eye-ocular Surface Cell': 1,
         'Eye-adipocyte': 1,
         'Lymph Node-b Cell': 1,
         'Vasculature-b Cell': 1,
         'Lung-classical Monocyte': 1,
         'Skin-langerhans Cell': 1,
         'Tongue-capillary Endothelial Cell': 1,
         'Lymph Node-cd4-positive Alpha-Beta T Cell': 1,
         'Liver-fibroblast': 1,
         'Spleen-cd4-positive, Alpha-Beta Memory T Cell': 1,
         'Pancreas-pancreatic Stellate Cell': 1,
         'Prostate-mast Cell': 1,
         'Skin-melanocyte': 1,
         'Uterus-epithelial Cell': 1,
         'Blood-type I Nk T Cell': 1,
         'Blood-platelet': 1,
         'Large Intestine-immature Enterocyte': 1,
         'Lymph Node-non-classical Monocyte': 1,
         'Muscle-endothelial Cell Of Lymphatic Vessel': 1,
         'Liver-liver Dendritic Cell': 1,
         'Mammary-vein Endothelial Cell': 1,
         'Thymus-plasma Cell': 1,
         'Small Intestine-mast Cell': 1,
         'Muscle-cd8-positive, Alpha-Beta T Cell': 1,
         'Muscle-cd4-positive, Alpha-Beta T Cell': 1,
         'Lymph Node-mature Conventional Dendritic Cell': 1,
         'Uterus-fibroblast': 1,
         'Blood-naive Thymus-Derived Cd4-Positive, Alpha-Beta T Cell': 1,
         'Bone Marrow-nk Cell': 1,
         'Lung-respiratory Mucous Cell': 1,
         'Salivary Gland-t Cell': 1,
         'Blood-cd4-positive, Alpha-Beta Memory T Cell': 1,
         'Muscle-mesothelial Cell': 1,
         'Fat-mesenchymal Stem Cell': 1,
         'Skin-mast Cell': 1,
         'Lymph Node-cd8-positive, Alpha-Beta Memory T Cell': 1,
         'Blood-plasma Cell': 1,
         'Bone Marrow-cd4-positive, Alpha-Beta T Cell': 1,
         'Lung-plasma Cell': 1,
         'Small Intestine-paneth Cell Of Epithelium Of Small Intestine': 1,
         'Thymus-dendritic Cell': 1,
         'Liver-monocyte': 1,
         'Eye-dendritic Cell': 1,
         'Bladder-endothelial Cell Of Lymphatic Vessel': 1,
         'Spleen-intermediate Monocyte': 1,
         'Muscle-mature Nk T Cell': 1,
         'Small Intestine-cd4-positive, Alpha-Beta T Cell': 1,
         'Prostate-cd8-positive, Alpha-Beta T Cell': 1,
         'Salivary Gland-endothelial Cell': 1})

In [53]:
len(repeated_terms)

8

In [54]:
intersection = set.intersection(*repeated_terms)
intersection

set()

In [56]:
list(intersection)

[]

In [34]:
list(intersection)

['Salivary Gland-myoepithelial Cell',
 'Fat-macrophage',
 'Muscle-smooth Muscle Cell',
 'Lymph Node-stromal Cell',
 'Eye-ciliary Body',
 'Fat-smooth Muscle Cell',
 'Lung-basal Cell',
 'Large Intestine-mature Enterocyte',
 'Thymus-medullary Thymic Epithelial Cell',
 'Prostate-neutrophil',
 'Salivary Gland-adventitial Cell',
 'Trachea-fibroblast',
 'Blood-erythrocyte',
 'Lung-type I Pneumocyte',
 'Muscle-erythrocyte',
 'Vasculature-lymphatic Endothelial Cell',
 'Eye-macrophage',
 'Muscle-capillary Endothelial Cell',
 'Muscle-fast Muscle Cell',
 'Salivary Gland-ionocyte',
 'Prostate-smooth Muscle Cell',
 'Vasculature-smooth Muscle Cell',
 'Kidney-kidney Epithelial Cell',
 'Large Intestine-immature Enterocyte',
 'Muscle-endothelial Cell Of Lymphatic Vessel',
 'Muscle-endothelial Cell Of Artery',
 'Uterus-vascular Associated Smooth Muscle Cell',
 'Small Intestine-monocyte',
 'Fat-neutrophil',
 'Skin-cell Of Skeletal Muscle',
 'Bladder-fibroblast',
 'Thymus-fast Muscle Cell',
 'Fat-fibroblast',
 'Heart-fibroblast Of Cardiac Tissue',
 'Thymus-mesothelial Cell',
 'Eye-erythroid Lineage Cell',
 'Lung-mesothelial Cell',
 'Liver-hepatocyte',
 'Eye-limbal Stromal Cell',
 'Muscle-pericyte Cell',
 'Mammary-pericyte Cell',
 'Pancreas-fibroblast',
 'Thymus-capillary Endothelial Cell',
 'Lung-alveolar Fibroblast',
 'Lung-neutrophil',
 'Lung-capillary Aerocyte',
 'Spleen-endothelial Cell',
 'Eye-retinal Ganglion Cell',
 'Uterus-epithelial Cell Of Uterus',
 'Bladder-pericyte Cell',
 'Large Intestine-intestinal Tuft Cell',
 'Large Intestine-monocyte',
 'Uterus-ciliated Epithelial Cell',
 'Lung-vein Endothelial Cell',
 'Eye-epithelial Cell Of Lacrimal Sac',
 'Eye-corneal Keratocyte',
 'Thymus-vascular Associated Smooth Muscle Cell',
 'Salivary Gland-fibroblast',
 'Lymph Node-endothelial Cell',
 'Kidney-endothelial Cell',
 'Heart-smooth Muscle Cell',
 'Muscle-mesothelial Cell',
 'Eye-fibroblast',
 'Trachea-connective Tissue Cell',
 'Vasculature-epithelial Cell',
 'Heart-cardiac Endothelial Cell',
 'Bladder-smooth Muscle Cell',
 'Eye-limbal Stem Cell',
 'Prostate-erythroid Progenitor']

In [55]:
len(intersection)

0