# GSEA

In [4]:
# Install GSEApy if you haven't already
# !pip install gseapy

import pandas as pd
import gseapy as gp

def prepare_ranking(csv_file):
    # Load the CSV file containing Ensembl names, symbols, and ranks
    #csv_file = "/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/Results/feature_selection/RNAseq/ridge_L2_0/Experiment_GSE60590_feature_selection_Symbols.csv"
    gene_rank_df = pd.read_csv(csv_file)
    # check the first rows of the dataframe, if it starts with "","coef","abs_coef","NULL", replace NULL with "Symbol" and "" with "Ensembl"
    gene_rank_df.columns = ["Ensembl","coef","abs_coef","Symbol"]
    if gene_rank_df.columns[0] == "V1":
        gene_rank_df.columns = ["Ensembl","coef","abs_coef","Symbol"]
        # remove first row
        gene_rank_df = gene_rank_df.iloc[1:]
    # Add a column rank form 1 to len(gene_rank_df) with the rank of the gene depending on the abs_coef
    gene_rank_df['rank'] = gene_rank_df['abs_coef'].rank(ascending=False)
    return gene_rank_df

In [5]:
def get_GSEA(rank_dict):
    rank_file_path = "rank_file.txt"

    with open(rank_file_path, 'w') as file:
        for gene, rank in rank_dict.items():
            file.write(f"{gene}\t{rank}\n")


    results = gp.prerank(rnk=rank_file_path, gene_sets='Aging_Perturbations_from_GEO_down', outdir='gsea_results', min_size=10, max_size=1000, permutation_num=1000)
    return results

def main(file_name, csv_path = "Results/feature_selection/RNAseq/ridge_L2_0/"):
    
    #file_name = "Experiment_GSE60590_feature_selection_Symbols.csv"
    gene_rank_df = prepare_ranking(csv_path+file_name)
    rank_dict = dict(zip(gene_rank_df["Symbol"], gene_rank_df["rank"]))
    results = get_GSEA(rank_dict)
    enrichments = results.res2d
    best_enrichments = enrichments[enrichments['FDR q-val']<0.1].sort_values('FDR q-val', ascending=True)
    # save the results to a csv file
    best_enrichments.to_csv(f"{csv_path}GSEA/{file_name[:-4]}Aging_Perturbations_from_GEO_down.csv")

In [6]:
# for file in os.listdir("Results/feature_selection/RNAseq/ridge_L2_0/"), run the main function
import os
csv_path = "Results/feature_selection/RNAseq/ridge_L2_0/"
file_list = os.listdir(csv_path)
for file in file_list:
    if file.endswith("_Symbols.csv"):
        print(file)
        main(file, csv_path)
#main("Experiment_GSE60590_feature_selection_Symbols.csv")

2024-04-02 18:41:05,271 [WARNING] Duplicated values found in preranked stats: 0.48% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Experiment_GSE129643_feature_selection_Symbols.csv

2024-04-02 18:41:16,383 [WARNING] Duplicated values found in preranked stats: 6.83% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Experiment_GSE167186_feature_selection_Symbols.csv

2024-04-02 18:41:36,797 [WARNING] Duplicated values found in preranked stats: 0.44% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Experiment_GSE152558_feature_selection_Symbols.csv

2024-04-02 18:41:48,891 [WARNING] Duplicated values found in preranked stats: 0.41% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Sex_male_feature_selection_Symbols.csv

2024-04-02 18:42:04,640 [WARNING] Duplicated values found in preranked stats: 20.19% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Status_Sarcopenia_feature_selection_Symbols.csv

2024-04-02 18:42:31,201 [WARNING] Input gene rankings contains NA values(gene name and ranking value), drop them all!
2024-04-02 18:42:31,208 [WARNING] Duplicated values found in preranked stats: 0.41% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Status_Healthy_feature_selection_Symbols.csv

2024-04-02 18:42:49,449 [WARNING] Input gene rankings contains NA values(gene name and ranking value), drop them all!
2024-04-02 18:42:49,456 [WARNING] Duplicated values found in preranked stats: 16.61% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Experiment_GSE60590_feature_selection_Symbols.csv

2024-04-02 18:43:11,059 [WARNING] Duplicated values found in preranked stats: 4.76% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Experiment_GSE157585_feature_selection_Symbols.csv

2024-04-02 18:43:31,521 [WARNING] Duplicated values found in preranked stats: 0.45% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Experiment_GSE164471_feature_selection_Symbols.csv

2024-04-02 18:43:44,756 [WARNING] Duplicated values found in preranked stats: 0.41% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Sex_female_feature_selection_Symbols.csv

2024-04-02 18:44:00,983 [WARNING] Duplicated values found in preranked stats: 20.25% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Status_trained_feature_selection_Symbols.csv

In [7]:
# Load the CSV file containing Ensembl names, symbols, and ranks
csv_file = "/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/Results/feature_selection/RNAseq/ridge_L2_0/Status_Sarcopenia_feature_selection_Symbols.csv"

gene_rank_df = prepare_ranking(csv_file)
gene_rank_df

,Ensembl,coef,abs_coef,Symbol,rank
0,NaN,coef,abs_coef,NaN,1.0
1,ENSG00000102580.14,-0.018857047709948255,0.018857047709948255,DNAJC3,18802.0
2,ENSG00000068885.14,0.018654151401390134,0.018654151401390134,IFT80,18803.0
3,ENSG00000135842.16,-0.016877449549635187,0.016877449549635187,NIBAN1,18804.0
4,ENSG00000166855.9,0.016495561983061065,0.016495561983061065,CLPX,18805.0
...,...,...,...,...,...
34501,ENSG00000206549.13,-5.928299865491584e-07,5.928299865491584e-07,NaN,721.0
34502,ENSG00000188163.7,-5.255007503209008e-07,5.255007503209008e-07,FAM166A,847.0
34503,ENSG00000137648.17,-5.004335600727839e-07,5.004335600727839e-07,TMPRSS4,898.0
34504,ENSG00000250709.1,2.0916220013937137e-07,2.0916220013937137e-07,CCDC169-SOHLH2,18628.0
34505,ENSG00000100105.17,-9.512175352276902e-08,9.512175352276902e-08,PATZ1,86.0

In [ ]:

# Create a rank dictionary with Ensembl names as keys and ranks as values
rank_dict = dict(zip(gene_rank_df['Symbol'], gene_rank_df['rank']))

# get the symbos with abs_coef > 0.1
gene_rank_df_f = gene_rank_df[gene_rank_df['abs_coef'] > 0.5]
symbols = gene_rank_df_f['Symbol'].tolist()
#remove nan values
symbols = [x for x in symbols if str(x) != 'nan']
gp.Enrichr(gene_list=symbols, gene_sets='KEGG_2019_Human', outdir='test/enrichr_kegg',cutoff=0.5)

In [67]:
gene_rank_df

                  Ensembl          coef      abs_coef   Symbol     rank
0       ENSG00000198692.9  1.828671e-03  1.828671e-03   EIF1AY      1.0
1       ENSG00000226306.6 -1.822951e-03  1.822951e-03    NPY6R      2.0
2      ENSG00000129824.15  1.814952e-03  1.814952e-03   RPS4Y1      3.0
3      ENSG00000012817.15  1.746068e-03  1.746068e-03    KDM5D      4.0
4      ENSG00000130021.13 -1.629168e-03  1.629168e-03     PUDP      5.0
...                   ...           ...           ...      ...      ...
34500   ENSG00000139330.5  1.176759e-08  1.176759e-08     KERA  34501.0
34501  ENSG00000187243.16  1.039413e-08  1.039413e-08  MAGED4B  34502.0
34502   ENSG00000213090.2 -6.625257e-09  6.625257e-09  SCYL2P1  34503.0
34503   ENSG00000270499.1  3.259339e-09  3.259339e-09      NaN  34504.0
34504  ENSG00000101752.11  4.188577e-10  4.188577e-10     MIB1  34505.0

[34505 rows x 5 columns]

2024-04-02 17:14:30,811 [WARNING] Input gene rankings contains NA values(gene name and ranking value), drop them all!
2024-04-02 17:14:30,817 [WARNING] Duplicated values found in preranked stats: 16.61% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,Selenocompound metabolism,-0.487261,-2.104585,0.0,0.0,0.0,16/16,51.31%,INMT;PAPSS2;TXNRD1;SCLY;KYAT3;TXNRD2;MTR;TXNRD...
1,prerank,Olfactory transduction,0.581038,2.008736,0.0,0.0,0.0,344/434,30.70%,OR4E2;OR8A1;OR4E1;OR2H2;OR10AC1;OR2B2;OR1L6;OR...
2,prerank,Protein export,-0.45193,-2.000342,0.0,0.0,0.0,22/22,54.85%,SEC61G;SEC11A;IMMP1L;SRP68;SEC61A2;SPCS2;SRP72...
7,prerank,Maturity onset diabetes of the young,0.558944,1.599368,0.003012,0.062392,0.166,21/25,38.71%,HNF1A;NKX6-1;PKLR;FOXA2;INS;NEUROG3;SLC2A2;RFX...
9,prerank,Taste transduction,0.486326,1.544753,0.0,0.086176,0.318,56/75,38.73%,TRPM5;ASIC2;GABRA5;TAS2R46;TAS2R40;HTR3B;TAS2R...
8,prerank,Fructose and mannose metabolism,-0.376116,-1.598311,0.0,0.146939,0.012407,30/30,62.44%,HK2;PFKFB2;TPI1;TKFC;ALDOA;PFKM;PFKFB1;HK1;TIG...
5,prerank,Terpenoid backbone biosynthesis,-0.405272,-1.69386,0.0,0.164571,0.009926,19/19,59.51%,GGPS1;FDPS;HMGCS2;HMGCS1;PDSS2;MVK;ACAT1;DHDDS...
6,prerank,Fatty acid biosynthesis,-0.457167,-1.625537,0.0,0.171429,0.012407,13/13,54.31%,ACSL3;ACSL1;ACACB;MCAT;ACSL5;OXSM;FASN;ACSL6;A...
3,prerank,Glycosylphosphatidylinositol (GPI)-anchor bios...,-0.43626,-1.744294,0.0,0.205714,0.007444,25/25,56.42%,PIGS;PIGF;PIGU;PIGP;PIGL;PIGX;PIGT;DPM2;PIGB;P...
4,prerank,SNARE interactions in vesicular transport,-0.342579,-1.701688,0.0,0.205714,0.009926,33/33,65.79%,SNAP29;GOSR2;VTI1B;VAMP2;STX8;BET1;GOSR1;VAMP3...
10,prerank,DNA replication,-0.264921,-1.526763,0.0,0.205714,0.019851,36/36,73.55%,SSBP1;POLE;MCM4;POLE4;PRIM1;RFC1;POLE3;MCM2;RF...
11,prerank,Thyroid cancer,-0.308432,-1.477173,0.0,0.228571,0.024814,35/36,62.69%,CTNNB1;DDB2;CDKN1A;BAX;TPR;MAP2K2;MAPK1;RXRB;G...
13,prerank,Ascorbate and aldarate metabolism,0.49965,1.390779,0.036072,0.375761,0.938,14/23,36.44%,UGT1A4;UGT2B17;UGT2B10;UGT1A8;UGT2A3;UGT2B28;U...
12,prerank,Phototransduction,0.48958,1.398964,0.024121,0.426186,0.917,16/27,36.53%,CALML5;GUCA1C;GNAT1;GUCA1A;GUCY2F;GUCY2D;GNGT1...

In [1]:
#!pip install lxml
from gseapy import Msigdb
msig = Msigdb()
# mouse hallmark gene sets
# get database list
msig.gene_sets

/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/.venv/lib/python3.10/site-packages/gseapy/msigdb.py:20: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  d = pd.read_html(resp.text)[0]
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/.venv/lib/python3.10/site-packages/gseapy/msigdb.py:72: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  d = pd.read_html(resp.text)[0]

AttributeError: 'Msigdb' object has no attribute 'gene_sets'

In [8]:
import gseapy as gp
databases = gp.get_library_name()
# save on txt file
with open("Data/GSEA_Avaliable_databases.txt", "w") as file:
    for db in databases:
        file.write(f"{db}\n")

In [ ]:

# Print top enriched gene sets
print(results.res2d.head())

# Visualize enrichment results
gp.plot.gsea_plot(rank_metric=results.ranking, term=results.res2d.index[0], **results.results[results.res2d.index[0]])