In [12]:
import pandas as pd
import os

In [13]:

def process_csv(folder_path, file_name):
    # Read CSV file
    df = pd.read_csv(folder_path+file_name)

    df = df.T
    df.columns = df.iloc[0]
    # Drop the first row since it's now the column index
    df = df.drop(df.index[0])
    #df = df[df.index.str.startswith('abundance')]
    df["Experiment"] = file_name.split("_")[0]
    print(file_name)
    return df

In [14]:
folder_name = "Data/RNAseq/"
files_in_folder = os.listdir(folder_name)

In [39]:
united_df = pd.DataFrame()
for file in files_in_folder:
    if file.endswith(".csv"):
        df = process_csv(folder_name, file)
        united_df = pd.concat([united_df, df])
united_df

GSE164471_abundance.csv
GSE152558_abundance.csv
GSE157585_abundance.csv

Gen,ENSG00000000003.14,ENSG00000000005.5,ENSG00000000419.12,ENSG00000000457.13,ENSG00000000460.16,ENSG00000000938.12,ENSG00000000971.15,ENSG00000001036.13,ENSG00000001084.11,ENSG00000001167.14,...,ENSG00000285470.1,ENSG00000285471.1,ENSG00000285472.1,ENSG00000285476.1,ENSG00000285480.1,ENSG00000285491.1,ENSG00000285505.1,ENSG00000285508.1,ENSG00000285509.1,Experiment
SRR13388732,3.346531,0.0,7.02394,0.705439,3.879328,0.275243,7.74635,6.57469,8.136232,3.16629,...,0.137932,0.161723,0.311412,0.439481,0.0,0.0,0.0,4.61464,0.142626,GSE164471
SRR13388733,7.35135,0.0,13.916237,4.891812,2.885359,0.190321,16.006573,6.49818,10.725815,7.54512,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.802,1.11954,GSE164471
SRR13388734,7.671751,1.62451,18.72003,3.33803,9.629021,0.204143,19.061782,7.36854,11.420381,6.80192,...,0.204604,1.43937,0.0,0.167163,0.0,0.418267,0.0,2.37204,0.915094,GSE164471
SRR13388735,2.547355,0.184514,6.876067,0.888782,1.684829,0.0,3.182537,2.415355,2.24285,1.916299,...,0.0,0.0,0.0,0.1488,0.0,0.0,0.0,5.20632,0.813373,GSE164471
SRR13388736,15.728966,0.613411,14.120093,3.123864,10.45799,0.198544,12.34,19.44176,18.223213,3.72651,...,0.0,1.00531,1.54491,1.06955,0.379249,0.0,0.0,3.39066,0.707502,GSE164471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SRR12604223,2.612647,0.0,31.928334,1.667896,0.597671,0.739375,3.235589,4.42618,3.222874,2.145595,...,0.0,0.0,0.0,0.017432,0.682812,0.0,0.0,2.73878,0.046083,GSE157585
SRR12604224,2.757327,0.0,29.279355,2.452099,0.418084,0.430877,4.026302,2.89947,2.995782,1.50537,...,0.0,0.0,0.0,0.017054,1.11188,0.0,0.031533,0.0,0.014711,GSE157585
SRR12604225,2.265775,0.0,24.404861,1.799621,0.396952,0.350774,5.135432,1.784124,2.377629,1.39741,...,0.0,0.0,0.0,0.029258,1.4915,0.0,0.0,0.207596,0.013647,GSE157585
SRR12604226,1.699691,0.0,28.413171,0.861111,0.34396,0.186687,2.515463,2.225528,1.369262,1.176786,...,0.0,0.075888,0.0,0.020583,1.62889,0.0,0.0,0.0,0.051638,GSE157585
SRR12604227,2.086682,0.0,22.951375,1.774524,0.278745,1.213412,3.389966,5.06989,4.445236,1.89907,...,0.0,0.0,0.0,0.0,1.01598,0.0,0.0,0.0,0.073233,GSE157585

In [16]:
united_df.columns

Index(['ENSG00000000003.14', 'ENSG00000000005.5', 'ENSG00000000419.12',
       'ENSG00000000457.13', 'ENSG00000000460.16', 'ENSG00000000938.12',
       'ENSG00000000971.15', 'ENSG00000001036.13', 'ENSG00000001084.11',
       'ENSG00000001167.14',
       ...
       'ENSG00000285470.1', 'ENSG00000285471.1', 'ENSG00000285472.1',
       'ENSG00000285476.1', 'ENSG00000285480.1', 'ENSG00000285491.1',
       'ENSG00000285505.1', 'ENSG00000285508.1', 'ENSG00000285509.1',
       'Experiment'],
      dtype='object', name='Gen', length=34506)

In [17]:

Samples_data_age =  pd.read_csv("Data/Samples_data_age.csv")

In [22]:
Samples_data_age.index = Samples_data_age["Sample"]

In [43]:
z_data = pd.DataFrame()
for sample in united_df.index:
    if sample in Samples_data_age.index:
        row = Samples_data_age.loc[sample]
    else:
        experiment = united_df.loc[sample]["Experiment"]
        row = pd.Series([sample,experiment, 0])
        print(f"Missing sample {sample}")
    z_data = pd.concat([z_data, row], axis=1)
z_data = z_data.T
z_data.index = z_data["Sample"]
#z_data = z_data.drop("Sample", axis=1)
z_data

                  Sample Experiment Age
Sample
SRR13388732  SRR13388732  GSE164471  23
SRR13388733  SRR13388733  GSE164471  28
SRR13388734  SRR13388734  GSE164471  31
SRR13388735  SRR13388735  GSE164471  31
SRR13388736  SRR13388736  GSE164471  35
...                  ...        ...  ..
SRR12604223  SRR12604223  GSE157585  24
SRR12604224  SRR12604224  GSE157585  24
SRR12604225  SRR12604225  GSE157585  24
SRR12604226  SRR12604226  GSE157585  24
SRR12604227  SRR12604227  GSE157585  24

[135 rows x 3 columns]

In [44]:
united_df["Experiment"] = z_data["Experiment"]
united_df["Age"] = z_data["Age"]
united_df["Sample"] = z_data["Sample"]

In [45]:
united_df.index == united_df["Sample"]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [47]:
united_df.index = united_df["Sample"]

In [48]:
united_df

Gen,ENSG00000000003.14,ENSG00000000005.5,ENSG00000000419.12,ENSG00000000457.13,ENSG00000000460.16,ENSG00000000938.12,ENSG00000000971.15,ENSG00000001036.13,ENSG00000001084.11,ENSG00000001167.14,...,ENSG00000285472.1,ENSG00000285476.1,ENSG00000285480.1,ENSG00000285491.1,ENSG00000285505.1,ENSG00000285508.1,ENSG00000285509.1,Experiment,Age,Sample
Sample,,,,,,,,,,,,,,,,,,,,,
SRR13388732,3.346531,0.0,7.02394,0.705439,3.879328,0.275243,7.74635,6.57469,8.136232,3.16629,...,0.311412,0.439481,0.0,0.0,0.0,4.61464,0.142626,GSE164471,23,SRR13388732
SRR13388733,7.35135,0.0,13.916237,4.891812,2.885359,0.190321,16.006573,6.49818,10.725815,7.54512,...,0.0,0.0,0.0,0.0,0.0,13.802,1.11954,GSE164471,28,SRR13388733
SRR13388734,7.671751,1.62451,18.72003,3.33803,9.629021,0.204143,19.061782,7.36854,11.420381,6.80192,...,0.0,0.167163,0.0,0.418267,0.0,2.37204,0.915094,GSE164471,31,SRR13388734
SRR13388735,2.547355,0.184514,6.876067,0.888782,1.684829,0.0,3.182537,2.415355,2.24285,1.916299,...,0.0,0.1488,0.0,0.0,0.0,5.20632,0.813373,GSE164471,31,SRR13388735
SRR13388736,15.728966,0.613411,14.120093,3.123864,10.45799,0.198544,12.34,19.44176,18.223213,3.72651,...,1.54491,1.06955,0.379249,0.0,0.0,3.39066,0.707502,GSE164471,35,SRR13388736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SRR12604223,2.612647,0.0,31.928334,1.667896,0.597671,0.739375,3.235589,4.42618,3.222874,2.145595,...,0.0,0.017432,0.682812,0.0,0.0,2.73878,0.046083,GSE157585,24,SRR12604223
SRR12604224,2.757327,0.0,29.279355,2.452099,0.418084,0.430877,4.026302,2.89947,2.995782,1.50537,...,0.0,0.017054,1.11188,0.0,0.031533,0.0,0.014711,GSE157585,24,SRR12604224
SRR12604225,2.265775,0.0,24.404861,1.799621,0.396952,0.350774,5.135432,1.784124,2.377629,1.39741,...,0.0,0.029258,1.4915,0.0,0.0,0.207596,0.013647,GSE157585,24,SRR12604225
SRR12604226,1.699691,0.0,28.413171,0.861111,0.34396,0.186687,2.515463,2.225528,1.369262,1.176786,...,0.0,0.020583,1.62889,0.0,0.0,0.0,0.051638,GSE157585,24,SRR12604226
SRR12604227,2.086682,0.0,22.951375,1.774524,0.278745,1.213412,3.389966,5.06989,4.445236,1.89907,...,0.0,0.0,1.01598,0.0,0.0,0.0,0.073233,GSE157585,24,SRR12604227

In [49]:
united_df.to_csv("Data/RNAseq_All_abundances.csv")