In [1]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.metrics import matthews_corrcoef, confusion_matrix

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import resample
import matplotlib.pyplot as plt
import pandas as pd
import model as m
import seaborn as sns
import divide_bins as divide
import numpy as np
import feature_selection as fs
import getting_threshold_genes as gtg

2024-05-23 14:57:53.817513: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-23 14:57:53.819807: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-23 14:57:53.850112: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-23 14:57:53.850138: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-23 14:57:53.850760: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-23 14:57:53.856288: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-23 14:57:53.857060: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-23 14:57:54.565514: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
root = "/home/karen/Documents/phd/Data/Batch_corrected/"

files = [
    #"micro_z_Combat.csv",
#"RNAs_2_reCombat.csv",
#"micro_2_Combat.csv",
#"micro_z_reCombat.csv",
#"RNAs_z_Combat.csv",
#"micro_2_reCombat.csv",
#"RNAs_2_Combat.csv",
"RNAs_z_Combat_2.csv",
#"RNAs_2_Combat.csv",
#"RNAs_z_reCombat.csv"
]

In [3]:
for file in files:
    dataset = pd.read_csv(root+file)
    result = fs.get_feature_from_class(dataset)
    result.to_csv("Results/master/feature_selection/"+file.split(".")[0]+"_feature_selection.csv")
    print("Done with", file)

Done with RNAs_z_Combat_2.csv

In [4]:
"Results/master/feature_selection/"+file.split(".")[0]+"_feature_selection.csv"

'Results/master/feature_selection/RNAs_z_Combat_2_feature_selection.csv'

In [4]:
top_genes_set = []
for file in files:
    feature_scoring_path = "Results/master/feature_selection/"+file.split(".")[0]+"_feature_selection.csv"
    top_df = gtg.get_df(feature_scoring_path)
    top_genes_set.append(set(top_df["Ensembl"]))

 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  5 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
0.0860871588773362

/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py:945: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*new_inputs, **kwargs)
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/.venv/lib/python3.10/site-packages/numpy/lib/polynomial.py:668: RuntimeWarning: invalid value encountered in divide
  lhs /= scale

In [5]:
file = "micro_2_Combat.csv"
feature_scoring_path = "Results/master/feature_selection/"+file.split(".")[0]+"_feature_selection.csv"
feature_scoring_path

'Results/master/feature_selection/micro_2_Combat_feature_selection.csv'

In [6]:
rn_df = gtg.get_gene_rank(feature_scoring_path)
rn_df.to_csv("Results/feature_selection/RNAseq/"+file.split(".")[0]+"_gene_ranking.csv")

/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":

In [7]:
top_df = gtg.get_df(feature_scoring_path)
top_df

 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
 ** On entry to DLASCL parameter number  5 had an illegal value
 ** On entry to DLASCL parameter number  4 had an illegal value
0.0510835050578805

/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/getting_threshold_genes.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py:945: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*new_inputs, **kwargs)
/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/.venv/lib/python3.10/site-packages/numpy/lib/polynomial.py:668: RuntimeWarning: invalid value encountered in divide
  lhs /= scale

      Ensembl      coef  abs_coef
0    BC038401  0.162994  0.162994
1    AK094069 -0.125970  0.125970
2    AF493886  0.116093  0.116093
3    BC028058  0.115783  0.115783
4    AF362941 -0.113838  0.113838
..        ...       ...       ...
279  AF324499 -0.051164  0.051164
280  BC043445  0.051144  0.051144
281  BE222032  0.051132  0.051132
282  AI917078  0.051126  0.051126
283  BC036613 -0.051102  0.051102

[284 rows x 3 columns]

In [8]:
top_genes_set
# Get the genes that appear in all sets
genes_in_all_sets = set.intersection(*top_genes_set)

genes_union = set.union(*top_genes_set)

In [9]:
len(genes_union)

376

In [10]:
gene_counts={}
for gene in genes_union:
    gene_counts[gene] = 0
    for gene_set in top_genes_set:
        if gene in gene_set:
            gene_counts[gene] += 1

In [11]:
gene_counts_df = pd.DataFrame.from_dict(gene_counts, orient='index')
gene_counts_df.columns = ["Count"]
gene_counts_df = gene_counts_df.sort_values(by="Count", ascending=False)
gene_counts_df[gene_counts_df["Count"] >2]

Empty DataFrame
Columns: [Count]
Index: []

In [12]:
len(gene_counts)

376