## Common/repeated genes

In [1]:
import pandas as pd
import os
def prepare_ranking(csv_file):
    # Load the CSV file containing Ensembl names, symbols, and ranks
    #csv_file = "/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/Results/feature_selection/RNAseq/ridge_L2_0/Experiment_GSE60590_feature_selection_Symbols.csv"
    gene_rank_df = pd.read_csv(csv_file)
    # check the first rows of the dataframe, if it starts with "","coef","abs_coef","NULL", replace NULL with "Symbol" and "" with "Ensembl"
    gene_rank_df.columns = ["Ensembl","coef","abs_coef","Symbol"]
    if gene_rank_df.columns[0] == "V1":
        gene_rank_df.columns = ["Ensembl","coef","abs_coef","Symbol"]
        # remove first row
        gene_rank_df = gene_rank_df.iloc[1:]
    # check if the first row value is NaN
    if gene_rank_df.iloc[0][1] == "coef":
        gene_rank_df = gene_rank_df.iloc[1:]
    
    gene_rank_df = gene_rank_df.fillna(0)
    gene_rank_df["abs_coef"] = pd.to_numeric(gene_rank_df["abs_coef"], errors='coerce')
    gene_rank_df = gene_rank_df[gene_rank_df["abs_coef"]>0.0488]
    return gene_rank_df

In [2]:

csv_path = "Results/feature_selection/RNAseq/ridge_L2_0/"
file_list = os.listdir(csv_path)

In [3]:
file_list

['Experiment_GSE157585_feature_selection.csv',
 'Union',
 'Experiment_GSE152558_feature_selection.csv',
 'GSEA',
 'Experiment_GSE129643_feature_selection_Symbols.csv',
 'Experiment_GSE167186_feature_selection_Symbols.csv',
 'Status_trained_feature_selection.csv',
 'Experiment_GSE152558_feature_selection_Symbols.csv',
 'Sex_male_feature_selection_Symbols.csv',
 'Status_Sarcopenia_feature_selection_Symbols.csv',
 'Experiment_GSE164471_feature_selection.csv',
 'Sex_male_feature_selection.csv',
 'Status_Healthy_feature_selection_Symbols.csv',
 'Sex_female_feature_selection.csv',
 'Experiment_GSE129643_feature_selection.csv',
 'GO_Biological_Process_2018',
 'Status_Healthy_feature_selection.csv',
 'Sarcopenia_only',
 'readme.txt',
 'Experiment_GSE60590_feature_selection.csv',
 'Status_Sarcopenia_feature_selection.csv',
 'Experiment_GSE60590_feature_selection_Symbols.csv',
 'set_sarcopenia_genes.txt',
 'Experiment_GSE157585_feature_selection_Symbols.csv',
 'Experiment_GSE164471_feature_selection_Symbols.csv',
 'Sex_female_feature_selection_Symbols.csv',
 'Experiment_GSE167186_feature_selection.csv',
 'GO_BiologKEGG_2019_Humanical_Process_2018',
 'Status_trained_feature_selection_Symbols.csv']

In [4]:
sets_genes = []
sets_ranks = {}
ranks_sarcopenia={}
set_sarcopenia= set()
## for file in file_list, get the first column, get the values
for file in file_list:
    if file.endswith("_Symbols.csv"):
        df = prepare_ranking(csv_path+file)
        # get the first column
        genes = df["Symbol"].values
        sets_genes.append(set(genes))
        # add all the genes to the dictionary with the abs_coef as the value, if it already exist, sum the values
        for gene, coef in zip(df["Symbol"], df["abs_coef"]):
            if gene in sets_ranks:
                sets_ranks[gene] += coef
            else:
                sets_ranks[gene] = coef
        
        if "Sarcopenia" in file:
            set_sarcopenia = set(genes)
            for gene, coef in zip(df["Symbol"], df["abs_coef"]):
                ranks_sarcopenia[gene] = coef


#sets_genes

/tmp/ipykernel_81067/348435330.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/tmp/ipykernel_81067/348435330.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/tmp/ipykernel_81067/348435330.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/tmp/ipykernel_81067/348435330.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/tmp/ipykernel_81067/348435330.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/tmp/ipykernel_81067/348435330.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/tmp/ipykernel_81067/348435330.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/tmp/ipykernel_81067/348435330.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/tmp/ipykernel_81067/348435330.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/tmp/ipykernel_81067/348435330.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":
/tmp/ipykernel_81067/348435330.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if gene_rank_df.iloc[0][1] == "coef":

In [5]:
len(sets_genes)

11

In [6]:
# remove empty sets
sets_genes = [x for x in sets_genes if x]

In [7]:
# get the intersection of all sets
intersection = set.intersection(*sets_genes)
intersection

{0}

In [8]:
for s in sets_genes:
    print(len(s))

797
307
1806
3290
327
2701
706

In [9]:
# union all genes
union = set.union(*sets_genes)

In [10]:
len(union)

5005

In [11]:
len(set_sarcopenia)

0

In [15]:

set_sarcopenia
# save the set_sarcopenia and union to a file
with open("Results/feature_selection/RNAseq/ridge_L2_0/set_sarcopenia_genes.txt", "w") as f:
    for gene in set_sarcopenia:
        f.write(str(gene)+"\n")

In [13]:
# get elements that apear in at least half of the sets
half_intersection = set()
for gene in union:
    count = 0
    for genes in sets_genes:
        if gene in genes:
            count += 1
    if count >= 8:
        half_intersection.add(gene)
len(half_intersection)

17467

In [14]:
len(sets_ranks)

25019

In [15]:
sets_ranks
# order the dictionary by value and change the value for a rank from 1 to len(sets_ranks)
sets_ranks = {k: v for k, v in sorted(sets_ranks.items(), key=lambda item: item[1], reverse=True)}
# asing the value to the dictionary on the position they have
for i, gene in enumerate(sets_ranks):
    sets_ranks[gene] = i+1

In [16]:
len(sets_ranks)

25019

In [17]:
len(intersection)

10545

In [18]:
sets_ranks.keys()

dict_keys([0, 'NDST2', 'SLC49A4', 'FAM153B', 'LSP1P5', 'RUNX1T1', 'IFNAR2', 'PRH1', 'CLN3', 'COMMD7', 'RBM27', 'C4orf36', 'GTPBP6', 'TPPP2', 'ULK4P1', 'ST6GALNAC6', 'ARL16', 'ASB15', 'TEKT3', 'LRTOMT', 'GNGT2', 'ARHGAP11B', 'RPSAP64', 'ADPRH', 'GOLGA6L9', 'DARS1', 'TRMT44', 'CARD10', 'TMC8', 'CAPN8', 'MYL12B', 'COMT', 'RPL9P30', 'RAPGEF3', 'SLC4A1', 'EIF2S3', 'TBC1D3', 'TSPYL4', 'TRMT9B', 'LVRN', 'CLSTN3', 'PHF7', 'PHLPP1', 'FBXO10', 'NIPAL3', 'PLEKHM1', 'PARP11', 'C3orf14', 'C11orf53', 'BTN3A2', 'CST3', 'FLVCR2', 'DET1', 'C8orf33', 'CEP95', 'RPL36AP18', 'TMCO1', 'PROSER1', 'IRF9', 'SPCS3', 'PEDS1', 'GORAB', 'ARMC1', 'PECAM1', 'ATP6V0B', 'ATP5MC1', 'PPP2R2B', 'SPAG1', 'VWCE', 'MCAT', 'PRB2', 'HMGN1P8', 'EIF4EBP1', 'CIDECP1', 'DPY19L3', 'SUGT1P3', 'ARSK', 'ZNF800', 'ZNF101', 'MLKL', 'MFNG', 'STRN4', 'SEC23A', 'SLC22A5', 'DPY19L1', 'MYO9B', 'KCTD21', 'CDO1', 'ARHGAP25', 'ASB13', 'PDE4C', 'PSMD14', 'RPL21P51', 'CYCSP3', 'GPR82', 'UVSSA', 'CDH18', 'ARHGEF1', 'PRPF19', 'YWHAQP5', 'PI4KAP2', 'CDH5', 'CLDND2', 'RAB8B', 'LONRF1', 'SPECC1P2', 'RAB9A', 'BICD2', 'CRYBG3', 'AP4M1', 'ZNF423', 'KCNJ13', 'SLC2A12', 'BTK', 'SPTBN4', 'CCT6P3', 'RALGDS', 'CLEC7A', 'ARRB2', 'KLHL38', 'JAZF1', 'CARNS1', 'CEP41', 'MSMO1', 'TBC1D24', 'ERC2', 'ADAMTS6', 'ANGPT2', 'CWC25', 'PPP1R36', 'PECR', 'LRP1', 'SEMA3D', 'PNP', 'SLC35A2', 'MTX3', 'SLC35A5', 'ZNF778', 'ZNF749', 'TMEM248', 'C7orf50', 'ZBTB17', 'CIAO3', 'PARVG', 'YTHDC2', 'SLC35G2', 'TMED7-TICAM2', 'PPIL1', 'ACER3', 'CACNG6', 'SH2D4A', 'SERP2', 'ZNF385D', 'CHAF1B', 'TUT1', 'GFPT2', 'DNAJC9', 'C3orf38', 'TRMT10A', 'SLC26A8', 'CHMP4A', 'GABRA1', 'DYNC1I1', 'ZNF821', 'MMP2', 'CNTNAP3B', 'ADGRV1', 'SPDYE10', 'CDC40', 'ANP32B', 'ABITRAM', 'MIF4GD', 'PPP2R2A', 'CBX7', 'BRD9P2', 'SLC37A1', 'NT5DC3', 'LYPD5', 'MND1', 'RPS29P19', 'FKBP11', 'GYPE', 'MXRA8', 'PIEZO1', 'DCAF7', 'CRIP1', 'DBN1', 'ADAT1', 'AKT1', 'FAN1', 'MRPS21P7', 'RNF115', 'OBSL1', 'ITIH6', 'CABP4', 'MED17', 'MBOAT2', 'TMEM214', 'CTSW', 'LY6G5B', 'CTU2', 'CROT', 'DPF1', 'LRRC14', 'PAAF1', 'PLEKHM2', 'NAA30', 'CARHSP1', 'LRRC8A', 'ATL1', 'MMAB', 'SACM1L', 'ISG20', 'ORAI3', 'RAB41', 'HERC5', 'TUBB4A', 'TRIM74', 'C9orf153', 'CSGALNACT1', 'ST18', 'RPS23', 'GUCY1B2', 'ZACN', 'SLC9A3R2', 'ZNF689', 'NIPAL1', 'TUFT1', 'TADA1', 'SNAP23P1', 'FBXL4', 'KDM7A', 'SESTD1', 'LPIN2', 'OR7A19P', 'MVB12A', 'SFR1', 'SCHIP1', 'ASF1A', 'AMY2A', 'RPL37P6', 'SLC13A3', 'OSCP1', 'FRS3', 'TUB', 'RSAD2', 'SV2B', 'RPL21P37', 'F3', 'WIZ', 'NTRK2', 'GSTK1', 'HGH1', 'SSX2IP', 'PRKACA', 'EMP3', 'TMSB15B', 'FRA10AC1', 'TBC1D22A', 'AK7', 'CCDC51', 'KDM4A', 'MID1IP1', 'LOC541473', 'CERK', 'ATP1A4', 'SH3TC1', 'CX3CR1', 'MAP4K1', 'SETD6', 'TNFRSF19', 'CRHR2', 'SMIM15', 'C4BPA', 'IRAG2', 'RIMBP2', 'ZNRD2', 'SERF1A', 'COL4A6', 'TLR4', 'LHFPL2', 'SORL1', 'DAZAP1', 'IFITM3', 'STAB1', 'PEX13', 'BCAR1', 'UFM1', 'TJAP1', 'TRIM54', 'ALYREF', 'C1RL', 'GPRC5C', 'AGTRAP', 'PRMT3', 'TRPV3', 'C4orf17', 'MRPS35P2', 'RPS14P6', 'XPO1', 'TMEM167A', 'CHTF8', 'MASP2', 'PIK3R4', 'ENO2', 'MDM1', 'TMEM150C', 'PDLIM5', 'SEMA3A', 'BASP1', 'CATSPER2P1', 'MNAT1', 'TBL2', 'DEFB122', 'RPL26P12', 'GDPD5', 'ITM2A', 'AMPH', 'SLC6A1', 'LETM2', 'ACAT2', 'STARD8', 'STK35', 'PKIG', 'CATSPERG', 'OCM2', 'PSMC3', 'MYL6', 'ATP11C', 'IGKV2D-28', 'RGL3', 'GRAMD1C', 'RPL21P103', 'ANAPC11', 'TRIM63', 'SPRED1', 'EIF2AK3', 'RPL7AP16', 'HID1', 'CTIF', 'RPL21P60', 'RNASET2', 'LOC101929006', 'MCRIP2', 'KRT8', 'DAPP1', 'SELE', 'TMEM100', 'CTNNA2', 'CDH2', 'AHSP', 'SLC6A15', 'SLC27A1', 'EID2B', 'ZNF594', 'PTPRU', 'SEC11A', 'AKT1S1', 'TFIP11', 'MCTP2', 'RPL34P6', 'CORO7', 'PLEKHM3', 'MAP6', 'HSPB11', 'DSTNP4', 'ENTPD1', 'SPATA20', 'PKD2', 'GPR108', 'BAIAP2', 'LMBRD2', 'ERAP1', 'ZCWPW2', 'CRACDL', 'LRP11', 'ARVCF', 'MOB1B', 'POC5', 'FABP4', 'MCOLN3', 'OR8B3', 'DHCR7', 'SOX5', 'ARF5', 'PCYT1B', 'SNX29', 'MRPS6', 'PHYKPL', 'VPS4A', 'NDUFB1', 'SPICE1', 'CCDC149', 'SIL1', 'SIX5', 'ZMYM4', 'SEMA6B', 'MCM5', 'NOL6', 'OSTC', 'SPNS1', 'ZNF444', 'RASSF6', 'ZHX3', 'C3orf62', 'GDPD4', 'RIPK1', 'LRP4', 'C10orf88', 'TRIML2', 'VCAN', 'CPE', 'NEK4', 'ATE1-AS1', 'APELA', 'RPL23AP24', 'FRAT2', 'GOLGA6A', 'GLMN', 'CDIP1', 'MMACHC', 'PJA1', 'ZCRB1', 'RNF135', 'KLHL18', 'AFG3L1P', 'JOSD2', 'SELP', 'ROM1', 'CES4A', 'NUP153', 'RPLP0', 'FAM104B', 'HPF1', 'CENPNP1', 'SPTSSB', 'UBA1', 'TRAV29DV5', 'GPR141', 'HNRNPL', 'GOT1', 'LSM8', 'RPS3AP25', 'TMEM242', 'ETNK2', 'ZNF398', 'ELMOD3', 'NR1H2', 'UBE2FP3', 'EPB41L1', 'NCOR1', 'TBX1', 'VASH2', 'SYT1', 'DESI1', 'RPL7P25', 'HMGN1P14', 'ZNF85', 'ADAM12', 'GLYAT', 'HJURP', 'SAV1', 'ABI1', 'FAF2', 'CEP72', 'ZNF737', 'PPM1N', 'SREBF1', 'MAPKAPK2', 'GDPD3', 'C16orf87', 'TCAF2', 'TMEM30CP', 'KCNJ10', 'DPCD', 'NDUFB7', 'CRLS1', 'WNT5B', 'CERS2', 'SLF1', 'GPC2', 'SEPHS1', 'SUMO4', 'PEBP4', 'FAM86B3P', 'RASA1', 'DNAH8', 'PMS2', 'TNKS1BP1', 'MPEG1', 'RPL21P29', 'MTCYBP13', 'PARVA', 'GINS4', 'SLC46A1', 'RBM24', 'ZNF101P2', 'COG4', 'VPS50', 'SEC22A', 'TTYH2', 'NTMT1', 'KLK4', 'CPSF3', 'FUCA1', 'SRP14P3', 'RPL10', 'CNTNAP1', 'RAB3IP', 'STAT4', 'TSC2', 'PML', 'SRSF10', 'NPIPB5', 'CDK8', 'C2CD2L', 'BMS1P13', 'SUGCT', 'RPL5P22', 'POLE2', 'IP6K1', 'KHDC1', 'LOC442028', 'CPM', 'CCDC40', 'BMS1P3', 'ARHGEF38', 'PYGL', 'GMNC', 'SPIN3', 'DGCR6L', 'ZNF816', 'ATG3', 'TIFA', 'C17orf58', 'FADS3', 'MMP20', 'SAMD4B', 'SLC38A5', 'MICAL1', 'PKD1L2', 'PKIB', 'NDUFB8', 'PRDX5', 'UBL5P1', 'RPSAP14', 'NOC4L', 'TCN2', 'FLT1', 'RELL1', 'YPEL5', 'FKBP7', 'DGCR2', 'TNFAIP8L3', 'NET1', 'LOC105371814', 'ZNF197', 'POLR2A', 'JHY', 'E2F4', 'PLXDC1', 'CDK19', 'ATP8B5P', 'ALG12', 'C7orf26', 'PMS2CL', 'EZH1', 'NEMF', 'NEK6', 'RPL8', 'PDCD7', 'RPS12P6', 'ZNF691', 'PAFAH1B3', 'PLB1', 'EHD1', 'FAM133B', 'SLC25A14', 'ARHGAP22', 'SRGAP2B', 'SIPA1L1', 'DIO2', 'TRAV12-2', 'PBLD', 'DEPDC5', 'CRIP1P3', 'SUCLG2', 'PDPK1', 'WDFY4', 'LOC100288570', 'LGALS1', 'DRD2', 'ELL3', 'ARHGAP44', 'BCL7C', 'PAQR9', 'RPL21P48', 'SEC22C', 'CNTN4', 'SRSF1', 'POTEB', 'OR11H2', 'TGFBR1', 'TM4SF18', 'FCHO2', 'CCDC9B', 'DLGAP1', 'POMZP3', 'RBMXL1', 'RPS18P5', 'NFKB1', 'FSTL3', 'RPL7P57', 'ATP5F1A', 'RPL37', 'TMEM176A', 'ASB7', 'BTG1', 'FBXW4', 'ANKUB1', 'C8orf76', 'ENOX2', 'DDX10P1', 'PPP2R5D', 'KCNAB2', 'GSTZ1', 'KBTBD6', 'GATAD2B', 'CGA', 'ERO1A', 'ATAD2', 'TMEM18', 'OR6N1', 'EIF6', 'SENP2', 'FANCG', 'DNAH14', 'C12orf50', 'HOXD8', 'FABP2', 'ZNF19', 'BUD31', 'ZNF227', 'MAPK6', 'POLR3E', 'BPIFA4P', 'KIF18A', 'ANKRD52', 'GGT5', 'THAP3', 'GOLGA8J', 'PDE4DIPP6', 'GALNTL6', 'HMGB1P17', 'ZNF41', 'CTNNB1', 'TRPC6', 'GTF2IP1', 'DYNC1LI2', 'SCIN', 'CASP10', 'MBOAT1', 'OSTN', 'CTNND2', 'CTHRC1', 'SUMO3', 'NT5C', 'PCMTD2', 'TXK', 'LAMB3', 'MIB2', 'DDR1', 'INHBA', 'APLNR', 'CHRFAM7A', 'SHC1', 'MOCS1', 'NAIPP3', 'ZFP69', 'SSNA1', 'CDYL2', 'DESI2', 'PABIR2', 'ZSCAN25', 'ADGRF5P1', 'SNRPC', 'RNF113A', 'GDI1', 'PARP3', 'FNDC3B', 'RPL7AP3', 'GAL3ST1', 'CCDC92', 'SS18', 'ETAA1', 'ZNF214', 'SLC31A2', 'ADIPOR2', 'ASH2L', 'ZNF177', 'ANAPC5', 'FBXL17', 'GRIPAP1', 'PCNX2', 'RARG', 'ARG1', 'SBSPON', 'GRID2', 'RPL36AP54', 'SOD1', 'GAB3', 'USP17L9P', 'ZNF135', 'PLG', 'TRIM34', 'HOOK1', 'TRAV25', 'DISC1', 'TMEM178A', 'COL6A1', 'THAP8', 'RPS6KA1', 'PPP1R27', 'PTGES', 'MRPS25', 'RLIM', 'PALM2AKAP2', 'GSN', 'TRMO', 'SLC22A17', 'MRFAP1L1', 'TSPAN3', 'NDUFB9P3', 'CCDC127', 'CATSPERE', 'CA5B', 'VPS72', 'SLC48A1', 'HMGB1P12', 'HERC2P9', 'TTC7A', 'TPCN2', 'IDH3G', 'ZNF384', 'CCDC142', 'PAN3', 'CHI3L2', 'CYP2C61P', 'PLEKHG2', 'TBCEL', 'AFF3', 'DIPK2A', 'NPR3', 'PNPLA6', 'GOLGA8M', 'GALNT7', 'RPL35AP22', 'LARP7P4', 'PHF12', 'APOL2', 'SLC20A1', 'KCNH1', 'LRRC47', 'HACL1', 'SH2B3', 'SLC33A1', 'METTL18', 'DHX36', 'RAB11FIP3', 'PHGDH', 'RPL31P4', 'DNM3', 'MRPL38', 'CCDC62', 'MTND2P21', 'SGCA', 'CPSF1', 'LIN9', 'ADGRG1', 'B4GALT3', 'GID8', 'BHLHB9', 'TUBGCP6', 'COMMD3-BMI1', 'RNF185', 'SLFN13', 'HRK', 'LGALS7', 'WDR17', 'ZFYVE19', 'SNRPGP14', 'C14orf93', 'C11orf71', 'FRAS1', 'ST13P12', 'LIG1', 'GPR137', 'UBE2F-SCLY', 'ADA2', 'UPB1', 'ASGR2', 'ZFAND6', 'TNFAIP8', 'TMEM216', 'COX20', 'EEF2KMT', 'ZNF511', 'HSD17B1', 'LRRC37A5P', 'KLHL15', 'ITGA4', 'DDRGK1', 'PHF2', 'FAM90A12P', 'SNIP1', 'PPARA', 'IFNW1', 'SYNJ2BP', 'MOCS3', 'SH3BP4', 'USP48', 'C9orf64', 'INTS13', 'DKK2', 'CAVIN4', 'DCSTAMP', 'VPS13A', 'PAFAH2', 'RPS12P7', 'SCRN2', 'POGK', 'CHMP7', 'AP4B1', 'LOC100420983', 'VPS53', 'S100A4', 'LDOC1', 'NAPB', 'ANPEP', 'JAK1', 'ANKRD49', 'ANKMY1', 'AGAP3', 'TASOR2', 'RPL21P95', 'AMHR2', 'IGLJCOR18', 'ENOX1', 'BEND5', 'NABP1', 'ZFAND4', 'FAAP20', 'CD72', 'PIGBOS1', 'TMEM53', 'SMN1', 'EOLA1', 'FPGS', 'AFF1', 'GRK4', 'NEK11', 'MRPL45', 'ID3', 'NCLN', 'ADCY7', 'SNTG2', 'CPSF7', 'SEL1L2', 'PCDHGA4', 'ARL6', 'HAUS8', 'IGHVII-28-1', 'SMIM27', 'FLVCR1', 'KCTD6', 'LEO1', 'DNAJB11', 'EBF4', 'KLK15', 'GIPR', 'ZNF627', 'BLCAP', 'MTND1P37', 'TBL1X', 'HGSNAT', 'NDUFA13', 'TRAK2', 'TMCO6', 'SRBD1', 'LINC02693', 'TPH2', 'HOXC4', 'POLR1E', 'C11orf58', 'GNG12', 'SCML2', 'IKZF1', 'KLC1', 'PDE10A', 'ALG10', 'SETDB1', 'PLPPR2', 'APOBEC3G', 'WDFY2', 'PHTF1', 'XKR9', 'IFIT2', 'PRKD2', 'PKD2L2', 'CRIP2', 'SOX4', 'CDKN2AIP', 'PDE11A', 'ECI1', 'HEG1', 'STX4', 'C15orf40', 'DHX37', 'MTATP6P21', 'SLC45A4', 'TELO2', 'HORMAD1', 'RASA2', 'SSX7', 'PELI2', 'SPINK5', 'L3MBTL2', 'ATG9B', 'MTCO3P23', 'MAPK8IP3', 'TMEM269', 'ZNF883', 'KCNMB3', 'GPX6', 'SPCS2', 'RPGR', 'ZRANB2', 'KLRD1', 'LRRC19', 'C11orf1', 'LOC101060021', 'HOXA13', 'C1orf216', 'HSP90B2P', 'DBNDD2', 'C1orf50', 'HNRNPAB', 'FEZ1', 'BEND6', 'FKBP1A', 'DDC', 'GP2', 'SSC5D', 'NCAM2', 'P4HA2', 'GBP4', 'YIF1B', 'TRMT5', 'ZNF223', 'RDH13', 'IDO1', 'RPL24P9', 'BOLA2', 'DGCR6', 'ESRP1', 'KIF21A', 'IL2RG', 'RBBP8', 'LOC100129534', 'FMN1', 'MTND4LP13', 'TNFRSF10A', 'PSMD13', 'C5orf24', 'MYL5', 'NCOA1', 'EDA2R', 'CCT6B', 'CD6', 'PRC1', 'KIF6', 'RPL6P3', 'SLC25A51P4', 'EEF1A2', 'RPS4XP6', 'CYTB', 'DONSON', 'DTX2', 'LCN15', 'SOCS7', 'XKR8', 'TRAV10', 'CITED4', 'CACNA2D3', 'TBCK', 'NR5A2', 'ZNF26', 'GABRD', 'CNTN1', 'FDX2', 'NDUFS2', 'DZIP1L', 'RHAG', 'TRAPPC3L', 'CDK15', 'MEGF11', 'A2ML1', 'TIRAP', 'LDHA', 'ETV4', 'KNOP1P2', 'ZCCHC8', 'SLC38A7', 'ZDHHC1', 'IGSF21', 'ANG', 'CYP4Z1', 'DDX18P1', 'CDRT1', 'PEG3', 'CRHBP', 'DPYD', 'ZBTB48', 'RPL36AP11', 'KCNAB3', 'PCDHGA7', 'COX19', 'RPL35P6', 'ZNF90', 'C4orf19', 'ANKS6', 'DNTTIP1', 'RFX2', 'PRLR', 'ZNF581', 'TBC1D30', 'RPN1', 'CNTNAP3', 'SHCBP1', 'IKZF4', 'SLA', 'SNRPCP7', 'GDAP1L1', 'UBE2C', 'TDGF1', 'EDA', 'PHF23', 'EVI2A', 'TCN1', 'ABAT', 'MAD2L1', 'METTL1', 'PIPSL', 'LOC652276', 'ARHGAP9', 'THEM4', 'ELN', 'OSBPL2', 'CDK2', 'IHO1', 'CA9', 'LOC359819', 'SFMBT1', 'RPL23AP31', 'ZNF461', 'BOLA2P2', 'PYDC1', 'CR1L', 'ARSG', 'PGLS', 'NBPF11', 'GPC1', 'VSTM4', 'LSS', 'MPDU1', 'RPLP1', 'ALG11', 'FGD5', 'CYCSP42', 'SNED1', 'DCAF8', 'QPCTL', 'CD151', 'IFTAP', 'LOC105372179', 'RPL36AP26', 'RHD', 'MST1', 'OR51F2', 'PPP1R3B', 'YTHDF2', 'BCLAF3', 'COL8A1', 'RBPMS2', 'EIF4E2P1', 'ACTR6', 'PDE6C', 'WDR89', 'SLC39A3', 'SLC25A18', 'CHCHD2', 'OR7E136P', 'LAMP3', 'ERLIN2', 'FAM186A', 'CDH1', 'MTMR10', 'IL1RL1', 'FKBP14', 'TP53INP1', 'CRCP', 'FOXK1', 'HTR2A', 'AOAH', 'CPD', 'ZNF337', 'ZNF544', 'ATP6AP1', 'RNF227', 'TUBGCP4', 'ICMT', 'EEPD1', 'RAB29', 'ZNF830', 'NCAPG', 'DNAJB12', 'CDKN3', 'MCM7', 'GPRASP2', 'MFSD4B', 'CENPBD1P', 'WNK3', 'TCF7', 'PFKM', 'SLFN11', 'NOTCH3', 'PTCD2', 'ELAC1', 'LOC440700', 'HPCAL1', 'OAZ1', 'HSP90B1', 'TOMM70', 'OLFML2A', 'PEG10', 'JADE3', 'INPP5D', 'SLC6A14P3', 'RABGAP1L', 'NUP98', 'ARHGAP42', 'LIG4', 'PRKCE', 'CD300LD', 'ELOB', 'DIAPH2', 'RPL32P13', 'SDC4', 'HSPE1P1', 'LETM1', 'GNB5', 'CLEC1A', 'PCDHGC3', 'NUP155', 'RNF7', 'GYPC', 'DOCK11', 'OR13G1', 'GUK1', 'CORIN', 'PRELID1', 'SSX5', 'TBC1D3B', 'CNBD1', 'MARCHF7', 'WNT10A', 'LRRC27', 'MYBPHL', 'IMMP1L', 'FGD6', 'GHDC', 'LOC100132834', 'DPF3', 'RGMB', 'NBPF12', 'OR7E7P', 'AOC4P', 'CD59', 'SCOC', 'IQANK1', 'HP', 'MTND4LP11', 'HNRNPA3P14', 'UBE2D3', 'AFG3L2', 'ICAM2', 'ARHGAP6', 'NCOR1P1', 'LOC646870', 'PSAP', 'MYLPF', 'P2RX3', 'UBB', 'APPL2', 'ZNF219', 'TNFRSF14', 'ADGRG7', 'PIP4K2C', 'SPATA6', 'F5', 'MYO15B', 'CHTOP', 'DSTYK', 'CXCL2', 'PLXNA4', 'TVP23CP1', 'SPDYE3', 'STK39', 'ZCWPW1', 'FTLP19', 'STXBP2', 'CCDC150', 'BMS1P22', 'ZNF554', 'ANKH', 'SOHLH2', 'C17orf100', 'EIF2AK1', 'RAB15', 'HACE1', 'DHTKD1', 'OR10G4', 'MTCO1P22', 'ZNF669', 'PCDHGB8P', 'TRIM11', 'DHX35', 'DMAP1', 'EAPP', 'LINC00869', 'YJEFN3', 'HOOK2', 'AVEN', 'TSSK3', 'NPHP1', 'SNAP23', 'DUXAP9', 'KCNC2', 'NPIPB9', 'AP1M2', 'CFP', 'BANK1', 'ALDH8A1', 'CALCOCO2', 'ANXA2', 'TEPSIN', 'OR5P1P', 'TRPV2', 'LPXN', 'PLP1', 'RP1L1', 'CCDC60', 'IL3RA', 'TMOD2', 'FPR2', 'COL6A3', 'URI1', 'MRPL33', 'TMEM71', 'CENPT', 'TMBIM4', 'SNRPB', 'DCK', 'SEPTIN6', 'FUZ', 'H4C11', 'FOSB', 'YEATS4', 'GSG1', 'NPM2', 'P4HTM', 'EXOSC1', 'DCAF16', 'ZNF211', 'PRKCZ', 'TRAPPC14', 'AKR7L', 'PKD1', 'TRDMT1', 'JSRP1', 'PLEKHS1', 'ASS1', 'ZNF547', 'CRX', 'TEX35', 'CARMIL2', 'SPOCK1', 'MTATP6P26', 'PMF1', 'FCRL3', 'INF2', 'MTCO3P31', 'LIPE', 'SLC43A2', 'OR5F2P', 'RPL7', 'MACO1', 'TUBD1', 'NR1D2', 'PSG1', 'SLC2A4', 'AMOTL2', 'CDH17', 'ECM1', 'FAM199X', 'L3MBTL4', 'TP73-AS1', 'MEDAG', 'MACROD2', 'PHF1', 'PRTFDC1', 'PDE7A', 'DLG3', 'BTG3', 'ATP1A2', 'PRR3', 'PRSS40A', 'PRELID3BP8', 'CLEC17A', 'ZNF850', 'RPL19P2', 'TCEA2', 'ANGPTL3', 'ASPDH', 'HCLS1', 'POLL', 'B3GNTL1P1', 'NLRP1', 'NEK3', 'ACACA', 'RBBP4', 'ZNF514', 'NME1-NME2', 'SLC39A14', 'CMPK2', 'RPL14', 'DALRD3', 'CLIP2', 'SLC1A2', 'SGSM1', 'ENPP3', 'ZNF28', 'PAEP', 'N6AMT1', 'LMNTD1', 'ZDHHC17', 'KLHL9', 'KIAA0895', 'RGS4', 'MORN2', 'DNAJC2', 'ADAMTS8', 'ZNF695', 'BCL2L2', 'GCAT', 'GOLGA6L4', 'RANP9', 'NINL', 'EPB41', 'SMARCC2', 'KCNJ15', 'TOLLIP', 'EXT2', 'ZNF234', 'SORCS2', 'DLG2', 'DHX58', 'CCDC198', 'C11orf68', 'RNF216', 'RFLNB', 'RPL9P20', 'RPL21P52', 'UQCRHL', 'GGT1', 'TEC', 'CIAO2A', 'NR1H3', 'RPS2', 'SLC6A9', 'COLGALT2', 'TNFSF12', 'RCBTB1', 'HYI', 'POC1B-GALNT4', 'GRPEL2', 'GGNBP2', 'SNRPD3', 'TYRO3', 'MAGI1', 'NAPSB', 'PTPN22', 'CARM1', 'RAE1', 'C5', 'USP9YP14', 'CDC7', 'PSMC6P2', 'CLN6', 'LOC728488', 'MPHOSPH10', 'TRA2A', 'GATA3', 'RABGGTA', 'GANC', 'IL18RAP', 'GPR156', 'TRAF3', 'MCM3AP', 'PCDHB9', 'ZNF155', 'SPRTN', 'FAM107B', 'CD300A', 'TRPC7', 'TRBVB', 'MESD', 'RPL23AP36', 'METTL14', 'PEX7', 'LSP1', 'FAM219A', 'DPP6', 'TMEM65', 'CASP3', 'SUGP2', 'MSTN', 'DDX55', 'ABCC6P2', 'CD68', 'GATM', 'OPA3', 'DNAJC12', 'RBKS', 'TTLL1', 'FAM3C', 'YBEY', 'MREG', 'LOC728554', 'C1orf100', 'SERPINH1', 'SLFN5', 'CFAP74', 'CCDC85B', 'DDA1', 'TTC33', 'CHM', 'ANKRD40CL', 'ZNF780A', 'PTGES2', 'HBD', 'MATR3', 'RNH1', 'MTCO3P29', 'ABHD4', 'IL17RE', 'DCST2', 'TRIM59', 'RPL7AP35', 'ZNF182', 'KIAA1549', 'GMCL1', 'RFC3', 'NTMT2', 'ATP6AP2', 'TNPO1P1', 'C19orf47', 'RPL9P24', 'TNIP3', 'CEPT1', 'DHODH', 'SINHCAFP3', 'SPINK1', 'SLC66A3', 'ACVR1B', 'SUV39H1', 'MTFMT', 'NKD1', 'DLK1', 'ZNF782', 'PFDN2', 'TBCE', 'MTND3P6', 'CXCL1', 'RPL12P22', 'TTC39A', 'GK5', 'SDR16C6P', 'OR2M2', 'COQ4', 'HMGB3P18', 'GMPPA', 'MOSPD3', 'ANKRD53', 'EDEM1', 'RPS2P5', 'LPAR4', 'RANBP3L', 'KANK3', 'ZNF321P', 'NLGN1', 'GATAD1', 'MYOC', 'TEX45', 'SLC47A1P1', 'RFPL4AP4', 'TES', 'ENY2', 'PGBD2', 'FCGR3B', 'DFFB', 'C2CD3', 'MTMR2', 'DPP3', 'E2F8', 'PIGA', 'TMEM233', 'BCL2L1', 'TLCD4-RWDD3', 'ERICH3', 'NUP62', 'C1orf43', 'SYT17', 'MTPN', 'NKTR', 'FRMPD1', 'MAGOHB', 'CTBS', 'RAB17', 'ZNF491', 'ZNF280D', 'OPN1SW', 'RPS27AP5', 'CTDSPL', 'SELENOI', 'NUDT17', 'TRIM27', 'COL4A4', 'C5AR2', 'RPS27L', 'AGK', 'SMIM29', 'ZNF215', 'TRHR', 'UQCR10', 'CARS1', 'CRYBA2', 'LIN7A', 'TCP1', 'RAB26', 'STX10', 'GOLGA8R', 'WSCD2', 'TDG', 'ZNF681', 'NBPF8', 'ASIC2', 'SMPD4', 'TRIM53AP', 'SLC22A4', 'MX2', 'DUSP19', 'GABRA4', 'STX3', 'ARID5A', 'ZIM2', 'PRSS8', 'RNF212B', 'HSD17B7P2', 'FAM124B', 'RPL37P11', 'VPS11', 'LXN', 'CALHM6', 'TBCC', 'SERINC5', 'CFI', 'PPP1R14A', 'ZNF599', 'PFN2', 'TOP1MT', 'RPS13P1', 'ZNF670-ZNF695', 'VPS52', 'TULP3', 'TMPRSS15', 'L3HYPDH', 'PLBD1', 'MS4A4A', 'ZNF286B', 'ATP7B', 'CACNB4', 'ATF1', 'PACS2', 'SPATS2', 'PCDH19', 'LIME1', 'PPIAP90', 'CYB561D2', 'AMY1A', 'ROPN1B', 'ALB', 'EDN3', 'TNRC6C', 'LOC100419654', 'CARNMT1', 'DEFB109C', 'DEFB109B', 'LINC00328-2P', 'PTGR2', 'FABP5P5', 'TRPM7', 'GTF3C2', 'SULF1', 'RGS14', 'TCIM', 'CD55', 'PCDHGA8', 'MOSMO', 'LOC100420114', 'SERINC2', 'IGSF23', 'LIMS1', 'FABP1', 'RBM22', 'CXXC1', 'RPLP0P2', 'LOC102723451', 'LSM2', 'RFESD', 'ATXN1L', 'ASAH1', 'UBA7', 'ZNF738', 'RASL10A', 'DBF4P3', 'NCALD', 'UTS2', 'NME7', 'RPL36AP46', 'CLNS1A', 'NDUFS5P2', 'AASS', 'GLMP', 'EIF4A1', 'NARF', 'CIDEC', 'PLEKHA6', 'VAV1', 'CSK', 'SLU7', 'METAP1D', 'COMMD5', 'NDUFB5P2', 'XBP1', 'OR2AP1', 'ARSB', 'PKNOX2', 'BTAF1', 'LOC729998', 'EBP', 'ARMCX5', 'BPIFB1', 'SNX7', 'YWHAQP7', 'RPL7AP60', 'ZXDB', 'RPL41P2', 'CCNG1', 'ANTXR1', 'AAMP', 'ANKRD20A11P', 'ZC3HAV1', 'CFL1P1', 'MECR', 'CLEC5A', 'CDC14A', 'TP53AIP1', 'ZC3H15', 'TCHP', 'STK33', 'IDH3B', 'BTBD10', 'FMN2', 'CDKL3', 'POLR2J3', 'ATL3', 'TAP1', 'TRBV23OR9-2', 'C7orf31', 'CAPN1', 'CCDC102B', 'LOC642929', 'AKR1B10', 'CTF1', 'RAD51', 'RNF121', 'NCDN', 'MUPP', 'MARCHF1', 'KMT2A', 'ADCY1', 'IGLV3-19', 'ZNF702P', 'GABRP', 'TSEN15', 'ZNF490', 'SLC35B2', 'FNDC3A', 'NYNRIN', 'ALK', 'CHL1', 'ATPAF2', 'TIGD4', 'BMERB1', 'HHEX', 'GTF2IP11', 'PAFAH1B2P2', 'GSDME', 'CILK1', 'RPL27AP6', 'PFKL', 'FAM177A1', 'OPN5', 'FPGT', 'KLC4', 'CDC73', 'CCDC180', 'SNTB2', 'XRCC4', 'PCK2', 'CD84', 'MPZL1', 'MED18', 'ATP6V1G2', 'KIAA0513', 'MIS12', 'DEPDC1B', 'HSP90AA6P', 'NRP2', 'CCDC43', 'MEPCE', 'SNX2', 'KRTAP20-4', 'GTF2A2', 'LGALS2', 'SLC25A32', 'RGS22', 'SLC12A1', 'FUT11', 'SGO1', 'CD101', 'RPL31', 'METTL22', 'NKAP', 'ZNF23', 'GTF2A1L', 'ARPC1A', 'MC2R', 'NOMO3', 'TMED11P', 'HJV', 'ZNF10', 'UGT2B28', 'ALDH18A1', 'NMRAL1', 'RPL26P36', 'TBC1D13', 'TRBV14', 'C12orf76', 'TOMM22P6', 'FZD9', 'DIS3', 'RNF103', 'TMEM97', 'ZNF781', 'RBBP5', 'BNIP3P30', 'MUC7', 'EEF2', 'GPS2', 'MDP1', 'DPH7', 'CLDN11', 'MTND1P15', 'S100B', 'VDAC1', 'DTNBP1', 'KIF16B', 'DHX33', 'CYP4Z2P', 'BIRC6-AS2', 'TAF9', 'XKR6', 'ATP6V1E2', 'CFAP92', 'VRK3', 'MRPS9', 'C7orf25', 'LRRC42', 'CEP120', 'PIP4K2B', 'USP10', 'MAP3K13', 'SERPINF1', 'ARHGEF39', 'MSL3', 'SASH1', 'CSTF2', 'DYDC1', 'GFER', 'FGF9', 'TUBAP4', 'FBXW8', 'SPATA13', 'RASSF5', 'MOB3B', 'CYGB', 'GLI2', 'PSG8', 'PI4KAP1', 'DBI', 'ANKDD1A', 'SHLD3', 'MIF', 'PNMT', 'ZNF230', 'MPG', 'GIPC1', 'ANKRD39', 'UPF3A', 'MAP3K19', 'OR51A2', 'PARVB', 'SOX13', 'SHLD2', 'ZRSR2', 'KPNA4', 'SNRPCP9', 'SLC11A1', 'MAPKAPK5', 'RBAK-RBAKDN', 'CCM2', 'MTND1P6', 'WDR31', 'NEURL4', 'ARMT1', 'TRIM66', 'TMEM229B', 'HNF4G', 'AKNAD1', 'RGS2', 'AVPR1A', 'SLCO1C1', 'CAMK4', 'CDK2AP1', 'RPL23AP5', 'RAB6B', 'LY96', 'PHLDB3', 'ANKEF1', 'TAMALIN', 'HMG20B', 'RPL5P26', 'CHIAP2', 'MYL1', 'RPL35AP10', 'GRM8', 'EPB41L4A', 'ANO6', 'OR2J3', 'CDH6', 'BAX', 'TREM1', 'TAF6', 'RMDN3', 'BNIP1', 'RPH3A', 'WFS1', 'ELAVL2', 'CEMIP2', 'SHMT2', 'HIF1A', 'OR6C64P', 'ATAD3B', 'VWA8', 'TATDN3', 'ABCB1', 'FGF12', 'ASZ1', 'CLDN10', 'DDX20', 'RNA5SP39', 'SLC8A3', 'NOVA2', 'WDR5', 'PISD', 'ACD', 'ART5', 'POP1', 'RTN4', 'PGAP1', 'UROD', 'GGTA2P', 'RND1', 'RNASEH2A', 'GNE', 'DNAJC28', 'ACSM6', 'NPAS3', 'TXNRD2', 'RAB7B', 'AK4', 'C1orf131', 'CGREF1', 'TACR1', 'KIAA1586', 'FBXO42', 'TRIM47', 'NUBP2', 'CFAP91', 'THAP2', 'RBP4', 'SPINK2', 'AP2M1', 'BLM', 'MED8', 'AURKC', 'TACR2', 'RPS15AP30', 'ABHD1', 'MAP9', 'MAB21L1', 'SDHA', 'INHA', 'FTH1P2', 'CLUHP3', 'ANKRD30BL', 'TP53', 'TAF1C', 'IL12RB1', 'ZNF791', 'NDUFA4L2', 'SLC39A10', 'IFT27', 'MFSD4A', 'OR2AM1P', 'PLCZ1', 'DRC1', 'HS6ST2', 'CASP5', 'MTHFD2P1', 'BEX4', 'UPK3BP1', 'ARFIP2', 'NR4A1', 'SDAD1P4', 'MTCO2P1', 'MTCO1P43', 'DOT1L', 'RRBP1', 'KLHL17', 'NUTF2P6', 'CLEC12B', 'RREB1', 'TCFL5', 'GLIPR2', 'FLACC1', 'HIVEP2', 'RPS3AP46', 'UBXN7', 'ANKAR', 'SLC6A13', 'RPL8P5', 'ZNF395', 'RPSAP72', 'LAD1', 'ZNF35', 'ATP13A3', 'RPS6KA6', 'RRAD', 'THRA', 'SCAMP2', 'YIPF6', 'MINK1', 'RACGAP1', 'HSCB', 'CREB3L1', 'OR6J1', 'ZNF799', 'YEATS2', 'RPL31P57', 'TMPRSS4', 'FGFR1', 'OAZ2', 'ANKRD18A', 'TRIM8', 'SPON2', 'ADGRF1', 'OSBP2', 'WDR54', 'MYL10', 'ZNF235', 'FMO1', 'NUDT22', 'SLC5A2', 'AIP', 'SCML4', 'LOC100419830', 'MX1', 'AGTR1', 'ALCAM', 'KCNK6', 'AGBL5', 'SLC6A8', 'ANGPTL4', 'HNRNPA1P42', 'GART', 'OR2G3', 'ARFGAP3', 'SPEF2', 'PNMA2', 'VAMP4', 'HMGB1P31', 'PDIK1L', 'ARL13B', 'RXRG', 'ANKRD13C', 'HELLS', 'PPP6R1', 'RECQL', 'ABCA3', 'SCFD1', 'SPATS2L', 'PTGER4', 'MEIOB', 'RGR', 'N4BP2', 'ZNF674', 'ZNF726', 'LGR4', 'MS4A3', 'SNRPGP12', 'SNX22', 'RNA5SP115', 'OR10J6P', 'GPC3', 'RABAC1', 'MAN1A2', 'ZSCAN32', 'RPL23A

In [107]:
import GSEA_suit as gsea
folder_save = "Results/feature_selection/RNAseq/ridge_L2_0/Union/"
results = gsea.get_GSEA(rank_dict=sets_ranks, database= "GO_Biological_Process_2023", min_size=5, outdir=folder_save)

In [80]:
enrichment = results.res2d
enrichment[enrichment['FDR q-val']<0.5]

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
4,prerank,Monocyte Chemotaxis (GO:0002548),0.60337,1.749518,0.0,0.460129,0.694,8/8,39.71%,CCL2;FOLR2;PTPRO;PDGFB;DEFB104A;CCL26;RPS19;FLT1
5,prerank,Regulation Of Chromosome Separation (GO:1905818),0.66657,1.747433,0.009901,0.349077,0.701,7/7,33.39%,NCAPD3;NCAPD2;NUMA1;NCAPG2;NCAPH2;CSNK2A2;TPR
6,prerank,Nucleotide-Sugar Metabolic Process (GO:0009225),0.534091,1.699603,0.0,0.394311,0.817,9/9,46.64%,SLC35A3;GFPT1;ENTPD5;FUT8;GALT;PARG;UGP2;EXTL2...
7,prerank,Positive Regulation Of Chromosome Separation (...,0.71082,1.675042,0.025478,0.389301,0.86,5/5,28.95%,NCAPD3;NCAPD2;NUMA1;NCAPG2;NCAPH2
8,prerank,Regulation Of Sister Chromatid Cohesion (GO:00...,0.693011,1.671465,0.006061,0.342928,0.865,5/5,30.73%,CTCF;BUB1;DDX11;FEN1;WAPL
9,prerank,Positive Regulation Of Chromatin Binding (GO:0...,0.68839,1.657586,0.01875,0.32768,0.884,5/5,31.19%,PARP9;DDX11;MED9;ZNF618;GMNN
11,prerank,piRNA Processing (GO:0034587),0.593684,1.613513,0.0,0.396544,0.945,7/7,40.67%,MOV10L1;PIWIL4;TDRD9;GPAT2;TEX15;TDRKH;DDX4
19,prerank,Protein Localization To Cell-Cell Junction (GO...,0.541647,1.56201,0.0,0.493436,0.983,8/8,45.88%,SCRIB;ACTG1;PAK2;TJP1;TJP3;LSR;JAK1;ARHGEF18

In [ ]:
# get all the genes in set_sarcopenia from sets_ranks
sarcopenia_scores={}
i = 1
for gene in set_sarcopenia:
    if gene != 0:
        sarcopenia_scores[gene] = int(sets_ranks[gene])
        #i+=1

#sorted_sarcopenia = sorted(sarcopenia_scores.items(), key=lambda x:x[1])
#sarcopenia_scores = dict(sorted_sarcopenia)

#sarcopenia_scores= sorted(sarcopenia_scores)
sarcopenia_scores

{'SCAPER': 57,
 'RPL24': 2277,
 'RPRD1B': 1019,
 'EFNA5': 6093,
 'DYNLL1': 966,
 'NPLOC4': 4973,
 'TRAPPC6B': 10335,
 'GCC1': 8075,
 'KIF5B': 4165,
 'CD36': 565,
 'UCP3': 1392,
 'SRSF3': 4274,
 'ZC3H18': 5118,
 'KHDRBS3': 584,
 'LAP3': 2158,
 'CAAP1': 4836,
 'STARD10': 4922,
 'SMAD9': 3311,
 'RPL18': 1834,
 'CHURC1': 1449,
 'RER1': 686,
 'RAD17': 12545,
 'HMBOX1': 901,
 'FN1': 4000,
 'FIBP': 2954,
 'RBM12B': 3554,
 'ANGPTL1': 5003,
 'ETV6': 5376,
 'STX7': 1422,
 'RNF31': 4669,
 'CIDEB': 5756,
 'TMEM108': 2266,
 'HERC4': 4022,
 'CDC37': 4539,
 'RGMA': 7621,
 'TADA2A': 7870,
 'PACS1': 2249,
 'MRPS28': 5963,
 'POLR2G': 3019,
 'CASK': 4927,
 'ATP2A2': 1520,
 'MAP7D1': 3354,
 'CLPX': 6656,
 'MZT2B': 5927,
 'MAN2A1': 2100,
 'DCTPP1': 5398,
 'KDM3B': 1548,
 'SAP30BP': 3818,
 'NDUFS6': 3857,
 'MYH14': 4245,
 'CHD6': 2325,
 'TMOD4': 4316,
 'EYA4': 2166,
 'GART': 5702,
 'COL1A2': 1727,
 'RSPO3': 70,
 'KALRN': 2120,
 'RABEP2': 497,
 'RAB2B': 10612,
 'AURKAIP1': 5913,
 'DUSP13': 2604,
 'CHMP3': 5925,
 'PF4': 10614,
 'PEX11B': 7168,
 'MYL12A': 3421,
 'GNL2': 1112,
 'MYOM3': 1036,
 'SIKE1': 1779,
 'ERCC5': 787,
 'OTUD4': 1970,
 'DMTF1': 5725,
 'TLK1': 929,
 'SAMD9L': 6743,
 'SPAG7': 9061,
 'MAP4K4': 571,
 'USP14': 7476,
 'SYPL1': 8525,
 'LRP1B': 56,
 'HOXA3': 4076,
 'ABCA10': 1575,
 'MRPS18C': 648,
 'APOC1': 5616,
 'FBL': 4958,
 'DPYSL3': 2726,
 'PRPF8': 1859,
 'KCNN3': 6608,
 'INTS10': 7423,
 'MRPL19': 3339,
 'HDAC9': 3832,
 'VDAC3': 4527,
 'RALGAPA1': 3307,
 'FAM189A2': 7072,
 'CEP85L': 1232,
 'NSUN5': 6893,
 'NDUFB10': 4319,
 'TCEAL3': 4582,
 'CNTD1': 8043,
 'RETREG2': 7773,
 'DRAM2': 5903,
 'CASQ2': 1015,
 'DOK4': 11074,
 'RNF187': 8930,
 'POP5': 1832,
 'S100A1': 5835,
 'KIAA0319L': 2285,
 'MRPS27': 3048,
 'PPM1K': 5533,
 'SLC16A3': 3678,
 'FGL2': 2739,
 'DGKD': 4557,
 'OMA1': 558,
 'AUP1': 10379,
 'UQCRH': 147,
 'MOK': 1993,
 'MYL2': 884,
 'PIK3CA': 3615,
 'EIF1B': 11895,
 'CCDC141': 1254,
 'ZNF836': 4112,
 'PFDN5': 1373,
 'MYLK3': 309,
 'PSMD4': 8857,
 'FLNC': 1328,
 'RDH12': 7930,
 'UGGT2': 6107,
 'KHSRP': 5889,
 'MTCO1P12': 5404,
 'PTTG1IP': 3922,
 'GSTP1': 6671,
 'FKBP5': 242,
 'ABCF1': 8209,
 'MRPS21': 5830,
 'FTO': 5448,
 'KCNJ11': 5261,
 'ILKAP': 2366,
 'DNAJB1': 1928,
 'PDHB': 1617,
 'PDLIM7': 574,
 'SOX6': 2600,
 'CCNT2': 2007,
 'CEP68': 3402,
 'TNNC1': 1369,
 'DNAJC3': 10076,
 'GRIPAP1': 9040,
 'CBFB': 3009,
 'RRM1': 893,
 'PPP6R3': 6716,
 'TAF13': 2348,
 'NBPF14': 4163,
 'ZNF644': 2143,
 'NPC1': 2994,
 'CTCF': 915,
 'RALB': 10292,
 'DDB1': 3813,
 'DDX46': 672,
 'CLK3': 2717,
 'NIBAN1': 421,
 'BRD8': 2906,
 'DYNLRB1': 6833,
 'APIP': 4488,
 'CHCHD3': 1527,
 'TK2': 2613,
 'COX2': 577,
 'NFATC3': 1647,
 'ARHGDIA': 4676,
 'EMC8': 8458,
 'PRMT7': 4105,
 'SOS1': 2312,
 'WIPF3': 548,
 'CARS2': 3058,
 'SCML1': 3785,
 'NOVA1': 5799,
 'TCEAL1': 6414,
 'ADCY2': 2549,
 'PCGF5': 1042,
 'APBB2': 1390,
 'TPM3': 830,
 'IFT80': 5012,
 'STXBP5': 3150,
 'ARX': 2128,
 'DTNBP1': 6728,
 'MME': 1372,
 'SULF1': 2592,
 'CNNM3': 3552,
 'KDM5A': 1123,
 'CYLD': 4674,
 'ATMIN': 5627,
 'RPS27': 2098}

In [55]:
folder_save = "Results/feature_selection/RNAseq/ridge_L2_0/Sarcopenia_only/"
results = gsea.get_GSEA(rank_dict=ranks_sarcopenia, database= "GO_Biological_Process_2023", min_size=10, outdir=folder_save)
enrichment = results.res2d
enrichment[enrichment['FDR q-val']<0.5]

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,Regulation Of Transcription By RNA Polymerase ...,-0.416095,-1.883857,0.016077,0.040161,0.032313,9/15,22.43%,DNAJB1;SMAD9;CBFB;ETV6;APBB2;HMBOX1;HDAC9;CHD6...
1,prerank,Regulation Of DNA-templated Transcription (GO:...,-0.333359,-1.424825,0.086567,0.099398,0.139456,7/13,22.43%,SMAD9;CBFB;ETV6;APBB2;HMBOX1;HDAC9;TADA2A

In [ ]:
enrichment

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,Pathways in cancer,0.602273,1.407538,0.075775,1.0,0.552,6/7,39.04%,TPM3;ADCY2;SOS1;RALB;GSTP1;PIK3CA
1,prerank,Phospholipase D signaling pathway,0.593407,1.261982,0.162651,1.0,0.801,5/5,42.25%,ADCY2;SOS1;RALB;PIK3CA;DGKD
2,prerank,Cardiac muscle contraction,0.553141,1.246202,0.190092,1.0,0.829,5/6,40.64%,TPM3;COX2;TNNC1;MYL2;UQCRH
3,prerank,Dilated cardiomyopathy (DCM),0.552211,1.174796,0.241718,0.989676,0.917,4/5,39.57%,TPM3;ADCY2;TNNC1;MYL2
4,prerank,Adrenergic signaling in cardiomyocytes,0.552211,1.174796,0.241718,0.989676,0.917,4/5,39.57%,TPM3;ADCY2;TNNC1;MYL2
5,prerank,Thermogenesis,0.49645,1.167662,0.246085,0.851081,0.924,3/7,13.90%,ADCY2;SOS1;COX2
6,prerank,Hepatitis B,0.526488,1.12439,0.297101,0.876644,0.952,3/5,18.72%,SOS1;NFATC3;DDB1
7,prerank,MAPK signaling pathway,0.505906,1.074385,0.352871,0.923692,0.97,3/5,35.29%,SOS1;NFATC3;FLNC
8,prerank,Focal adhesion,0.431552,1.050279,0.407572,0.893425,0.981,5/8,39.57%,SOS1;FLNC;MYLK3;PIK3CA;MYL2
9,prerank,cGMP-PKG signaling pathway,0.446508,0.952337,0.527578,1.0,0.995,2/5,13.37%,ADCY2;NFATC3
10,prerank,Regulation of actin cytoskeleton,0.400185,0.944434,0.537931,0.992594,0.995,4/7,39.57%,SOS1;MYLK3;PIK3CA;MYL2
11,prerank,Alzheimer disease,0.403951,0.907014,0.60814,0.996893,0.998,2/6,13.90%,MME;COX2
12,prerank,Non-alcoholic fatty liver disease (NAFLD),0.414077,0.893147,0.620813,0.949615,0.998,4/5,50.27%,COX2;PIK3CA;UQCRH;NDUFB10
13,prerank,Calcium signaling pathway,0.412223,0.880075,0.627381,0.910187,0.999,3/5,36.36%,ADCY2;TNNC1;MYLK3
14,prerank,Ribosome,0.384238,0.869693,0.654888,0.870273,0.999,4/6,57.75%,RPS27;MRPS21;MRPL19;MRPS18C
15,prerank,Parkinson disease,0.381944,0.825334,0.718861,0.899431,1.0,4/5,52.94%,COX2;UQCRH;NDUFB10;VDAC3
16,prerank,Platelet activation,0.389396,0.825033,0.715674,0.846939,1.0,3/5,39.04%,ADCY2;MYLK3;PIK3CA
17,prerank,Axon guidance,0.339057,0.729864,0.846059,0.939964,1.0,2/5,39.04%,NFATC3;PIK3CA
18,prerank,Huntington disease,0.314847,0.717921,0.858458,0.904651,1.0,4/6,52.94%,COX2;UQCRH;NDUFB10;VDAC3
19,prerank,PI3K-Akt signaling pathway,0.315964,0.704956,0.889535,0.874167,1.0,2/6,39.04%,SOS1;PIK3CA