In [18]:
import pandas as pd
import pickle
training= "/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/Data/RNAseq_abundances_adjusted_combat_inmose.csv"
#training = "/home/karen/Documents/GitHub/batch_correction/Data/RNAseq_All_counts_unadjusted_integer.csv"

In [19]:
training_df = pd.read_csv(training)
training_df

/tmp/ipykernel_58465/810663661.py:1: DtypeWarning: Columns (34508) have mixed types. Specify dtype option on import or set low_memory=False.
  training_df = pd.read_csv(training)

,Sample,ENSG00000000003.14,ENSG00000000005.5,ENSG00000000419.12,ENSG00000000457.13,ENSG00000000460.16,ENSG00000000938.12,ENSG00000000971.15,ENSG00000001036.13,ENSG00000001084.11,...,ENSG00000285476.1,ENSG00000285480.1,ENSG00000285491.1,ENSG00000285505.1,ENSG00000285508.1,ENSG00000285509.1,Age,Experiment,Sex,Status
0,SRR13758984,21281762,0,15759712,0,11295483,0,35294310,0,18333093,...,0,0,0,0,2773,0,91.0,GSE167186,NaN,Sarcopenia
1,SRR13758985,8542646,0,15035432,0,0,0,26637602,0,1389125,...,0,0,0,0,1328,0,86.0,GSE167186,male,Healthy
2,SRR13758986,4079945,0,5410942,0,5658191,0,10946301,4491317,7747412,...,0,0,0,0,1,0,69.0,GSE167186,male,Healthy
3,SRR13758987,14758557,0,12809471,0,0,0,24093106,0,11562944,...,0,0,0,0,1614,0,83.0,GSE167186,NaN,Sarcopenia
4,SRR13758988,3623061,0,15529838,23957067,0,0,25492722,10773730,12889518,...,0,0,0,0,795,0,71.0,GSE167186,NaN,UNCLASSIFIED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,SRR1555210,37402439,0,21355420,1,1212397,1,87213838,3370216,5884457,...,3582648,0,0,0,0,5351828,27.5,GSE60590,male,trained
266,SRR1555211,48027788,0,89024445,1348907,24399,1,148387777,3685378,113719675,...,0,1956002,0,0,0,0,27.5,GSE60590,male,untrained
267,SRR1555212,84899250,0,167383416,407713,37284600,1,219777948,58357903,79405469,...,0,824055,0,1040940,12712840,5952181,27.5,GSE60590,male,trained
268,SRR1555213,35885217,1428536,44248179,19331,2896856,110080,73026055,17457124,30839652,...,0,873096,0,0,0,0,27.5,GSE60590,male,trained
269,SRR1555214,10643864,0,46372444,129439,7344040,1,57547797,1832373,12467741,...,8586586,1146976,0,0,0,1260520,27.5,GSE60590,male,untrained

In [9]:
test_data = training_df
test_data.columns

Index(['ENSG00000000003.14', 'ENSG00000000005.5', 'ENSG00000000419.12',
       'ENSG00000000457.13', 'ENSG00000000460.16', 'ENSG00000000938.12',
       'ENSG00000000971.15', 'ENSG00000001036.13', 'ENSG00000001084.11',
       'ENSG00000001167.14',
       ...
       'ENSG00000285480.1', 'ENSG00000285491.1', 'ENSG00000285505.1',
       'ENSG00000285508.1', 'ENSG00000285509.1', 'Age', 'Status', 'Sex',
       'Experiment', 'Sample'],
      dtype='object', length=34510)

In [10]:

X_test_data = test_data[test_data.columns[:-5]]
z_test_data = test_data[test_data.columns[-4:]]
y_test_data = test_data["Age"]
z_test_data = z_test_data["Experiment"]

In [11]:
df= pd.DataFrame({'Age': y_test_data, 'Experiment': z_test_data})
df = df.set_index(pd.Index(range(len(df)))) #Setting the sample as index

df

      Age Experiment
0    91.0  GSE167186
1    86.0  GSE167186
2    69.0  GSE167186
3    83.0  GSE167186
4    71.0  GSE167186
..    ...        ...
265  27.5   GSE60590
266  27.5   GSE60590
267  27.5   GSE60590
268  27.5   GSE60590
269  27.5   GSE60590

[270 rows x 2 columns]

In [14]:
catboost_model = pickle.load(open('Shap_values/RNAs_z_Combat_7_SMOTE_seq_regressor_556i_07.pkl', 'rb'))

In [15]:
y_pred = catboost_model.predict(X_test_data)
y_pred

array([48.84633236, 48.58183844, 48.2061438 , 49.2974799 , 48.59571091,
       48.58711173, 48.3740867 , 49.09323049, 48.44187528, 48.99574943,
       48.50628449, 48.5288919 , 49.45769497, 48.63754797, 48.50396047,
       49.28195889, 48.17432865, 48.60074732, 46.68503479, 48.52369831,
       48.56993566, 46.46133603, 48.61611447, 48.71331807, 48.73331223,
       48.43084835, 48.5294926 , 48.57856685, 48.92319525, 48.81560007,
       48.32908548, 48.77455086, 48.90448503, 48.74527071, 48.35423685,
       48.92244155, 48.70956992, 47.86885483, 48.33138571, 48.52363905,
       48.87904102, 48.70136487, 49.26256604, 48.85643481, 49.4077756 ,
       48.7192785 , 48.47861241, 48.36928608, 49.13457972, 48.48151584,
       48.63115345, 48.50083791, 48.08686164, 48.57508211, 48.89189554,
       44.93860741, 48.25005983, 48.06452532, 49.15709236, 49.10278647,
       49.40515714, 48.89185556, 49.29683523, 48.68631706, 48.8885747 ,
       48.89926444, 48.66023977, 48.39608372, 48.38955664, 48.68414476,
       49.3016149 , 48.98001424, 48.92352981, 48.71314885, 48.78796517,
       49.24459864, 49.21420424, 50.07904585, 49.48942369, 49.81626683,
       49.63879803, 49.38778954, 49.35924888, 52.27801185, 48.9857273 ,
       49.37077194, 49.76906849, 48.9857273 , 49.41543666, 51.86199804,
       49.90823209, 49.91058344, 48.62056686, 49.62601574, 49.85148864,
       48.69170312, 49.09264311, 52.42959237, 49.90823209, 52.1636054 ,
       49.81861818, 49.88145232, 50.04991473, 52.1636054 , 49.24459864,
       49.21420424, 50.07904585, 49.48942369, 49.81626683, 49.63879803,
       49.38778954, 49.35924888, 52.27801185, 48.9857273 , 49.37077194,
       49.76906849, 48.9857273 , 49.41543666, 51.86199804, 49.90823209,
       49.91058344, 48.62056686, 49.62601574, 49.85148864, 48.69170312,
       49.09264311, 52.18048728, 49.69246914, 52.42959237, 49.90823209,
       52.10691361, 52.1636054 , 49.37077194, 49.81861818, 52.1636054 ,
       49.88145232, 50.04991473, 52.37936835, 52.43657637, 49.29289396,
       52.06224889, 49.81626683, 52.09003173, 52.30579468, 49.69246914,
       49.91058344, 51.96754394, 52.26112996, 50.01749925, 52.29782404,
       52.3310781 , 52.35043733, 52.35043733, 52.35043733, 52.36731922,
       52.369463  , 52.24209683, 52.34795998, 52.35043733, 52.3310781 ,
       52.30649207, 52.3310781 , 52.35043733, 52.36731922, 52.30649207,
       52.38634489, 52.35043733, 52.36698565, 52.35043733, 52.3310781 ,
       52.35043733, 52.35043733, 52.3310781 , 52.35043733, 52.35043733,
       52.24352152, 52.21283971, 52.22663964, 52.23620396, 52.35043733,
       52.38634489, 52.3310781 , 52.3310781 , 52.35043733, 52.34795998,
       52.36000166, 52.36731922, 52.38634489, 52.35043733, 52.34795998,
       52.34795998, 52.36731922, 52.3310781 , 52.36731922, 52.36731922,
       52.25341941, 52.23653753, 52.24352152, 52.36033522, 52.19870579,
       52.20205362, 52.23219895, 52.35043733, 52.35043733, 52.36000166,
       52.3310781 , 52.3310781 , 52.36033522, 52.35043733, 52.33938537,
       52.35043733, 52.21283971, 52.28883549, 52.36033522, 52.22663964,
       52.34795998, 52.24352152, 52.35043733, 52.3310781 , 52.34097599,
       52.22663964, 52.22663964, 52.35010377, 52.35010377, 52.3310781 ,
       52.35043733, 52.3310781 , 52.30649207, 52.3310781 , 52.35043733,
       52.35043733, 52.35043733, 52.36731922, 52.3310781 , 52.10691361,
       52.10691361, 52.10691361, 52.10691361, 52.10691361, 52.34845821,
       52.38684312, 52.53963514, 52.2975839 , 52.51368042, 52.32387219,
       52.32387219, 52.56422116, 52.34289786, 52.56422116, 52.2975839 ,
       52.32387219, 52.34845821, 52.27855823, 52.53963514, 52.5755427 ,
       52.32387219, 52.34323143, 52.51368042, 52.5189072 , 52.53963514,
       52.32387219, 52.56422116, 52.55866081, 52.32387219, 52.53963514,
       52.53963514, 52.49432118, 52.53963514, 52.55866081, 52.49432118])

In [16]:
# Calculate evaluation metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test_data, y_pred)
rmse = mean_squared_error(y_test_data, y_pred, squared=False)  # Calculate RMSE from MSE
mae = mean_absolute_error(y_test_data, y_pred)
r2 = r2_score(y_test_data, y_pred)


result_metrics = {"Method": "Catboost",  "MSE": mse, "RMSE": rmse, "MAE": mae, "R2": r2}


results = pd.DataFrame({'Actual': y_test_data, 'Predicted': y_pred, 'Group': z_test_data})

/home/karen/Documents/GitHub/Identify_muscle_age_genes/deep_learning/.venv/lib/python3.11/site-packages/sklearn/metrics/_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [17]:
results

     Actual  Predicted      Group
0      91.0  48.846332  GSE167186
1      86.0  48.581838  GSE167186
2      69.0  48.206144  GSE167186
3      83.0  49.297480  GSE167186
4      71.0  48.595711  GSE167186
..      ...        ...        ...
265    27.5  52.539635   GSE60590
266    27.5  52.494321   GSE60590
267    27.5  52.539635   GSE60590
268    27.5  52.558661   GSE60590
269    27.5  52.494321   GSE60590

[270 rows x 3 columns]